/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const init = IDL.Record({ 'governor' : IDL.Principal });
  const result_nat64 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const assign_request = IDL.Record({
    'shard' : IDL.Principal,
    'expected_revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const route = IDL.Record({
    'shard' : IDL.Principal,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const assign_result = IDL.Record({ 'revision' : IDL.Nat64, 'route' : route });
  const result_assign = IDL.Variant({ 'Ok' : assign_result, 'Err' : IDL.Text });
  const assign_domain_request = IDL.Record({
    'domain' : IDL.Text,
    'shard' : IDL.Principal,
    'expected_revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const domain_route = IDL.Record({
    'domain' : IDL.Text,
    'shard' : IDL.Principal,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const assign_domain_result = IDL.Record({
    'revision' : IDL.Nat64,
    'route' : domain_route,
  });
  const result_assign_domain = IDL.Variant({
    'Ok' : assign_domain_result,
    'Err' : IDL.Text,
  });
  const domain_migration = IDL.Record({
    'destination' : IDL.Principal,
    'domain' : IDL.Text,
    'source' : IDL.Principal,
    'route_revision' : IDL.Nat64,
    'club_id' : IDL.Text,
    'migration_revision' : IDL.Nat64,
  });
  const result_domain_migration = IDL.Variant({
    'Ok' : domain_migration,
    'Err' : IDL.Text,
  });
  const migration = IDL.Record({
    'destination' : IDL.Principal,
    'source' : IDL.Principal,
    'route_revision' : IDL.Nat64,
    'club_id' : IDL.Text,
    'migration_revision' : IDL.Nat64,
  });
  const result_migration = IDL.Variant({ 'Ok' : migration, 'Err' : IDL.Text });
  const result_opt_domain_migration = IDL.Variant({
    'Ok' : IDL.Opt(domain_migration),
    'Err' : IDL.Text,
  });
  const result_opt_domain_route = IDL.Variant({
    'Ok' : IDL.Opt(domain_route),
    'Err' : IDL.Text,
  });
  const result_opt_migration = IDL.Variant({
    'Ok' : IDL.Opt(migration),
    'Err' : IDL.Text,
  });
  const result_opt_route = IDL.Variant({
    'Ok' : IDL.Opt(route),
    'Err' : IDL.Text,
  });
  const page = IDL.Record({
    'next' : IDL.Opt(IDL.Text),
    'routes' : IDL.Vec(route),
    'revision' : IDL.Nat64,
  });
  const result_page = IDL.Variant({ 'Ok' : page, 'Err' : IDL.Text });
  
  return IDL.Service({
    'abort_domain_migration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [result_nat64],
        [],
      ),
    'abort_migration' : IDL.Func([IDL.Text, IDL.Nat64], [result_nat64], []),
    'assign' : IDL.Func([assign_request], [result_assign], []),
    'assign_domain' : IDL.Func(
        [assign_domain_request],
        [result_assign_domain],
        [],
      ),
    'begin_domain_migration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat64],
        [result_domain_migration],
        [],
      ),
    'begin_migration' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat64],
        [result_migration],
        [],
      ),
    'commit_domain_migration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [result_assign_domain],
        [],
      ),
    'commit_migration' : IDL.Func([IDL.Text, IDL.Nat64], [result_assign], []),
    'get_domain_migration' : IDL.Func(
        [IDL.Text, IDL.Text],
        [result_opt_domain_migration],
        ['query'],
      ),
    'get_domain_route' : IDL.Func(
        [IDL.Text, IDL.Text],
        [result_opt_domain_route],
        ['query'],
      ),
    'get_migration' : IDL.Func([IDL.Text], [result_opt_migration], ['query']),
    'get_route' : IDL.Func([IDL.Text], [result_opt_route], ['query']),
    'list_routes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat16],
        [result_page],
        ['query'],
      ),
    'version' : IDL.Func([], [IDL.Nat64], ['query']),
  });
};

export const init = ({ IDL }) => {
  const init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [init];
};