/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const status = IDL.Variant({
    'Failed' : IDL.Null,
    'Delivered' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const notification = IDL.Record({
    'id' : IDL.Text,
    'status' : status,
    'body' : IDL.Text,
    'club' : IDL.Text,
    'next_attempt_ms' : IDL.Nat64,
    'kind' : IDL.Text,
    'user' : IDL.Text,
    'attempts' : IDL.Nat32,
    'idempotency_key' : IDL.Text,
  });
  const result = IDL.Variant({ 'Ok' : notification, 'Err' : IDL.Text });
  const results = IDL.Variant({
    'Ok' : IDL.Vec(notification),
    'Err' : IDL.Text,
  });
  const result_nat16 = IDL.Variant({ 'Ok' : IDL.Nat16, 'Err' : IDL.Text });
  
  return IDL.Service({
    'acknowledge' : IDL.Func([IDL.Text, IDL.Text], [result], []),
    'claim' : IDL.Func([IDL.Nat64, IDL.Nat16], [results], []),
    'enqueue' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [result],
        [],
      ),
    'fail' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat64)], [result], []),
    'get_notification' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(notification)],
        ['query'],
      ),
    'grant_worker' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'recover' : IDL.Func([], [result_nat16], []),
  });
};

export const init = ({ IDL }) => { return []; };