/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface notification {
  'id' : string,
  'status' : status,
  'body' : string,
  'club' : string,
  'next_attempt_ms' : bigint,
  'kind' : string,
  'user' : string,
  'attempts' : number,
  'idempotency_key' : string,
}
export type result = { 'Ok' : notification } |
  { 'Err' : string };
export type result_nat16 = { 'Ok' : number } |
  { 'Err' : string };
export type results = { 'Ok' : Array<notification> } |
  { 'Err' : string };
export type status = { 'Failed' : null } |
  { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'acknowledge' : ActorMethod<[string, string], result>,
  'claim' : ActorMethod<[bigint, number], results>,
  'enqueue' : ActorMethod<
    [string, string, string, string, string, string],
    result
  >,
  'fail' : ActorMethod<[string, string, [] | [bigint]], result>,
  'get_notification' : ActorMethod<[string], [] | [notification]>,
  'grant_worker' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'recover' : ActorMethod<[], result_nat16>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];