/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/secret_workload_identity.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface WorkloadIdentity {
    status: Variant_Active_Suspended_Revoked;
    workload_name: string;
    workload_principal: Principal;
    allowed_scopes: Array<string>;
    last_used: bigint;
    registered_at: bigint;
}
export interface AuditSummary {
    total_accesses: bigint;
    denied: bigint;
    approved: bigint;
}
export interface WorkloadIdentityFilter {
    opt_from_ts?: bigint;
    opt_to_ts?: bigint;
    opt_scope?: string;
    opt_principal?: Principal;
}
export interface SecretAccessResult {
    approved: boolean;
    timestamp: bigint;
    reason: string;
}
export interface SecretAccessAudit {
    workload_name: string;
    requesting_principal: Principal;
    secret_scope: string;
    approved: boolean;
    nonce: string;
    timestamp: bigint;
    denial_reason?: string;
}
export enum Variant_Active_Suspended_Revoked {
    Active = "Active",
    Suspended = "Suspended",
    Revoked = "Revoked"
}
/**
 * / Secret Workload Identity Canister
 * / Manages workload identity registration and vault secret access control
 * / Enforces least-privilege access to vault secrets by canister principal
 */
export interface secret_workload_identityInterface {
    audit_secret_access(filter: WorkloadIdentityFilter): Promise<Array<SecretAccessAudit>>;
    get_audit_summary(): Promise<AuditSummary>;
    get_workload(workload_principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_workloads(): Promise<Array<WorkloadIdentity>>;
    register_workload(workload_principal: Principal, workload_name: string, allowed_scopes: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    revoke_workload(workload_principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_workload_scopes(workload_principal: Principal, allowed_scopes: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    verify_secret_access(workload_principal: Principal, secret_scope: string, nonce: string): Promise<SecretAccessResult>;
}
import type { SecretAccessAudit as _SecretAccessAudit, WorkloadIdentity as _WorkloadIdentity, WorkloadIdentityFilter as _WorkloadIdentityFilter } from "./declarations/secret_workload_identity.did";
export class Secret_workload_identity implements secret_workload_identityInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async audit_secret_access(arg0: WorkloadIdentityFilter): Promise<Array<SecretAccessAudit>> {
        const result = await this.actor.audit_secret_access(to_candid_WorkloadIdentityFilter_n1(arg0));
        return from_candid_vec_n3(result);
    }
    async get_audit_summary(): Promise<AuditSummary> {
        const result = await this.actor.get_audit_summary();
        return result;
    }
    async get_workload(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_workload(arg0);
        return from_candid_variant_n7(result);
    }
    async initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize();
        return from_candid_variant_n11(result);
    }
    async list_workloads(): Promise<Array<WorkloadIdentity>> {
        const result = await this.actor.list_workloads();
        return from_candid_vec_n12(result);
    }
    async register_workload(arg0: Principal, arg1: string, arg2: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.register_workload(arg0, arg1, arg2);
        return from_candid_variant_n7(result);
    }
    async revoke_workload(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.revoke_workload(arg0);
        return from_candid_variant_n11(result);
    }
    async update_workload_scopes(arg0: Principal, arg1: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: WorkloadIdentity;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_workload_scopes(arg0, arg1);
        return from_candid_variant_n7(result);
    }
    async verify_secret_access(arg0: Principal, arg1: string, arg2: string): Promise<SecretAccessResult> {
        const result = await this.actor.verify_secret_access(arg0, arg1, arg2);
        return result;
    }
}
function from_candid_SecretAccessAudit_n4(value: _SecretAccessAudit): SecretAccessAudit {
    return from_candid_record_n5(value);
}
function from_candid_WorkloadIdentity_n8(value: _WorkloadIdentity): WorkloadIdentity {
    return from_candid_record_n9(value);
}
function from_candid_opt_n6(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(value: {
    workload_name: string;
    requesting_principal: Principal;
    secret_scope: string;
    approved: boolean;
    nonce: string;
    timestamp: bigint;
    denial_reason: [] | [string];
}): {
    workload_name: string;
    requesting_principal: Principal;
    secret_scope: string;
    approved: boolean;
    nonce: string;
    timestamp: bigint;
    denial_reason?: string;
} {
    return {
        workload_name: value.workload_name,
        requesting_principal: value.requesting_principal,
        secret_scope: value.secret_scope,
        approved: value.approved,
        nonce: value.nonce,
        timestamp: value.timestamp,
        denial_reason: record_opt_to_undefined(from_candid_opt_n6(value.denial_reason))
    };
}
function from_candid_record_n9(value: {
    status: {
        Active: null;
    } | {
        Suspended: null;
    } | {
        Revoked: null;
    };
    workload_name: string;
    workload_principal: Principal;
    allowed_scopes: Array<string>;
    last_used: bigint;
    registered_at: bigint;
}): {
    status: Variant_Active_Suspended_Revoked;
    workload_name: string;
    workload_principal: Principal;
    allowed_scopes: Array<string>;
    last_used: bigint;
    registered_at: bigint;
} {
    return {
        status: from_candid_variant_n10(value.status),
        workload_name: value.workload_name,
        workload_principal: value.workload_principal,
        allowed_scopes: value.allowed_scopes,
        last_used: value.last_used,
        registered_at: value.registered_at
    };
}
function from_candid_variant_n10(value: {
    Active: null;
} | {
    Suspended: null;
} | {
    Revoked: null;
}): Variant_Active_Suspended_Revoked {
    return "Active" in value ? Variant_Active_Suspended_Revoked.Active : "Suspended" in value ? Variant_Active_Suspended_Revoked.Suspended : "Revoked" in value ? Variant_Active_Suspended_Revoked.Revoked : value;
}
function from_candid_variant_n11(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: _WorkloadIdentity;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: WorkloadIdentity;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_WorkloadIdentity_n8(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n12(value: Array<_WorkloadIdentity>): Array<WorkloadIdentity> {
    return value.map((x)=>from_candid_WorkloadIdentity_n8(x));
}
function from_candid_vec_n3(value: Array<_SecretAccessAudit>): Array<SecretAccessAudit> {
    return value.map((x)=>from_candid_SecretAccessAudit_n4(x));
}
function to_candid_WorkloadIdentityFilter_n1(value: WorkloadIdentityFilter): _WorkloadIdentityFilter {
    return to_candid_record_n2(value);
}
function to_candid_record_n2(value: {
    opt_from_ts?: bigint;
    opt_to_ts?: bigint;
    opt_scope?: string;
    opt_principal?: Principal;
}): {
    opt_from_ts: [] | [bigint];
    opt_to_ts: [] | [bigint];
    opt_scope: [] | [string];
    opt_principal: [] | [Principal];
} {
    return {
        opt_from_ts: value.opt_from_ts ? candid_some(value.opt_from_ts) : candid_none(),
        opt_to_ts: value.opt_to_ts ? candid_some(value.opt_to_ts) : candid_none(),
        opt_scope: value.opt_scope ? candid_some(value.opt_scope) : candid_none(),
        opt_principal: value.opt_principal ? candid_some(value.opt_principal) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Secret_workload_identity {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Secret_workload_identity(actor);
}
