/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Phase = IDL.Variant({
    'exported' : IDL.Null,
    'verified' : IDL.Null,
    'aborted' : IDL.Null,
    'imported' : IDL.Null,
    'started' : IDL.Null,
    'committed' : IDL.Null,
  });
  const Migration = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Principal,
    'domain' : IDL.Text,
    'source' : IDL.Principal,
    'checksum' : IDL.Text,
    'schemaVersion' : IDL.Nat,
    'phase' : Phase,
    'recordCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'abort' : IDL.Func([IDL.Nat], [Migration], []),
    'begin' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Principal, IDL.Nat, IDL.Text],
        [Migration],
        [],
      ),
    'commit' : IDL.Func([IDL.Nat], [Migration], []),
    'initialize' : IDL.Func([], [], []),
    'markExported' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [Migration], []),
    'markImported' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [Migration], []),
    'status' : IDL.Func(
        [],
        [IDL.Opt(Migration), IDL.Vec(Migration)],
        ['query'],
      ),
    'verify' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [Migration], []),
  });
};

export const init = ({ IDL }) => { return []; };