/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/competition_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
};
export interface TeamEntry {
    status: string;
    team_id: string;
    competition_id: string;
    club_id: string;
}
export type Result_6 = {
    __kind__: "Ok";
    Ok: Match;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Init {
    governor: Principal;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Match {
    id: string;
    status: string;
    home_team: string;
    away_team: string;
    away_score: number;
    home_score: number;
    revision: bigint;
    competition_id: string;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: JoinToken;
} | {
    __kind__: "Err";
    Err: string;
};
export interface RoleGrant {
    role: string;
    user: Principal;
    team_id?: string;
    competition_id: string;
}
export interface JoinToken {
    id: string;
    issued_by: Principal;
    used: boolean;
    team_id: string;
    competition_id: string;
    expires_at_ms: bigint;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Season {
    status: string;
    name: string;
    revision: bigint;
    competition_id: string;
}
export type Result = {
    __kind__: "Ok";
    Ok: Competition;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: TeamEntry;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Competition {
    id: string;
    status: string;
    name: string;
    season: string;
    revision: bigint;
    club_id: string;
}
export type Result_7 = {
    __kind__: "Ok";
    Ok: Season;
} | {
    __kind__: "Err";
    Err: string;
};
export interface State {
    seasons: Array<Season>;
    schema: number;
    entries: Array<TeamEntry>;
    matches: Array<Match>;
    tokens: Array<JoinToken>;
    governor: Principal;
    competitions: Array<Competition>;
    roles: Array<RoleGrant>;
}
export interface competition_domainInterface {
    claim_join_token(arg0: string): Promise<Result_5>;
    create_competition(arg0: string, arg1: string, arg2: string): Promise<Result>;
    create_season(arg0: string, arg1: string): Promise<Result_7>;
    export_state(): Promise<Result_2>;
    grant_role(arg0: Principal, arg1: string, arg2: string, arg3: string | null): Promise<Result_4>;
    issue_join_token(arg0: string, arg1: string, arg2: bigint): Promise<Result_1>;
    record_match(arg0: string, arg1: string, arg2: string): Promise<Result_6>;
    register_team(arg0: string, arg1: string, arg2: string): Promise<Result_3>;
    set_match_result(arg0: string, arg1: number, arg2: number, arg3: bigint): Promise<Result_6>;
    set_season_status(arg0: string, arg1: string, arg2: bigint): Promise<Result_7>;
}
import type { Competition as _Competition, JoinToken as _JoinToken, Match as _Match, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, RoleGrant as _RoleGrant, Season as _Season, State as _State, TeamEntry as _TeamEntry } from "./declarations/competition_domain.did";
export class Competition_domain implements competition_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async claim_join_token(arg0: string): Promise<Result_5> {
        const result = await this.actor.claim_join_token(arg0);
        return from_candid_Result_5_n1(result);
    }
    async create_competition(arg0: string, arg1: string, arg2: string): Promise<Result> {
        const result = await this.actor.create_competition(arg0, arg1, arg2);
        return from_candid_Result_n3(result);
    }
    async create_season(arg0: string, arg1: string): Promise<Result_7> {
        const result = await this.actor.create_season(arg0, arg1);
        return from_candid_Result_7_n5(result);
    }
    async export_state(): Promise<Result_2> {
        const result = await this.actor.export_state();
        return from_candid_Result_2_n7(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string, arg3: string | null): Promise<Result_4> {
        const result = await this.actor.grant_role(arg0, arg1, arg2, to_candid_opt_n15(arg3));
        return from_candid_Result_4_n16(result);
    }
    async issue_join_token(arg0: string, arg1: string, arg2: bigint): Promise<Result_1> {
        const result = await this.actor.issue_join_token(arg0, arg1, arg2);
        return from_candid_Result_1_n18(result);
    }
    async record_match(arg0: string, arg1: string, arg2: string): Promise<Result_6> {
        const result = await this.actor.record_match(arg0, arg1, arg2);
        return from_candid_Result_6_n20(result);
    }
    async register_team(arg0: string, arg1: string, arg2: string): Promise<Result_3> {
        const result = await this.actor.register_team(arg0, arg1, arg2);
        return from_candid_Result_3_n22(result);
    }
    async set_match_result(arg0: string, arg1: number, arg2: number, arg3: bigint): Promise<Result_6> {
        const result = await this.actor.set_match_result(arg0, arg1, arg2, arg3);
        return from_candid_Result_6_n20(result);
    }
    async set_season_status(arg0: string, arg1: string, arg2: bigint): Promise<Result_7> {
        const result = await this.actor.set_season_status(arg0, arg1, arg2);
        return from_candid_Result_7_n5(result);
    }
}
function from_candid_Result_1_n18(value: _Result_1): Result_1 {
    return from_candid_variant_n19(value);
}
function from_candid_Result_2_n7(value: _Result_2): Result_2 {
    return from_candid_variant_n8(value);
}
function from_candid_Result_3_n22(value: _Result_3): Result_3 {
    return from_candid_variant_n23(value);
}
function from_candid_Result_4_n16(value: _Result_4): Result_4 {
    return from_candid_variant_n17(value);
}
function from_candid_Result_5_n1(value: _Result_5): Result_5 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_6_n20(value: _Result_6): Result_6 {
    return from_candid_variant_n21(value);
}
function from_candid_Result_7_n5(value: _Result_7): Result_7 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_n3(value: _Result): Result {
    return from_candid_variant_n4(value);
}
function from_candid_RoleGrant_n12(value: _RoleGrant): RoleGrant {
    return from_candid_record_n13(value);
}
function from_candid_State_n9(value: _State): State {
    return from_candid_record_n10(value);
}
function from_candid_opt_n14(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(value: {
    seasons: Array<_Season>;
    schema: number;
    entries: Array<_TeamEntry>;
    matches: Array<_Match>;
    tokens: Array<_JoinToken>;
    governor: Principal;
    competitions: Array<_Competition>;
    roles: Array<_RoleGrant>;
}): {
    seasons: Array<Season>;
    schema: number;
    entries: Array<TeamEntry>;
    matches: Array<Match>;
    tokens: Array<JoinToken>;
    governor: Principal;
    competitions: Array<Competition>;
    roles: Array<RoleGrant>;
} {
    return {
        seasons: value.seasons,
        schema: value.schema,
        entries: value.entries,
        matches: value.matches,
        tokens: value.tokens,
        governor: value.governor,
        competitions: value.competitions,
        roles: from_candid_vec_n11(value.roles)
    };
}
function from_candid_record_n13(value: {
    role: string;
    user: Principal;
    team_id: [] | [string];
    competition_id: string;
}): {
    role: string;
    user: Principal;
    team_id?: string;
    competition_id: string;
} {
    return {
        role: value.role,
        user: value.user,
        team_id: record_opt_to_undefined(from_candid_opt_n14(value.team_id)),
        competition_id: value.competition_id
    };
}
function from_candid_variant_n17(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n19(value: {
    Ok: _JoinToken;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: JoinToken;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: _Match;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Match;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n23(value: {
    Ok: _TeamEntry;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: TeamEntry;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _Competition;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Competition;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _Season;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Season;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_State_n9(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n11(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n12(x));
}
function to_candid_opt_n15(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Competition_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Competition_domain(actor);
}
