import { defineConfig } from 'vite';
import path from 'node:path';
import fs from 'node:fs';
import { requireOwnedNetwork } from './scripts/local-lifecycle.mjs';

const allowed = new Set(JSON.parse(fs.readFileSync(new URL('./lab-runtime-files.json', import.meta.url), 'utf8')));
const csp = "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; frame-src 'none'; object-src 'none'; worker-src 'none'; base-uri 'none'; form-action 'none'; manifest-src 'none'; media-src 'self' blob:";
export default defineConfig({
  // Never load production .env files or expose inherited VITE_* variables.
  envDir: false, envPrefix: 'IGNITE_LAB_UNUSED_', publicDir: 'public',
  esbuild: { jsx: 'automatic' }, cacheDir: '.lab-cache',
  plugins: [
    { name: 'local-canister-public-config',
      configureServer(server) {
        server.middlewares.use('/icp/api', (_req, res, next) => {
          try { requireOwnedNetwork(path.resolve(import.meta.dirname, '..')); next(); }
          catch { res.statusCode = 503; res.end('Local lab network unavailable'); }
        });
        server.middlewares.use('/icp/api/v2/lab-config', (req, res) => {
          res.setHeader('Cache-Control', 'no-store');
          res.setHeader('Content-Type', 'application/json');
          if (req.method !== 'GET') { res.statusCode = 405; res.end('{}'); return; }
          try {
            // Generated by the local CLI wrapper: ID and public root key only.
            const config = JSON.parse(fs.readFileSync(new URL('../.local-icp/public.json', import.meta.url), 'utf8'));
            if (config.network !== 'local' || !/^[0-9a-f]{266}$/i.test(config.rootKey)) throw new Error('Invalid local config');
            if (typeof config.identityAccessCanisterId !== 'string' || config.identityAccessCanisterId.length === 0) {
              throw new Error('Identity access canister is unavailable');
            }
            res.end(JSON.stringify({
              network: 'local',
              canisterId: config.canisterId,
              identityAccessCanisterId: config.identityAccessCanisterId,
              canisterIds: config.canisterIds ?? {},
              rootKey: config.rootKey,
            }));
          } catch { res.statusCode = 503; res.end('{"error":"Local canister configuration unavailable"}'); }
        });
      },
    },
    { name: 'isolated-runtime-allowlist', enforce: 'pre',
      load(id) {
        return null;
      },
    },
  ],
  resolve: { alias: { '@': path.resolve(process.cwd(), 'src') } },
  server: {
    host: '127.0.0.1', port: 5180, strictPort: true,
    headers: { 'Content-Security-Policy': csp },
    // Fixed loopback target. No environment-selected or production proxy target.
    proxy: { '/icp/api/': { target: 'http://127.0.0.1:4943', rewrite: p => p.replace(/^\/icp/, '') } },
    fs: { strict: true, allow: [process.cwd()] },
  },
  preview: { host: '127.0.0.1', port: 5180, strictPort: true, headers: { 'Content-Security-Policy': csp } },
  build: { target: ['es2020', 'safari15'], sourcemap: false },
});
