/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Account = IDL.Record({
    'id' : IDL.Text,
    'legacy_subject' : IDL.Principal,
    'version' : IDL.Nat64,
    'principals' : IDL.Vec(IDL.Principal),
  });
  const Result = IDL.Variant({ 'Ok' : Account, 'Err' : IDL.Text });
  const Challenge = IDL.Record({
    'id' : IDL.Nat64,
    'account_id' : IDL.Text,
    'issuer' : IDL.Principal,
    'target' : IDL.Principal,
    'accepted' : IDL.Bool,
    'expires_at_ns' : IDL.Nat64,
    'expected_version' : IDL.Nat64,
  });
  const Result_1 = IDL.Variant({ 'Ok' : Challenge, 'Err' : IDL.Text });
  const Team = IDL.Record({ 'id' : IDL.Text, 'club' : IDL.Text });
  const Guardian = IDL.Record({ 'child' : IDL.Text, 'user' : IDL.Principal });
  const Child = IDL.Record({
    'id' : IDL.Text,
    'teams' : IDL.Vec(IDL.Text),
    'parent' : IDL.Opt(IDL.Principal),
  });
  const Exclusion = IDL.Record({ 'club' : IDL.Text, 'user' : IDL.Principal });
  const RoleGrant = IDL.Record({
    'club' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
  });
  const Acl = IDL.Record({
    'teams' : IDL.Vec(Team),
    'guardians' : IDL.Vec(Guardian),
    'clubs' : IDL.Vec(IDL.Text),
    'children' : IDL.Vec(Child),
    'exclusions' : IDL.Vec(Exclusion),
    'roles' : IDL.Vec(RoleGrant),
  });
  const Config = IDL.Record({
    'acl' : Acl,
    'schema' : IDL.Nat32,
    'governor' : IDL.Principal,
    'acl_version' : IDL.Nat64,
  });
  const Result_2 = IDL.Variant({ 'Ok' : Config, 'Err' : IDL.Text });
  const Draft = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'is_active' : IDL.Bool,
    'open_mode' : IDL.Text,
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const Link = IDL.Record({
    'id' : IDL.Text,
    'sort_order' : IDL.Nat32,
    'created_at_ms' : IDL.Nat64,
    'draft' : Draft,
    'club_id' : IDL.Text,
  });
  const Listing = IDL.Record({
    'links' : IDL.Vec(Link),
    'revision' : IDL.Nat64,
  });
  const Result_3 = IDL.Variant({ 'Ok' : Listing, 'Err' : IDL.Text });
  const AccountExclusion = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Text,
  });
  const Family = IDL.Record({ 'account_id' : IDL.Text, 'child_id' : IDL.Text });
  const AccountRole = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
  });
  const State = IDL.Record({
    'schema' : IDL.Nat32,
    'accounts' : IDL.Vec(Account),
    'exclusions' : IDL.Vec(AccountExclusion),
    'families' : IDL.Vec(Family),
    'challenges' : IDL.Vec(Challenge),
    'roles' : IDL.Vec(AccountRole),
    'next_challenge' : IDL.Nat64,
  });
  const Result_4 = IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text });
  const Snapshot = IDL.Record({
    'schema' : IDL.Nat32,
    'clubs' : IDL.Vec(IDL.Tuple(IDL.Text, Listing)),
  });
  const Result_5 = IDL.Variant({ 'Ok' : Snapshot, 'Err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const ClubProfile = IDL.Record({
    'id' : IDL.Text,
    'secondary_color' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'created_at_ms' : IDL.Nat64,
    'logo_url' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Bool,
    'primary_color' : IDL.Opt(IDL.Text),
  });
  const Result_7 = IDL.Variant({
    'Ok' : IDL.Opt(ClubProfile),
    'Err' : IDL.Text,
  });
  const ClubSettings = IDL.Record({
    'contact_email' : IDL.Opt(IDL.Text),
    'membership_open' : IDL.Bool,
    'announcement' : IDL.Opt(IDL.Text),
    'public_directory' : IDL.Bool,
    'club_id' : IDL.Text,
  });
  const Result_8 = IDL.Variant({
    'Ok' : IDL.Opt(ClubSettings),
    'Err' : IDL.Text,
  });
  const ClubSponsor = IDL.Record({
    'id' : IDL.Text,
    'website_url' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'sort_order' : IDL.Nat32,
    'logo_url' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Bool,
    'club_id' : IDL.Text,
  });
  const Result_9 = IDL.Variant({
    'Ok' : IDL.Opt(ClubSponsor),
    'Err' : IDL.Text,
  });
  const ClubTeam = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'division' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Bool,
    'club_id' : IDL.Text,
    'age_group' : IDL.Opt(IDL.Text),
  });
  const Result_10 = IDL.Variant({ 'Ok' : IDL.Opt(ClubTeam), 'Err' : IDL.Text });
  const Result_11 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Result_12 = IDL.Variant({
    'Ok' : IDL.Vec(ClubProfile),
    'Err' : IDL.Text,
  });
  const Result_13 = IDL.Variant({
    'Ok' : IDL.Vec(ClubSponsor),
    'Err' : IDL.Text,
  });
  const Result_14 = IDL.Variant({ 'Ok' : IDL.Vec(ClubTeam), 'Err' : IDL.Text });
  const Operation = IDL.Variant({
    'SetActive' : IDL.Record({ 'id' : IDL.Text, 'active' : IDL.Bool }),
    'Save' : IDL.Record({ 'id' : IDL.Opt(IDL.Text), 'draft' : Draft }),
    'Remove' : IDL.Record({ 'id' : IDL.Text }),
    'Reorder' : IDL.Record({ 'first' : IDL.Text, 'second' : IDL.Text }),
  });
  const Request = IDL.Record({
    'request_id' : IDL.Text,
    'club' : IDL.Text,
    'operation' : Operation,
    'expected_revision' : IDL.Nat64,
  });
  const Mutation = IDL.Record({
    'link' : IDL.Opt(Link),
    'revision' : IDL.Nat64,
  });
  const Result_15 = IDL.Variant({ 'Ok' : Mutation, 'Err' : IDL.Text });
  const Result_16 = IDL.Variant({ 'Ok' : ClubProfile, 'Err' : IDL.Text });
  const Result_17 = IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text });
  const Result_18 = IDL.Variant({ 'Ok' : ClubSponsor, 'Err' : IDL.Text });
  const Result_19 = IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text });
  
  return IDL.Service({
    'accept_identity_link' : IDL.Func([IDL.Nat64], [Result], []),
    'begin_identity_link' : IDL.Func([IDL.Principal], [Result_1], []),
    'export_acl' : IDL.Func([], [Result_2], ['query']),
    'export_frozen_club' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'export_identity_state' : IDL.Func([], [Result_4], ['query']),
    'export_links' : IDL.Func([], [Result_5], ['query']),
    'freeze_club' : IDL.Func([IDL.Text, IDL.Nat64], [Result_6], []),
    'get_club_profile' : IDL.Func([IDL.Text], [Result_7], ['query']),
    'get_club_settings' : IDL.Func([IDL.Text], [Result_8], ['query']),
    'get_link' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'get_sponsor' : IDL.Func([IDL.Text], [Result_9], ['query']),
    'get_team' : IDL.Func([IDL.Text], [Result_10], ['query']),
    'import_frozen_club' : IDL.Func([IDL.Text, Listing], [Result_11], []),
    'import_links' : IDL.Func([Snapshot], [Result_11], []),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_clubs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat16],
        [Result_12],
        ['query'],
      ),
    'list_links' : IDL.Func([IDL.Text, IDL.Bool], [Result_3], ['query']),
    'list_sponsors' : IDL.Func([IDL.Text], [Result_13], ['query']),
    'list_teams' : IDL.Func([IDL.Text], [Result_14], ['query']),
    'mutate' : IDL.Func([Request], [Result_15], []),
    'replace_acl' : IDL.Func([IDL.Nat64, Acl], [Result_6], []),
    'revoke_identity' : IDL.Func([IDL.Principal, IDL.Nat64], [Result], []),
    'save_club_profile' : IDL.Func([ClubProfile], [Result_16], []),
    'save_club_settings' : IDL.Func([ClubSettings], [Result_17], []),
    'save_sponsor' : IDL.Func([ClubSponsor], [Result_18], []),
    'save_team' : IDL.Func([ClubTeam], [Result_19], []),
    'unfreeze_club' : IDL.Func([IDL.Text, IDL.Nat64], [Result_11], []),
    'whoami' : IDL.Func([], [Result], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };