/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const LineupEntry = IDL.Record({
    'member' : IDL.Text,
    'slot' : IDL.Text,
    'team_id' : IDL.Opt(IDL.Text),
    'event_id' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'starts_at_ms' : IDL.Nat64,
    'ends_at_ms' : IDL.Nat64,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const Recurrence = IDL.Record({
    'until_ms' : IDL.Nat64,
    'frequency' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'account_id' : IDL.Text,
    'present' : IDL.Bool,
    'note' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const Duty = IDL.Record({
    'account_id' : IDL.Text,
    'duty' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const RosterEntry = IDL.Record({
    'account_id' : IDL.Text,
    'child_id' : IDL.Opt(IDL.Text),
    'event_id' : IDL.Text,
  });
  const RoleGrant = IDL.Record({
    'role' : IDL.Text,
    'user' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'club_id' : IDL.Text,
  });
  const Rsvp = IDL.Record({
    'account_id' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'state' : IDL.Text,
    'event_id' : IDL.Text,
  });
  
  return IDL.Service({
    'add_lineup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : LineupEntry, 'Err' : IDL.Text })],
        [],
      ),
    'create_event' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
        [IDL.Variant({ 'Ok' : Event, 'Err' : IDL.Text })],
        [],
      ),
    'export_state' : IDL.Func(
        [],
        [
          IDL.Variant({
            'Ok' : IDL.Record({
              'lineups' : IDL.Vec(LineupEntry),
              'schema' : IDL.Nat32,
              'recurrences' : IDL.Vec(Recurrence),
              'attendance' : IDL.Vec(Attendance),
              'events' : IDL.Vec(Event),
              'duties' : IDL.Vec(Duty),
              'governor' : IDL.Principal,
              'roster' : IDL.Vec(RosterEntry),
              'roles' : IDL.Vec(RoleGrant),
              'rsvps' : IDL.Vec(Rsvp),
            }),
            'Err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'grant_role' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_events' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'set_attendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Variant({ 'Ok' : Attendance, 'Err' : IDL.Text })],
        [],
      ),
    'set_duty' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : Duty, 'Err' : IDL.Text })],
        [],
      ),
    'set_recurrence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [IDL.Variant({ 'Ok' : Recurrence, 'Err' : IDL.Text })],
        [],
      ),
    'set_roster' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : RosterEntry, 'Err' : IDL.Text })],
        [],
      ),
    'set_rsvp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : Rsvp, 'Err' : IDL.Text })],
        [],
      ),
    'update_event' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
        [IDL.Variant({ 'Ok' : Event, 'Err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };