/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  const LineupEntry = IDL.Record({
    'member' : IDL.Text,
    'slot' : IDL.Text,
    'team_id' : IDL.Opt(IDL.Text),
    'event_id' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'Ok' : LineupEntry, 'Err' : IDL.Text });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'starts_at_ms' : IDL.Nat64,
    'ends_at_ms' : IDL.Nat64,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const Result = IDL.Variant({ 'Ok' : Event, 'Err' : IDL.Text });
  const Recurrence = IDL.Record({
    'until_ms' : IDL.Nat64,
    'frequency' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'account_id' : IDL.Text,
    'present' : IDL.Bool,
    'note' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const Duty = IDL.Record({
    'account_id' : IDL.Text,
    'duty' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const RosterEntry = IDL.Record({
    'account_id' : IDL.Text,
    'child_id' : IDL.Opt(IDL.Text),
    'event_id' : IDL.Text,
  });
  const RoleGrant = IDL.Record({
    'role' : IDL.Text,
    'user' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'club_id' : IDL.Text,
  });
  const Rsvp = IDL.Record({
    'account_id' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'state' : IDL.Text,
    'event_id' : IDL.Text,
  });
  const State = IDL.Record({
    'lineups' : IDL.Vec(LineupEntry),
    'schema' : IDL.Nat32,
    'recurrences' : IDL.Vec(Recurrence),
    'attendance' : IDL.Vec(Attendance),
    'events' : IDL.Vec(Event),
    'duties' : IDL.Vec(Duty),
    'governor' : IDL.Principal,
    'roster' : IDL.Vec(RosterEntry),
    'roles' : IDL.Vec(RoleGrant),
    'rsvps' : IDL.Vec(Rsvp),
  });
  const Result_3 = IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'Ok' : Attendance, 'Err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'Ok' : Duty, 'Err' : IDL.Text });
  const Result_7 = IDL.Variant({ 'Ok' : Recurrence, 'Err' : IDL.Text });
  const Result_8 = IDL.Variant({ 'Ok' : RosterEntry, 'Err' : IDL.Text });
  const Result_5 = IDL.Variant({ 'Ok' : Rsvp, 'Err' : IDL.Text });
  
  return IDL.Service({
    'add_lineup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_2],
        [],
      ),
    'create_event' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
        [Result],
        [],
      ),
    'export_state' : IDL.Func([], [Result_3], ['query']),
    'grant_role' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'list_events' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'set_attendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [Result_1],
        [],
      ),
    'set_duty' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_6], []),
    'set_recurrence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [Result_7],
        [],
      ),
    'set_roster' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_8],
        [],
      ),
    'set_rsvp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_5], []),
    'update_event' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [Init];
};