/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'account_id' : string,
  'present' : boolean,
  'note' : string,
  'event_id' : string,
}
export interface Duty {
  'account_id' : string,
  'duty' : string,
  'event_id' : string,
}
export interface Event {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'team_id' : [] | [string],
  'description' : string,
  'starts_at_ms' : bigint,
  'ends_at_ms' : bigint,
  'revision' : bigint,
  'club_id' : string,
}
export interface Init { 'governor' : Principal }
export interface LineupEntry {
  'member' : string,
  'slot' : string,
  'team_id' : [] | [string],
  'event_id' : string,
}
export interface Recurrence {
  'until_ms' : bigint,
  'frequency' : string,
  'event_id' : string,
}
export type Result = { 'Ok' : Event } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Attendance } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : LineupEntry } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : State } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Rsvp } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Duty } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : Recurrence } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : RosterEntry } |
  { 'Err' : string };
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : string,
}
export interface RosterEntry {
  'account_id' : string,
  'child_id' : [] | [string],
  'event_id' : string,
}
export interface Rsvp {
  'account_id' : string,
  'updated_at_ms' : bigint,
  'state' : string,
  'event_id' : string,
}
export interface State {
  'lineups' : Array<LineupEntry>,
  'schema' : number,
  'recurrences' : Array<Recurrence>,
  'attendance' : Array<Attendance>,
  'events' : Array<Event>,
  'duties' : Array<Duty>,
  'governor' : Principal,
  'roster' : Array<RosterEntry>,
  'roles' : Array<RoleGrant>,
  'rsvps' : Array<Rsvp>,
}
export interface _SERVICE {
  'add_lineup' : ActorMethod<[string, string, string, [] | [string]], Result_2>,
  'create_event' : ActorMethod<
    [string, [] | [string], string, string, bigint, bigint],
    Result
  >,
  'export_state' : ActorMethod<[], Result_3>,
  'grant_role' : ActorMethod<
    [Principal, string, string, [] | [string]],
    Result_4
  >,
  'list_events' : ActorMethod<[[] | [string], [] | [string]], Array<Event>>,
  'set_attendance' : ActorMethod<[string, string, boolean, string], Result_1>,
  'set_duty' : ActorMethod<[string, string, string], Result_6>,
  'set_recurrence' : ActorMethod<[string, string, bigint], Result_7>,
  'set_roster' : ActorMethod<[string, string, [] | [string]], Result_8>,
  'set_rsvp' : ActorMethod<[string, string, string], Result_5>,
  'update_event' : ActorMethod<
    [string, string, string, bigint, bigint],
    Result
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];