/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const queue_state = IDL.Record({
    'armed' : IDL.Bool,
    'next_run_at_ms' : IDL.Opt(IDL.Nat64),
  });
  const result_state = IDL.Variant({ 'Ok' : queue_state, 'Err' : IDL.Text });
  const status = IDL.Variant({
    'Failed' : IDL.Null,
    'Processing' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const job = IDL.Record({
    'id' : IDL.Text,
    'last_error' : IDL.Opt(IDL.Text),
    'status' : status,
    'run_at_ms' : IDL.Nat64,
    'attempts' : IDL.Nat32,
    'scope' : IDL.Text,
    'callback' : IDL.Opt(IDL.Principal),
    'lease_until_ms' : IDL.Opt(IDL.Nat64),
    'idempotency_key' : IDL.Text,
  });
  const result_jobs = IDL.Variant({ 'Ok' : IDL.Vec(job), 'Err' : IDL.Text });
  const result_job = IDL.Variant({ 'Ok' : job, 'Err' : IDL.Text });
  const snapshot = IDL.Record({ 'jobs' : IDL.Vec(job), 'state' : queue_state });
  const result_snapshot = IDL.Variant({ 'Ok' : snapshot, 'Err' : IDL.Text });
  const result_unit = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const page = IDL.Record({
    'jobs' : IDL.Vec(job),
    'next' : IDL.Opt(IDL.Text),
  });
  const result_page = IDL.Variant({ 'Ok' : page, 'Err' : IDL.Text });
  const reconciliation = IDL.Record({
    'incoming_jobs' : IDL.Nat32,
    'matching_jobs' : IDL.Nat32,
    'local_jobs' : IDL.Nat32,
  });
  const result_reconciliation = IDL.Variant({
    'Ok' : reconciliation,
    'Err' : IDL.Text,
  });
  const result_nat16 = IDL.Variant({ 'Ok' : IDL.Nat16, 'Err' : IDL.Text });
  
  return IDL.Service({
    'arm' : IDL.Func([IDL.Nat64], [result_state], []),
    'claim' : IDL.Func([IDL.Nat64, IDL.Nat16], [result_jobs], []),
    'claim_with_lease' : IDL.Func(
        [IDL.Nat64, IDL.Nat16, IDL.Nat64],
        [result_jobs],
        [],
      ),
    'complete' : IDL.Func([IDL.Text, IDL.Text], [result_job], []),
    'export_state' : IDL.Func([], [result_snapshot], ['query']),
    'fail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat64)],
        [result_job],
        [],
      ),
    'get_job' : IDL.Func([IDL.Text], [IDL.Opt(job)], ['query']),
    'get_state' : IDL.Func([], [queue_state], ['query']),
    'grant_callback_scope' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [result_unit],
        [],
      ),
    'grant_worker' : IDL.Func([IDL.Principal], [result_unit], []),
    'grant_worker_scope' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [result_unit],
        [],
      ),
    'import_state' : IDL.Func([snapshot], [result_unit], []),
    'initialize' : IDL.Func([], [result_unit], []),
    'list_jobs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat16],
        [result_page],
        ['query'],
      ),
    'reconcile' : IDL.Func([snapshot], [result_reconciliation], ['query']),
    'recover_expired' : IDL.Func([IDL.Nat64], [result_nat16], []),
    'recover_interrupted' : IDL.Func([], [result_nat16], []),
    'schedule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64, IDL.Text],
        [result_job],
        [],
      ),
    'schedule_with_callback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Nat64, IDL.Text],
        [result_job],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };