/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/club_links.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface AccountExclusion {
    account_id: string;
    club: string;
}
export interface Account {
    id: string;
    legacy_subject: Principal;
    version: bigint;
    principals: Array<Principal>;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: Config;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_17 = {
    __kind__: "Ok";
    Ok: ClubSettings;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Acl {
    teams: Array<Team>;
    guardians: Array<Guardian>;
    clubs: Array<string>;
    children: Array<Child>;
    exclusions: Array<Exclusion>;
    roles: Array<RoleGrant>;
}
export type Result_13 = {
    __kind__: "Ok";
    Ok: Array<ClubSponsor>;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_5 = {
    __kind__: "Ok";
    Ok: Snapshot;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_16 = {
    __kind__: "Ok";
    Ok: ClubProfile;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Draft {
    url: string;
    title: string;
    icon: string;
    is_active: boolean;
    open_mode: string;
    subtitle?: string;
}
export interface ClubProfile {
    id: string;
    secondary_color?: string;
    name: string;
    slug: string;
    description?: string;
    created_at_ms: bigint;
    logo_url?: string;
    is_active: boolean;
    primary_color?: string;
}
export interface Challenge {
    id: bigint;
    account_id: string;
    issuer: Principal;
    target: Principal;
    accepted: boolean;
    expires_at_ns: bigint;
    expected_version: bigint;
}
export interface Request {
    request_id: string;
    club: string;
    operation: Operation;
    expected_revision: bigint;
}
export interface Child {
    id: string;
    teams: Array<string>;
    parent?: Principal;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: Challenge;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_11 = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_4 = {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Guardian {
    child: string;
    user: Principal;
}
export interface Mutation {
    link?: Link;
    revision: bigint;
}
export type Result_19 = {
    __kind__: "Ok";
    Ok: ClubTeam;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Exclusion {
    club: string;
    user: Principal;
}
export type Result_7 = {
    __kind__: "Ok";
    Ok: ClubProfile | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_14 = {
    __kind__: "Ok";
    Ok: Array<ClubTeam>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ClubSettings {
    contact_email?: string;
    membership_open: boolean;
    announcement?: string;
    public_directory: boolean;
    club_id: string;
}
export interface Link {
    id: string;
    sort_order: number;
    created_at_ms: bigint;
    draft: Draft;
    club_id: string;
}
export interface RoleGrant {
    club?: string;
    role: string;
    team?: string;
    user: Principal;
}
export interface Snapshot {
    schema: number;
    clubs: Array<[string, Listing]>;
}
export interface State {
    schema: number;
    accounts: Array<Account>;
    exclusions: Array<AccountExclusion>;
    families: Array<Family>;
    challenges: Array<Challenge>;
    roles: Array<AccountRole>;
    next_challenge: bigint;
}
export type Operation = {
    __kind__: "SetActive";
    SetActive: {
        id: string;
        active: boolean;
    };
} | {
    __kind__: "Save";
    Save: {
        id?: string;
        draft: Draft;
    };
} | {
    __kind__: "Remove";
    Remove: {
        id: string;
    };
} | {
    __kind__: "Reorder";
    Reorder: {
        first: string;
        second: string;
    };
};
export interface Team {
    id: string;
    club: string;
}
export interface ClubSponsor {
    id: string;
    website_url?: string;
    name: string;
    tier: string;
    sort_order: number;
    logo_url?: string;
    is_active: boolean;
    club_id: string;
}
export interface Family {
    account_id: string;
    child_id: string;
}
export interface Listing {
    links: Array<Link>;
    revision: bigint;
}
export type Result_6 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Config {
    acl: Acl;
    schema: number;
    governor: Principal;
    acl_version: bigint;
}
export type Result_12 = {
    __kind__: "Ok";
    Ok: Array<ClubProfile>;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_9 = {
    __kind__: "Ok";
    Ok: ClubSponsor | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_18 = {
    __kind__: "Ok";
    Ok: ClubSponsor;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result = {
    __kind__: "Ok";
    Ok: Account;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_10 = {
    __kind__: "Ok";
    Ok: ClubTeam | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface AccountRole {
    account_id: string;
    club?: string;
    role: string;
    team?: string;
}
export type Result_3 = {
    __kind__: "Ok";
    Ok: Listing;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_15 = {
    __kind__: "Ok";
    Ok: Mutation;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_8 = {
    __kind__: "Ok";
    Ok: ClubSettings | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ClubTeam {
    id: string;
    name: string;
    division?: string;
    gender?: string;
    is_active: boolean;
    club_id: string;
    age_group?: string;
}
export interface club_linksInterface {
    accept_identity_link(arg0: bigint): Promise<Result>;
    begin_identity_link(arg0: Principal): Promise<Result_1>;
    export_acl(): Promise<Result_2>;
    export_frozen_club(arg0: string): Promise<Result_3>;
    export_identity_state(): Promise<Result_4>;
    export_links(): Promise<Result_5>;
    freeze_club(arg0: string, arg1: bigint): Promise<Result_6>;
    get_club_profile(arg0: string): Promise<Result_7>;
    get_club_settings(arg0: string): Promise<Result_8>;
    get_link(arg0: string): Promise<Result_3>;
    get_sponsor(arg0: string): Promise<Result_9>;
    get_team(arg0: string): Promise<Result_10>;
    import_frozen_club(arg0: string, arg1: Listing): Promise<Result_11>;
    import_links(arg0: Snapshot): Promise<Result_11>;
    list_clubs(arg0: string | null, arg1: number): Promise<Result_12>;
    list_links(arg0: string, arg1: boolean): Promise<Result_3>;
    list_sponsors(arg0: string): Promise<Result_13>;
    list_teams(arg0: string): Promise<Result_14>;
    mutate(arg0: Request): Promise<Result_15>;
    replace_acl(arg0: bigint, arg1: Acl): Promise<Result_6>;
    revoke_identity(arg0: Principal, arg1: bigint): Promise<Result>;
    save_club_profile(arg0: ClubProfile): Promise<Result_16>;
    save_club_settings(arg0: ClubSettings): Promise<Result_17>;
    save_sponsor(arg0: ClubSponsor): Promise<Result_18>;
    save_team(arg0: ClubTeam): Promise<Result_19>;
    unfreeze_club(arg0: string, arg1: bigint): Promise<Result_11>;
    whoami(): Promise<Result>;
}
import type { Account as _Account, AccountExclusion as _AccountExclusion, AccountRole as _AccountRole, Acl as _Acl, Challenge as _Challenge, Child as _Child, ClubProfile as _ClubProfile, ClubSettings as _ClubSettings, ClubSponsor as _ClubSponsor, ClubTeam as _ClubTeam, Config as _Config, Draft as _Draft, Exclusion as _Exclusion, Family as _Family, Guardian as _Guardian, Link as _Link, Listing as _Listing, Mutation as _Mutation, Operation as _Operation, Request as _Request, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_13 as _Result_13, Result_14 as _Result_14, Result_15 as _Result_15, Result_16 as _Result_16, Result_17 as _Result_17, Result_18 as _Result_18, Result_19 as _Result_19, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, RoleGrant as _RoleGrant, Snapshot as _Snapshot, State as _State, Team as _Team } from "./declarations/club_links.did";
export class Club_links implements club_linksInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async accept_identity_link(arg0: bigint): Promise<Result> {
        const result = await this.actor.accept_identity_link(arg0);
        return from_candid_Result_n1(result);
    }
    async begin_identity_link(arg0: Principal): Promise<Result_1> {
        const result = await this.actor.begin_identity_link(arg0);
        return from_candid_Result_1_n3(result);
    }
    async export_acl(): Promise<Result_2> {
        const result = await this.actor.export_acl();
        return from_candid_Result_2_n5(result);
    }
    async export_frozen_club(arg0: string): Promise<Result_3> {
        const result = await this.actor.export_frozen_club(arg0);
        return from_candid_Result_3_n19(result);
    }
    async export_identity_state(): Promise<Result_4> {
        const result = await this.actor.export_identity_state();
        return from_candid_Result_4_n28(result);
    }
    async export_links(): Promise<Result_5> {
        const result = await this.actor.export_links();
        return from_candid_Result_5_n35(result);
    }
    async freeze_club(arg0: string, arg1: bigint): Promise<Result_6> {
        const result = await this.actor.freeze_club(arg0, arg1);
        return from_candid_Result_6_n41(result);
    }
    async get_club_profile(arg0: string): Promise<Result_7> {
        const result = await this.actor.get_club_profile(arg0);
        return from_candid_Result_7_n43(result);
    }
    async get_club_settings(arg0: string): Promise<Result_8> {
        const result = await this.actor.get_club_settings(arg0);
        return from_candid_Result_8_n48(result);
    }
    async get_link(arg0: string): Promise<Result_3> {
        const result = await this.actor.get_link(arg0);
        return from_candid_Result_3_n19(result);
    }
    async get_sponsor(arg0: string): Promise<Result_9> {
        const result = await this.actor.get_sponsor(arg0);
        return from_candid_Result_9_n53(result);
    }
    async get_team(arg0: string): Promise<Result_10> {
        const result = await this.actor.get_team(arg0);
        return from_candid_Result_10_n58(result);
    }
    async import_frozen_club(arg0: string, arg1: Listing): Promise<Result_11> {
        const result = await this.actor.import_frozen_club(arg0, to_candid_Listing_n63(arg1));
        return from_candid_Result_11_n70(result);
    }
    async import_links(arg0: Snapshot): Promise<Result_11> {
        const result = await this.actor.import_links(to_candid_Snapshot_n72(arg0));
        return from_candid_Result_11_n70(result);
    }
    async list_clubs(arg0: string | null, arg1: number): Promise<Result_12> {
        const result = await this.actor.list_clubs(to_candid_opt_n76(arg0), arg1);
        return from_candid_Result_12_n77(result);
    }
    async list_links(arg0: string, arg1: boolean): Promise<Result_3> {
        const result = await this.actor.list_links(arg0, arg1);
        return from_candid_Result_3_n19(result);
    }
    async list_sponsors(arg0: string): Promise<Result_13> {
        const result = await this.actor.list_sponsors(arg0);
        return from_candid_Result_13_n80(result);
    }
    async list_teams(arg0: string): Promise<Result_14> {
        const result = await this.actor.list_teams(arg0);
        return from_candid_Result_14_n83(result);
    }
    async mutate(arg0: Request): Promise<Result_15> {
        const result = await this.actor.mutate(to_candid_Request_n86(arg0));
        return from_candid_Result_15_n91(result);
    }
    async replace_acl(arg0: bigint, arg1: Acl): Promise<Result_6> {
        const result = await this.actor.replace_acl(arg0, to_candid_Acl_n96(arg1));
        return from_candid_Result_6_n41(result);
    }
    async revoke_identity(arg0: Principal, arg1: bigint): Promise<Result> {
        const result = await this.actor.revoke_identity(arg0, arg1);
        return from_candid_Result_n1(result);
    }
    async save_club_profile(arg0: ClubProfile): Promise<Result_16> {
        const result = await this.actor.save_club_profile(to_candid_ClubProfile_n104(arg0));
        return from_candid_Result_16_n106(result);
    }
    async save_club_settings(arg0: ClubSettings): Promise<Result_17> {
        const result = await this.actor.save_club_settings(to_candid_ClubSettings_n108(arg0));
        return from_candid_Result_17_n110(result);
    }
    async save_sponsor(arg0: ClubSponsor): Promise<Result_18> {
        const result = await this.actor.save_sponsor(to_candid_ClubSponsor_n112(arg0));
        return from_candid_Result_18_n114(result);
    }
    async save_team(arg0: ClubTeam): Promise<Result_19> {
        const result = await this.actor.save_team(to_candid_ClubTeam_n116(arg0));
        return from_candid_Result_19_n118(result);
    }
    async unfreeze_club(arg0: string, arg1: bigint): Promise<Result_11> {
        const result = await this.actor.unfreeze_club(arg0, arg1);
        return from_candid_Result_11_n70(result);
    }
    async whoami(): Promise<Result> {
        const result = await this.actor.whoami();
        return from_candid_Result_n1(result);
    }
}
function from_candid_AccountRole_n33(value: _AccountRole): AccountRole {
    return from_candid_record_n34(value);
}
function from_candid_Acl_n9(value: _Acl): Acl {
    return from_candid_record_n10(value);
}
function from_candid_Child_n12(value: _Child): Child {
    return from_candid_record_n13(value);
}
function from_candid_ClubProfile_n46(value: _ClubProfile): ClubProfile {
    return from_candid_record_n47(value);
}
function from_candid_ClubSettings_n51(value: _ClubSettings): ClubSettings {
    return from_candid_record_n52(value);
}
function from_candid_ClubSponsor_n56(value: _ClubSponsor): ClubSponsor {
    return from_candid_record_n57(value);
}
function from_candid_ClubTeam_n61(value: _ClubTeam): ClubTeam {
    return from_candid_record_n62(value);
}
function from_candid_Config_n7(value: _Config): Config {
    return from_candid_record_n8(value);
}
function from_candid_Draft_n26(value: _Draft): Draft {
    return from_candid_record_n27(value);
}
function from_candid_Link_n24(value: _Link): Link {
    return from_candid_record_n25(value);
}
function from_candid_Listing_n21(value: _Listing): Listing {
    return from_candid_record_n22(value);
}
function from_candid_Mutation_n93(value: _Mutation): Mutation {
    return from_candid_record_n94(value);
}
function from_candid_Result_10_n58(value: _Result_10): Result_10 {
    return from_candid_variant_n59(value);
}
function from_candid_Result_11_n70(value: _Result_11): Result_11 {
    return from_candid_variant_n71(value);
}
function from_candid_Result_12_n77(value: _Result_12): Result_12 {
    return from_candid_variant_n78(value);
}
function from_candid_Result_13_n80(value: _Result_13): Result_13 {
    return from_candid_variant_n81(value);
}
function from_candid_Result_14_n83(value: _Result_14): Result_14 {
    return from_candid_variant_n84(value);
}
function from_candid_Result_15_n91(value: _Result_15): Result_15 {
    return from_candid_variant_n92(value);
}
function from_candid_Result_16_n106(value: _Result_16): Result_16 {
    return from_candid_variant_n107(value);
}
function from_candid_Result_17_n110(value: _Result_17): Result_17 {
    return from_candid_variant_n111(value);
}
function from_candid_Result_18_n114(value: _Result_18): Result_18 {
    return from_candid_variant_n115(value);
}
function from_candid_Result_19_n118(value: _Result_19): Result_19 {
    return from_candid_variant_n119(value);
}
function from_candid_Result_1_n3(value: _Result_1): Result_1 {
    return from_candid_variant_n4(value);
}
function from_candid_Result_2_n5(value: _Result_2): Result_2 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_3_n19(value: _Result_3): Result_3 {
    return from_candid_variant_n20(value);
}
function from_candid_Result_4_n28(value: _Result_4): Result_4 {
    return from_candid_variant_n29(value);
}
function from_candid_Result_5_n35(value: _Result_5): Result_5 {
    return from_candid_variant_n36(value);
}
function from_candid_Result_6_n41(value: _Result_6): Result_6 {
    return from_candid_variant_n42(value);
}
function from_candid_Result_7_n43(value: _Result_7): Result_7 {
    return from_candid_variant_n44(value);
}
function from_candid_Result_8_n48(value: _Result_8): Result_8 {
    return from_candid_variant_n49(value);
}
function from_candid_Result_9_n53(value: _Result_9): Result_9 {
    return from_candid_variant_n54(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_RoleGrant_n16(value: _RoleGrant): RoleGrant {
    return from_candid_record_n17(value);
}
function from_candid_Snapshot_n37(value: _Snapshot): Snapshot {
    return from_candid_record_n38(value);
}
function from_candid_State_n30(value: _State): State {
    return from_candid_record_n31(value);
}
function from_candid_opt_n14(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(value: [] | [_ClubProfile]): ClubProfile | null {
    return value.length === 0 ? null : from_candid_ClubProfile_n46(value[0]);
}
function from_candid_opt_n50(value: [] | [_ClubSettings]): ClubSettings | null {
    return value.length === 0 ? null : from_candid_ClubSettings_n51(value[0]);
}
function from_candid_opt_n55(value: [] | [_ClubSponsor]): ClubSponsor | null {
    return value.length === 0 ? null : from_candid_ClubSponsor_n56(value[0]);
}
function from_candid_opt_n60(value: [] | [_ClubTeam]): ClubTeam | null {
    return value.length === 0 ? null : from_candid_ClubTeam_n61(value[0]);
}
function from_candid_opt_n95(value: [] | [_Link]): Link | null {
    return value.length === 0 ? null : from_candid_Link_n24(value[0]);
}
function from_candid_record_n10(value: {
    teams: Array<_Team>;
    guardians: Array<_Guardian>;
    clubs: Array<string>;
    children: Array<_Child>;
    exclusions: Array<_Exclusion>;
    roles: Array<_RoleGrant>;
}): {
    teams: Array<Team>;
    guardians: Array<Guardian>;
    clubs: Array<string>;
    children: Array<Child>;
    exclusions: Array<Exclusion>;
    roles: Array<RoleGrant>;
} {
    return {
        teams: value.teams,
        guardians: value.guardians,
        clubs: value.clubs,
        children: from_candid_vec_n11(value.children),
        exclusions: value.exclusions,
        roles: from_candid_vec_n15(value.roles)
    };
}
function from_candid_record_n13(value: {
    id: string;
    teams: Array<string>;
    parent: [] | [Principal];
}): {
    id: string;
    teams: Array<string>;
    parent?: Principal;
} {
    return {
        id: value.id,
        teams: value.teams,
        parent: record_opt_to_undefined(from_candid_opt_n14(value.parent))
    };
}
function from_candid_record_n17(value: {
    club: [] | [string];
    role: string;
    team: [] | [string];
    user: Principal;
}): {
    club?: string;
    role: string;
    team?: string;
    user: Principal;
} {
    return {
        club: record_opt_to_undefined(from_candid_opt_n18(value.club)),
        role: value.role,
        team: record_opt_to_undefined(from_candid_opt_n18(value.team)),
        user: value.user
    };
}
function from_candid_record_n22(value: {
    links: Array<_Link>;
    revision: bigint;
}): {
    links: Array<Link>;
    revision: bigint;
} {
    return {
        links: from_candid_vec_n23(value.links),
        revision: value.revision
    };
}
function from_candid_record_n25(value: {
    id: string;
    sort_order: number;
    created_at_ms: bigint;
    draft: _Draft;
    club_id: string;
}): {
    id: string;
    sort_order: number;
    created_at_ms: bigint;
    draft: Draft;
    club_id: string;
} {
    return {
        id: value.id,
        sort_order: value.sort_order,
        created_at_ms: value.created_at_ms,
        draft: from_candid_Draft_n26(value.draft),
        club_id: value.club_id
    };
}
function from_candid_record_n27(value: {
    url: string;
    title: string;
    icon: string;
    is_active: boolean;
    open_mode: string;
    subtitle: [] | [string];
}): {
    url: string;
    title: string;
    icon: string;
    is_active: boolean;
    open_mode: string;
    subtitle?: string;
} {
    return {
        url: value.url,
        title: value.title,
        icon: value.icon,
        is_active: value.is_active,
        open_mode: value.open_mode,
        subtitle: record_opt_to_undefined(from_candid_opt_n18(value.subtitle))
    };
}
function from_candid_record_n31(value: {
    schema: number;
    accounts: Array<_Account>;
    exclusions: Array<_AccountExclusion>;
    families: Array<_Family>;
    challenges: Array<_Challenge>;
    roles: Array<_AccountRole>;
    next_challenge: bigint;
}): {
    schema: number;
    accounts: Array<Account>;
    exclusions: Array<AccountExclusion>;
    families: Array<Family>;
    challenges: Array<Challenge>;
    roles: Array<AccountRole>;
    next_challenge: bigint;
} {
    return {
        schema: value.schema,
        accounts: value.accounts,
        exclusions: value.exclusions,
        families: value.families,
        challenges: value.challenges,
        roles: from_candid_vec_n32(value.roles),
        next_challenge: value.next_challenge
    };
}
function from_candid_record_n34(value: {
    account_id: string;
    club: [] | [string];
    role: string;
    team: [] | [string];
}): {
    account_id: string;
    club?: string;
    role: string;
    team?: string;
} {
    return {
        account_id: value.account_id,
        club: record_opt_to_undefined(from_candid_opt_n18(value.club)),
        role: value.role,
        team: record_opt_to_undefined(from_candid_opt_n18(value.team))
    };
}
function from_candid_record_n38(value: {
    schema: number;
    clubs: Array<[string, _Listing]>;
}): {
    schema: number;
    clubs: Array<[string, Listing]>;
} {
    return {
        schema: value.schema,
        clubs: from_candid_vec_n39(value.clubs)
    };
}
function from_candid_record_n47(value: {
    id: string;
    secondary_color: [] | [string];
    name: string;
    slug: string;
    description: [] | [string];
    created_at_ms: bigint;
    logo_url: [] | [string];
    is_active: boolean;
    primary_color: [] | [string];
}): {
    id: string;
    secondary_color?: string;
    name: string;
    slug: string;
    description?: string;
    created_at_ms: bigint;
    logo_url?: string;
    is_active: boolean;
    primary_color?: string;
} {
    return {
        id: value.id,
        secondary_color: record_opt_to_undefined(from_candid_opt_n18(value.secondary_color)),
        name: value.name,
        slug: value.slug,
        description: record_opt_to_undefined(from_candid_opt_n18(value.description)),
        created_at_ms: value.created_at_ms,
        logo_url: record_opt_to_undefined(from_candid_opt_n18(value.logo_url)),
        is_active: value.is_active,
        primary_color: record_opt_to_undefined(from_candid_opt_n18(value.primary_color))
    };
}
function from_candid_record_n52(value: {
    contact_email: [] | [string];
    membership_open: boolean;
    announcement: [] | [string];
    public_directory: boolean;
    club_id: string;
}): {
    contact_email?: string;
    membership_open: boolean;
    announcement?: string;
    public_directory: boolean;
    club_id: string;
} {
    return {
        contact_email: record_opt_to_undefined(from_candid_opt_n18(value.contact_email)),
        membership_open: value.membership_open,
        announcement: record_opt_to_undefined(from_candid_opt_n18(value.announcement)),
        public_directory: value.public_directory,
        club_id: value.club_id
    };
}
function from_candid_record_n57(value: {
    id: string;
    website_url: [] | [string];
    name: string;
    tier: string;
    sort_order: number;
    logo_url: [] | [string];
    is_active: boolean;
    club_id: string;
}): {
    id: string;
    website_url?: string;
    name: string;
    tier: string;
    sort_order: number;
    logo_url?: string;
    is_active: boolean;
    club_id: string;
} {
    return {
        id: value.id,
        website_url: record_opt_to_undefined(from_candid_opt_n18(value.website_url)),
        name: value.name,
        tier: value.tier,
        sort_order: value.sort_order,
        logo_url: record_opt_to_undefined(from_candid_opt_n18(value.logo_url)),
        is_active: value.is_active,
        club_id: value.club_id
    };
}
function from_candid_record_n62(value: {
    id: string;
    name: string;
    division: [] | [string];
    gender: [] | [string];
    is_active: boolean;
    club_id: string;
    age_group: [] | [string];
}): {
    id: string;
    name: string;
    division?: string;
    gender?: string;
    is_active: boolean;
    club_id: string;
    age_group?: string;
} {
    return {
        id: value.id,
        name: value.name,
        division: record_opt_to_undefined(from_candid_opt_n18(value.division)),
        gender: record_opt_to_undefined(from_candid_opt_n18(value.gender)),
        is_active: value.is_active,
        club_id: value.club_id,
        age_group: record_opt_to_undefined(from_candid_opt_n18(value.age_group))
    };
}
function from_candid_record_n8(value: {
    acl: _Acl;
    schema: number;
    governor: Principal;
    acl_version: bigint;
}): {
    acl: Acl;
    schema: number;
    governor: Principal;
    acl_version: bigint;
} {
    return {
        acl: from_candid_Acl_n9(value.acl),
        schema: value.schema,
        governor: value.governor,
        acl_version: value.acl_version
    };
}
function from_candid_record_n94(value: {
    link: [] | [_Link];
    revision: bigint;
}): {
    link?: Link;
    revision: bigint;
} {
    return {
        link: record_opt_to_undefined(from_candid_opt_n95(value.link)),
        revision: value.revision
    };
}
function from_candid_tuple_n40(value: [string, _Listing]): [string, Listing] {
    return [
        value[0],
        from_candid_Listing_n21(value[1])
    ];
}
function from_candid_variant_n107(value: {
    Ok: _ClubProfile;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubProfile;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ClubProfile_n46(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n111(value: {
    Ok: _ClubSettings;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubSettings;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ClubSettings_n51(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n115(value: {
    Ok: _ClubSponsor;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubSponsor;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ClubSponsor_n56(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n119(value: {
    Ok: _ClubTeam;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubTeam;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ClubTeam_n61(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _Account;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Account;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: _Listing;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Listing;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Listing_n21(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n29(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_State_n30(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n36(value: {
    Ok: _Snapshot;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Snapshot;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Snapshot_n37(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _Challenge;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Challenge;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n42(value: {
    Ok: bigint;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n44(value: {
    Ok: [] | [_ClubProfile];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubProfile | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n45(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n49(value: {
    Ok: [] | [_ClubSettings];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubSettings | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n50(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n54(value: {
    Ok: [] | [_ClubSponsor];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubSponsor | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n55(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n59(value: {
    Ok: [] | [_ClubTeam];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClubTeam | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n60(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _Config;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Config;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Config_n7(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n71(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n78(value: {
    Ok: Array<_ClubProfile>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ClubProfile>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n79(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n81(value: {
    Ok: Array<_ClubSponsor>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ClubSponsor>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n82(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n84(value: {
    Ok: Array<_ClubTeam>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ClubTeam>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n85(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n92(value: {
    Ok: _Mutation;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Mutation;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Mutation_n93(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n11(value: Array<_Child>): Array<Child> {
    return value.map((x)=>from_candid_Child_n12(x));
}
function from_candid_vec_n15(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n16(x));
}
function from_candid_vec_n23(value: Array<_Link>): Array<Link> {
    return value.map((x)=>from_candid_Link_n24(x));
}
function from_candid_vec_n32(value: Array<_AccountRole>): Array<AccountRole> {
    return value.map((x)=>from_candid_AccountRole_n33(x));
}
function from_candid_vec_n39(value: Array<[string, _Listing]>): Array<[string, Listing]> {
    return value.map((x)=>from_candid_tuple_n40(x));
}
function from_candid_vec_n79(value: Array<_ClubProfile>): Array<ClubProfile> {
    return value.map((x)=>from_candid_ClubProfile_n46(x));
}
function from_candid_vec_n82(value: Array<_ClubSponsor>): Array<ClubSponsor> {
    return value.map((x)=>from_candid_ClubSponsor_n56(x));
}
function from_candid_vec_n85(value: Array<_ClubTeam>): Array<ClubTeam> {
    return value.map((x)=>from_candid_ClubTeam_n61(x));
}
function to_candid_Acl_n96(value: Acl): _Acl {
    return to_candid_record_n97(value);
}
function to_candid_Child_n99(value: Child): _Child {
    return to_candid_record_n100(value);
}
function to_candid_ClubProfile_n104(value: ClubProfile): _ClubProfile {
    return to_candid_record_n105(value);
}
function to_candid_ClubSettings_n108(value: ClubSettings): _ClubSettings {
    return to_candid_record_n109(value);
}
function to_candid_ClubSponsor_n112(value: ClubSponsor): _ClubSponsor {
    return to_candid_record_n113(value);
}
function to_candid_ClubTeam_n116(value: ClubTeam): _ClubTeam {
    return to_candid_record_n117(value);
}
function to_candid_Draft_n68(value: Draft): _Draft {
    return to_candid_record_n69(value);
}
function to_candid_Link_n66(value: Link): _Link {
    return to_candid_record_n67(value);
}
function to_candid_Listing_n63(value: Listing): _Listing {
    return to_candid_record_n64(value);
}
function to_candid_Operation_n88(value: Operation): _Operation {
    return to_candid_variant_n89(value);
}
function to_candid_Request_n86(value: Request): _Request {
    return to_candid_record_n87(value);
}
function to_candid_RoleGrant_n102(value: RoleGrant): _RoleGrant {
    return to_candid_record_n103(value);
}
function to_candid_Snapshot_n72(value: Snapshot): _Snapshot {
    return to_candid_record_n73(value);
}
function to_candid_opt_n76(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n100(value: {
    id: string;
    teams: Array<string>;
    parent?: Principal;
}): {
    id: string;
    teams: Array<string>;
    parent: [] | [Principal];
} {
    return {
        id: value.id,
        teams: value.teams,
        parent: value.parent ? candid_some(value.parent) : candid_none()
    };
}
function to_candid_record_n103(value: {
    club?: string;
    role: string;
    team?: string;
    user: Principal;
}): {
    club: [] | [string];
    role: string;
    team: [] | [string];
    user: Principal;
} {
    return {
        club: value.club ? candid_some(value.club) : candid_none(),
        role: value.role,
        team: value.team ? candid_some(value.team) : candid_none(),
        user: value.user
    };
}
function to_candid_record_n105(value: {
    id: string;
    secondary_color?: string;
    name: string;
    slug: string;
    description?: string;
    created_at_ms: bigint;
    logo_url?: string;
    is_active: boolean;
    primary_color?: string;
}): {
    id: string;
    secondary_color: [] | [string];
    name: string;
    slug: string;
    description: [] | [string];
    created_at_ms: bigint;
    logo_url: [] | [string];
    is_active: boolean;
    primary_color: [] | [string];
} {
    return {
        id: value.id,
        secondary_color: value.secondary_color ? candid_some(value.secondary_color) : candid_none(),
        name: value.name,
        slug: value.slug,
        description: value.description ? candid_some(value.description) : candid_none(),
        created_at_ms: value.created_at_ms,
        logo_url: value.logo_url ? candid_some(value.logo_url) : candid_none(),
        is_active: value.is_active,
        primary_color: value.primary_color ? candid_some(value.primary_color) : candid_none()
    };
}
function to_candid_record_n109(value: {
    contact_email?: string;
    membership_open: boolean;
    announcement?: string;
    public_directory: boolean;
    club_id: string;
}): {
    contact_email: [] | [string];
    membership_open: boolean;
    announcement: [] | [string];
    public_directory: boolean;
    club_id: string;
} {
    return {
        contact_email: value.contact_email ? candid_some(value.contact_email) : candid_none(),
        membership_open: value.membership_open,
        announcement: value.announcement ? candid_some(value.announcement) : candid_none(),
        public_directory: value.public_directory,
        club_id: value.club_id
    };
}
function to_candid_record_n113(value: {
    id: string;
    website_url?: string;
    name: string;
    tier: string;
    sort_order: number;
    logo_url?: string;
    is_active: boolean;
    club_id: string;
}): {
    id: string;
    website_url: [] | [string];
    name: string;
    tier: string;
    sort_order: number;
    logo_url: [] | [string];
    is_active: boolean;
    club_id: string;
} {
    return {
        id: value.id,
        website_url: value.website_url ? candid_some(value.website_url) : candid_none(),
        name: value.name,
        tier: value.tier,
        sort_order: value.sort_order,
        logo_url: value.logo_url ? candid_some(value.logo_url) : candid_none(),
        is_active: value.is_active,
        club_id: value.club_id
    };
}
function to_candid_record_n117(value: {
    id: string;
    name: string;
    division?: string;
    gender?: string;
    is_active: boolean;
    club_id: string;
    age_group?: string;
}): {
    id: string;
    name: string;
    division: [] | [string];
    gender: [] | [string];
    is_active: boolean;
    club_id: string;
    age_group: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        division: value.division ? candid_some(value.division) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        is_active: value.is_active,
        club_id: value.club_id,
        age_group: value.age_group ? candid_some(value.age_group) : candid_none()
    };
}
function to_candid_record_n64(value: {
    links: Array<Link>;
    revision: bigint;
}): {
    links: Array<_Link>;
    revision: bigint;
} {
    return {
        links: to_candid_vec_n65(value.links),
        revision: value.revision
    };
}
function to_candid_record_n67(value: {
    id: string;
    sort_order: number;
    created_at_ms: bigint;
    draft: Draft;
    club_id: string;
}): {
    id: string;
    sort_order: number;
    created_at_ms: bigint;
    draft: _Draft;
    club_id: string;
} {
    return {
        id: value.id,
        sort_order: value.sort_order,
        created_at_ms: value.created_at_ms,
        draft: to_candid_Draft_n68(value.draft),
        club_id: value.club_id
    };
}
function to_candid_record_n69(value: {
    url: string;
    title: string;
    icon: string;
    is_active: boolean;
    open_mode: string;
    subtitle?: string;
}): {
    url: string;
    title: string;
    icon: string;
    is_active: boolean;
    open_mode: string;
    subtitle: [] | [string];
} {
    return {
        url: value.url,
        title: value.title,
        icon: value.icon,
        is_active: value.is_active,
        open_mode: value.open_mode,
        subtitle: value.subtitle ? candid_some(value.subtitle) : candid_none()
    };
}
function to_candid_record_n73(value: {
    schema: number;
    clubs: Array<[string, Listing]>;
}): {
    schema: number;
    clubs: Array<[string, _Listing]>;
} {
    return {
        schema: value.schema,
        clubs: to_candid_vec_n74(value.clubs)
    };
}
function to_candid_record_n87(value: {
    request_id: string;
    club: string;
    operation: Operation;
    expected_revision: bigint;
}): {
    request_id: string;
    club: string;
    operation: _Operation;
    expected_revision: bigint;
} {
    return {
        request_id: value.request_id,
        club: value.club,
        operation: to_candid_Operation_n88(value.operation),
        expected_revision: value.expected_revision
    };
}
function to_candid_record_n90(value: {
    id?: string;
    draft: Draft;
}): {
    id: [] | [string];
    draft: _Draft;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        draft: to_candid_Draft_n68(value.draft)
    };
}
function to_candid_record_n97(value: {
    teams: Array<Team>;
    guardians: Array<Guardian>;
    clubs: Array<string>;
    children: Array<Child>;
    exclusions: Array<Exclusion>;
    roles: Array<RoleGrant>;
}): {
    teams: Array<_Team>;
    guardians: Array<_Guardian>;
    clubs: Array<string>;
    children: Array<_Child>;
    exclusions: Array<_Exclusion>;
    roles: Array<_RoleGrant>;
} {
    return {
        teams: value.teams,
        guardians: value.guardians,
        clubs: value.clubs,
        children: to_candid_vec_n98(value.children),
        exclusions: value.exclusions,
        roles: to_candid_vec_n101(value.roles)
    };
}
function to_candid_tuple_n75(value: [string, Listing]): [string, _Listing] {
    return [
        value[0],
        to_candid_Listing_n63(value[1])
    ];
}
function to_candid_variant_n89(value: {
    __kind__: "SetActive";
    SetActive: {
        id: string;
        active: boolean;
    };
} | {
    __kind__: "Save";
    Save: {
        id?: string;
        draft: Draft;
    };
} | {
    __kind__: "Remove";
    Remove: {
        id: string;
    };
} | {
    __kind__: "Reorder";
    Reorder: {
        first: string;
        second: string;
    };
}): {
    SetActive: {
        id: string;
        active: boolean;
    };
} | {
    Save: {
        id: [] | [string];
        draft: _Draft;
    };
} | {
    Remove: {
        id: string;
    };
} | {
    Reorder: {
        first: string;
        second: string;
    };
} {
    return value.__kind__ === "SetActive" ? {
        SetActive: value.SetActive
    } : value.__kind__ === "Save" ? {
        Save: to_candid_record_n90(value.Save)
    } : value.__kind__ === "Remove" ? {
        Remove: value.Remove
    } : value.__kind__ === "Reorder" ? {
        Reorder: value.Reorder
    } : value;
}
function to_candid_vec_n101(value: Array<RoleGrant>): Array<_RoleGrant> {
    return value.map((x)=>to_candid_RoleGrant_n102(x));
}
function to_candid_vec_n65(value: Array<Link>): Array<_Link> {
    return value.map((x)=>to_candid_Link_n66(x));
}
function to_candid_vec_n74(value: Array<[string, Listing]>): Array<[string, _Listing]> {
    return value.map((x)=>to_candid_tuple_n75(x));
}
function to_candid_vec_n98(value: Array<Child>): Array<_Child> {
    return value.map((x)=>to_candid_Child_n99(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Club_links {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Club_links(actor);
}
