/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/notification_queue.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface notification {
    id: string;
    status: status;
    body: string;
    club: string;
    next_attempt_ms: bigint;
    kind: string;
    user: string;
    attempts: number;
    idempotency_key: string;
}
export type result_nat16 = {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
};
export type result = {
    __kind__: "Ok";
    Ok: notification;
} | {
    __kind__: "Err";
    Err: string;
};
export type results = {
    __kind__: "Ok";
    Ok: Array<notification>;
} | {
    __kind__: "Err";
    Err: string;
};
export enum status {
    Failed = "Failed",
    Delivered = "Delivered",
    Processing = "Processing",
    Pending = "Pending"
}
export interface notification_queueInterface {
    acknowledge(arg0: string, arg1: string): Promise<result>;
    claim(arg0: bigint, arg1: number): Promise<results>;
    enqueue(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<result>;
    fail(arg0: string, arg1: string, arg2: bigint | null): Promise<result>;
    get_notification(arg0: string): Promise<notification | null>;
    grant_worker(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    recover(): Promise<result_nat16>;
}
import type { notification as _notification, result as _result, result_nat16 as _result_nat16, results as _results, status as _status } from "./declarations/notification_queue.did";
export class Notification_queue implements notification_queueInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acknowledge(arg0: string, arg1: string): Promise<result> {
        const result = await this.actor.acknowledge(arg0, arg1);
        return from_candid_result_n1(result);
    }
    async claim(arg0: bigint, arg1: number): Promise<results> {
        const result = await this.actor.claim(arg0, arg1);
        return from_candid_results_n7(result);
    }
    async enqueue(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<result> {
        const result = await this.actor.enqueue(arg0, arg1, arg2, arg3, arg4, arg5);
        return from_candid_result_n1(result);
    }
    async fail(arg0: string, arg1: string, arg2: bigint | null): Promise<result> {
        const result = await this.actor.fail(arg0, arg1, to_candid_opt_n10(arg2));
        return from_candid_result_n1(result);
    }
    async get_notification(arg0: string): Promise<notification | null> {
        const result = await this.actor.get_notification(arg0);
        return from_candid_opt_n11(result);
    }
    async grant_worker(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_worker(arg0);
        return from_candid_variant_n12(result);
    }
    async initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize();
        return from_candid_variant_n12(result);
    }
    async recover(): Promise<result_nat16> {
        const result = await this.actor.recover();
        return from_candid_result_nat16_n13(result);
    }
}
function from_candid_notification_n3(value: _notification): notification {
    return from_candid_record_n4(value);
}
function from_candid_opt_n11(value: [] | [_notification]): notification | null {
    return value.length === 0 ? null : from_candid_notification_n3(value[0]);
}
function from_candid_record_n4(value: {
    id: string;
    status: _status;
    body: string;
    club: string;
    next_attempt_ms: bigint;
    kind: string;
    user: string;
    attempts: number;
    idempotency_key: string;
}): {
    id: string;
    status: status;
    body: string;
    club: string;
    next_attempt_ms: bigint;
    kind: string;
    user: string;
    attempts: number;
    idempotency_key: string;
} {
    return {
        id: value.id,
        status: from_candid_status_n5(value.status),
        body: value.body,
        club: value.club,
        next_attempt_ms: value.next_attempt_ms,
        kind: value.kind,
        user: value.user,
        attempts: value.attempts,
        idempotency_key: value.idempotency_key
    };
}
function from_candid_result_n1(value: _result): result {
    return from_candid_variant_n2(value);
}
function from_candid_result_nat16_n13(value: _result_nat16): result_nat16 {
    return from_candid_variant_n14(value);
}
function from_candid_results_n7(value: _results): results {
    return from_candid_variant_n8(value);
}
function from_candid_status_n5(value: _status): status {
    return from_candid_variant_n6(value);
}
function from_candid_variant_n12(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n14(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _notification;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: notification;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_notification_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Failed: null;
} | {
    Delivered: null;
} | {
    Processing: null;
} | {
    Pending: null;
}): status {
    return "Failed" in value ? status.Failed : "Delivered" in value ? status.Delivered : "Processing" in value ? status.Processing : "Pending" in value ? status.Pending : value;
}
function from_candid_variant_n8(value: {
    Ok: Array<_notification>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<notification>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n9(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n9(value: Array<_notification>): Array<notification> {
    return value.map((x)=>from_candid_notification_n3(x));
}
function to_candid_opt_n10(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Notification_queue {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Notification_queue(actor);
}
