[toolchain]
moc = "1.14.0"

[moc]
args = ["--default-persistent-actors"]

[dependencies]
core = "2.6.1"

[canisters.messaging_domain_motoko]
main = "src/main.mo"
candid = "messaging_domain_motoko.did"

[canisters.messaging_domain_motoko.migrations]
chain = "src/backend/migrations"
check-limit = 1