/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const init = IDL.Record({ 'governor' : IDL.Principal });
  const availability = IDL.Record({
    'icp_enabled' : IDL.Bool,
    'version' : IDL.Nat64,
    'supabase_enabled' : IDL.Bool,
  });
  const placement_state = IDL.Variant({
    'Blocked' : IDL.Null,
    'Active' : IDL.Null,
    'ReadOnly' : IDL.Null,
    'MigrationRequired' : IDL.Null,
  });
  const backend = IDL.Variant({
    'Icp' : IDL.Record({ 'canister' : IDL.Principal }),
    'Supabase' : IDL.Record({ 'environment' : IDL.Text }),
  });
  const placement = IDL.Record({
    'country' : IDL.Text,
    'version' : IDL.Nat64,
    'state' : placement_state,
    'club_id' : IDL.Text,
    'backend' : backend,
  });
  const decision = IDL.Record({
    'writable' : IDL.Bool,
    'placement' : placement,
    'country_allowed' : IDL.Bool,
    'backend_enabled' : IDL.Bool,
    'reason' : IDL.Text,
  });
  const result_decision = IDL.Variant({
    'Ok' : IDL.Opt(decision),
    'Err' : IDL.Text,
  });
  const operator_role = IDL.Variant({
    'Auditor' : IDL.Null,
    'PlacementAdmin' : IDL.Null,
    'SecurityAdmin' : IDL.Null,
    'InfrastructureAdmin' : IDL.Null,
    'MigrationOperator' : IDL.Null,
  });
  const operator_record = IDL.Record({
    'user' : IDL.Principal,
    'roles' : IDL.Vec(operator_role),
  });
  const result_operator = IDL.Variant({
    'Ok' : operator_record,
    'Err' : IDL.Text,
  });
  const result_opt_placement = IDL.Variant({
    'Ok' : IDL.Opt(placement),
    'Err' : IDL.Text,
  });
  const policy = IDL.Record({
    'country' : IDL.Text,
    'icp_enabled' : IDL.Bool,
    'version' : IDL.Nat64,
    'supabase_enabled' : IDL.Bool,
  });
  const result_policy = IDL.Variant({ 'Ok' : policy, 'Err' : IDL.Text });
  const residency_assignment = IDL.Record({
    'version' : IDL.Nat64,
    'target_alias' : IDL.Text,
    'club_id' : IDL.Text,
    'profile' : IDL.Text,
  });
  const result_opt_residency = IDL.Variant({
    'Ok' : IDL.Opt(residency_assignment),
    'Err' : IDL.Text,
  });
  const residency_policy = IDL.Record({
    'country' : IDL.Text,
    'allowed_profiles' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat64,
  });
  const result_residency_policy = IDL.Variant({
    'Ok' : residency_policy,
    'Err' : IDL.Text,
  });
  const result_bool = IDL.Variant({ 'Ok' : IDL.Bool, 'Err' : IDL.Text });
  const target = IDL.Record({
    'alias' : IDL.Text,
    'deployment_class' : IDL.Text,
    'healthy' : IDL.Bool,
    'version' : IDL.Nat64,
    'enabled' : IDL.Bool,
    'site_id' : IDL.Opt(IDL.Text),
    'profile' : IDL.Text,
    'backend' : backend,
  });
  const result_opt_target = IDL.Variant({
    'Ok' : IDL.Opt(target),
    'Err' : IDL.Text,
  });
  const audit_event = IDL.Record({
    'id' : IDL.Nat64,
    'action' : IDL.Text,
    'at_ns' : IDL.Nat64,
    'registry_version' : IDL.Nat64,
    'detail' : IDL.Text,
    'caller' : IDL.Principal,
    'club_id' : IDL.Opt(IDL.Text),
  });
  const audit_page = IDL.Record({
    'next' : IDL.Opt(IDL.Nat64),
    'events' : IDL.Vec(audit_event),
  });
  const result_audit_page = IDL.Variant({
    'Ok' : audit_page,
    'Err' : IDL.Text,
  });
  const page = IDL.Record({
    'placements' : IDL.Vec(placement),
    'next' : IDL.Opt(IDL.Text),
    'registry_version' : IDL.Nat64,
  });
  const result_page = IDL.Variant({ 'Ok' : page, 'Err' : IDL.Text });
  const result_unit = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const backend_kind = IDL.Variant({ 'Icp' : IDL.Null, 'Supabase' : IDL.Null });
  const result_availability = IDL.Variant({
    'Ok' : availability,
    'Err' : IDL.Text,
  });
  const result_placement = IDL.Variant({ 'Ok' : placement, 'Err' : IDL.Text });
  const result_residency = IDL.Variant({
    'Ok' : residency_assignment,
    'Err' : IDL.Text,
  });
  const site_availability = IDL.Record({
    'version' : IDL.Nat64,
    'enabled' : IDL.Bool,
    'site_id' : IDL.Text,
  });
  const result_site_availability = IDL.Variant({
    'Ok' : site_availability,
    'Err' : IDL.Text,
  });
  const result_target = IDL.Variant({ 'Ok' : target, 'Err' : IDL.Text });
  
  return IDL.Service({
    'get_availability' : IDL.Func([], [availability], ['query']),
    'get_decision' : IDL.Func([IDL.Text], [result_decision], ['query']),
    'get_operator' : IDL.Func([IDL.Principal], [result_operator], ['query']),
    'get_placement' : IDL.Func([IDL.Text], [result_opt_placement], ['query']),
    'get_policy' : IDL.Func([IDL.Text], [result_policy], ['query']),
    'get_residency' : IDL.Func([IDL.Text], [result_opt_residency], ['query']),
    'get_residency_policy' : IDL.Func(
        [IDL.Text],
        [result_residency_policy],
        ['query'],
      ),
    'get_site_availability' : IDL.Func([IDL.Text], [result_bool], ['query']),
    'get_target' : IDL.Func([IDL.Text], [result_opt_target], ['query']),
    'grant_operator' : IDL.Func(
        [IDL.Principal, IDL.Vec(operator_role)],
        [result_operator],
        [],
      ),
    'list_audit' : IDL.Func(
        [IDL.Opt(IDL.Nat64), IDL.Nat16],
        [result_audit_page],
        ['query'],
      ),
    'list_placements' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat16],
        [result_page],
        ['query'],
      ),
    'revoke_operator' : IDL.Func([IDL.Principal], [result_unit], []),
    'set_availability' : IDL.Func(
        [backend_kind, IDL.Bool, IDL.Nat64],
        [result_availability],
        [],
      ),
    'set_placement' : IDL.Func(
        [IDL.Text, IDL.Text, backend, IDL.Nat64],
        [result_placement],
        [],
      ),
    'set_policy' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Nat64],
        [result_policy],
        [],
      ),
    'set_residency' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64],
        [result_residency],
        [],
      ),
    'set_residency_policy' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat64],
        [result_residency_policy],
        [],
      ),
    'set_site_availability' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Nat64],
        [result_site_availability],
        [],
      ),
    'set_state' : IDL.Func(
        [IDL.Text, placement_state, IDL.Nat64],
        [result_placement],
        [],
      ),
    'set_target' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          backend,
          IDL.Text,
          IDL.Bool,
          IDL.Nat64,
        ],
        [result_target],
        [],
      ),
    'set_target_health' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Nat64],
        [result_target],
        [],
      ),
    'version' : IDL.Func([], [IDL.Nat64], ['query']),
  });
};

export const init = ({ IDL }) => {
  const init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [init];
};