/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface audit_event {
  'id' : bigint,
  'action' : string,
  'at_ns' : bigint,
  'registry_version' : bigint,
  'detail' : string,
  'caller' : Principal,
  'club_id' : [] | [string],
}
export interface audit_page {
  'next' : [] | [bigint],
  'events' : Array<audit_event>,
}
export interface availability {
  'icp_enabled' : boolean,
  'version' : bigint,
  'supabase_enabled' : boolean,
}
export type backend = { 'Icp' : { 'canister' : Principal } } |
  { 'Supabase' : { 'environment' : string } };
export type backend_kind = { 'Icp' : null } |
  { 'Supabase' : null };
export interface decision {
  'writable' : boolean,
  'placement' : placement,
  'country_allowed' : boolean,
  'backend_enabled' : boolean,
  'reason' : string,
}
export interface init { 'governor' : Principal }
export interface operator_record {
  'user' : Principal,
  'roles' : Array<operator_role>,
}
export type operator_role = { 'Auditor' : null } |
  { 'PlacementAdmin' : null } |
  { 'SecurityAdmin' : null } |
  { 'InfrastructureAdmin' : null } |
  { 'MigrationOperator' : null };
export interface page {
  'placements' : Array<placement>,
  'next' : [] | [string],
  'registry_version' : bigint,
}
export interface placement {
  'country' : string,
  'version' : bigint,
  'state' : placement_state,
  'club_id' : string,
  'backend' : backend,
}
export type placement_state = { 'Blocked' : null } |
  { 'Active' : null } |
  { 'ReadOnly' : null } |
  { 'MigrationRequired' : null };
export interface policy {
  'country' : string,
  'icp_enabled' : boolean,
  'version' : bigint,
  'supabase_enabled' : boolean,
}
export interface residency_assignment {
  'version' : bigint,
  'target_alias' : string,
  'club_id' : string,
  'profile' : string,
}
export interface residency_policy {
  'country' : string,
  'allowed_profiles' : Array<string>,
  'version' : bigint,
}
export type result_audit_page = { 'Ok' : audit_page } |
  { 'Err' : string };
export type result_availability = { 'Ok' : availability } |
  { 'Err' : string };
export type result_bool = { 'Ok' : boolean } |
  { 'Err' : string };
export type result_decision = { 'Ok' : [] | [decision] } |
  { 'Err' : string };
export type result_operator = { 'Ok' : operator_record } |
  { 'Err' : string };
export type result_opt_placement = { 'Ok' : [] | [placement] } |
  { 'Err' : string };
export type result_opt_residency = { 'Ok' : [] | [residency_assignment] } |
  { 'Err' : string };
export type result_opt_target = { 'Ok' : [] | [target] } |
  { 'Err' : string };
export type result_page = { 'Ok' : page } |
  { 'Err' : string };
export type result_placement = { 'Ok' : placement } |
  { 'Err' : string };
export type result_policy = { 'Ok' : policy } |
  { 'Err' : string };
export type result_residency = { 'Ok' : residency_assignment } |
  { 'Err' : string };
export type result_residency_policy = { 'Ok' : residency_policy } |
  { 'Err' : string };
export type result_site_availability = { 'Ok' : site_availability } |
  { 'Err' : string };
export type result_target = { 'Ok' : target } |
  { 'Err' : string };
export type result_unit = { 'Ok' : null } |
  { 'Err' : string };
export interface site_availability {
  'version' : bigint,
  'enabled' : boolean,
  'site_id' : string,
}
export interface target {
  'alias' : string,
  'deployment_class' : string,
  'healthy' : boolean,
  'version' : bigint,
  'enabled' : boolean,
  'site_id' : [] | [string],
  'profile' : string,
  'backend' : backend,
}
export interface _SERVICE {
  'get_availability' : ActorMethod<[], availability>,
  'get_decision' : ActorMethod<[string], result_decision>,
  'get_operator' : ActorMethod<[Principal], result_operator>,
  'get_placement' : ActorMethod<[string], result_opt_placement>,
  'get_policy' : ActorMethod<[string], result_policy>,
  'get_residency' : ActorMethod<[string], result_opt_residency>,
  'get_residency_policy' : ActorMethod<[string], result_residency_policy>,
  'get_site_availability' : ActorMethod<[string], result_bool>,
  'get_target' : ActorMethod<[string], result_opt_target>,
  'grant_operator' : ActorMethod<
    [Principal, Array<operator_role>],
    result_operator
  >,
  'list_audit' : ActorMethod<[[] | [bigint], number], result_audit_page>,
  'list_placements' : ActorMethod<[[] | [string], number], result_page>,
  'revoke_operator' : ActorMethod<[Principal], result_unit>,
  'set_availability' : ActorMethod<
    [backend_kind, boolean, bigint],
    result_availability
  >,
  'set_placement' : ActorMethod<
    [string, string, backend, bigint],
    result_placement
  >,
  'set_policy' : ActorMethod<[string, boolean, boolean, bigint], result_policy>,
  'set_residency' : ActorMethod<
    [string, string, string, bigint],
    result_residency
  >,
  'set_residency_policy' : ActorMethod<
    [string, Array<string>, bigint],
    result_residency_policy
  >,
  'set_site_availability' : ActorMethod<
    [string, boolean, bigint],
    result_site_availability
  >,
  'set_state' : ActorMethod<
    [string, placement_state, bigint],
    result_placement
  >,
  'set_target' : ActorMethod<
    [string, [] | [string], string, backend, string, boolean, bigint],
    result_target
  >,
  'set_target_health' : ActorMethod<[string, boolean, bigint], result_target>,
  'version' : ActorMethod<[], bigint>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];