/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'legacy_subject' : Principal,
  'version' : bigint,
  'principals' : Array<Principal>,
}
export interface AccountExclusion { 'account_id' : string, 'club' : string }
export interface AccountRole {
  'account_id' : string,
  'club' : [] | [string],
  'role' : string,
  'team' : [] | [string],
}
export interface Acl {
  'teams' : Array<Team>,
  'guardians' : Array<Guardian>,
  'clubs' : Array<string>,
  'children' : Array<Child>,
  'exclusions' : Array<Exclusion>,
  'roles' : Array<RoleGrant>,
}
export interface Challenge {
  'id' : bigint,
  'account_id' : string,
  'issuer' : Principal,
  'target' : Principal,
  'accepted' : boolean,
  'expires_at_ns' : bigint,
  'expected_version' : bigint,
}
export interface Child {
  'id' : string,
  'teams' : Array<string>,
  'parent' : [] | [Principal],
}
export interface ClubProfile {
  'id' : string,
  'secondary_color' : [] | [string],
  'name' : string,
  'slug' : string,
  'description' : [] | [string],
  'created_at_ms' : bigint,
  'logo_url' : [] | [string],
  'is_active' : boolean,
  'primary_color' : [] | [string],
}
export interface ClubSettings {
  'contact_email' : [] | [string],
  'membership_open' : boolean,
  'announcement' : [] | [string],
  'public_directory' : boolean,
  'club_id' : string,
}
export interface ClubSponsor {
  'id' : string,
  'website_url' : [] | [string],
  'name' : string,
  'tier' : string,
  'sort_order' : number,
  'logo_url' : [] | [string],
  'is_active' : boolean,
  'club_id' : string,
}
export interface ClubTeam {
  'id' : string,
  'name' : string,
  'division' : [] | [string],
  'gender' : [] | [string],
  'is_active' : boolean,
  'club_id' : string,
  'age_group' : [] | [string],
}
export interface Config {
  'acl' : Acl,
  'schema' : number,
  'governor' : Principal,
  'acl_version' : bigint,
}
export interface Draft {
  'url' : string,
  'title' : string,
  'icon' : string,
  'is_active' : boolean,
  'open_mode' : string,
  'subtitle' : [] | [string],
}
export interface Exclusion { 'club' : string, 'user' : Principal }
export interface Family { 'account_id' : string, 'child_id' : string }
export interface Guardian { 'child' : string, 'user' : Principal }
export interface Link {
  'id' : string,
  'sort_order' : number,
  'created_at_ms' : bigint,
  'draft' : Draft,
  'club_id' : string,
}
export interface Listing { 'links' : Array<Link>, 'revision' : bigint }
export interface Mutation { 'link' : [] | [Link], 'revision' : bigint }
export type Operation = {
    'SetActive' : { 'id' : string, 'active' : boolean }
  } |
  { 'Save' : { 'id' : [] | [string], 'draft' : Draft } } |
  { 'Remove' : { 'id' : string } } |
  { 'Reorder' : { 'first' : string, 'second' : string } };
export interface Request {
  'request_id' : string,
  'club' : string,
  'operation' : Operation,
  'expected_revision' : bigint,
}
export type Result = { 'Ok' : Account } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Challenge } |
  { 'Err' : string };
export type Result_10 = { 'Ok' : [] | [ClubTeam] } |
  { 'Err' : string };
export type Result_11 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_12 = { 'Ok' : Array<ClubProfile> } |
  { 'Err' : string };
export type Result_13 = { 'Ok' : Array<ClubSponsor> } |
  { 'Err' : string };
export type Result_14 = { 'Ok' : Array<ClubTeam> } |
  { 'Err' : string };
export type Result_15 = { 'Ok' : Mutation } |
  { 'Err' : string };
export type Result_16 = { 'Ok' : ClubProfile } |
  { 'Err' : string };
export type Result_17 = { 'Ok' : ClubSettings } |
  { 'Err' : string };
export type Result_18 = { 'Ok' : ClubSponsor } |
  { 'Err' : string };
export type Result_19 = { 'Ok' : ClubTeam } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : Config } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : Listing } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : State } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Snapshot } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : [] | [ClubProfile] } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : [] | [ClubSettings] } |
  { 'Err' : string };
export type Result_9 = { 'Ok' : [] | [ClubSponsor] } |
  { 'Err' : string };
export interface RoleGrant {
  'club' : [] | [string],
  'role' : string,
  'team' : [] | [string],
  'user' : Principal,
}
export interface Snapshot {
  'schema' : number,
  'clubs' : Array<[string, Listing]>,
}
export interface State {
  'schema' : number,
  'accounts' : Array<Account>,
  'exclusions' : Array<AccountExclusion>,
  'families' : Array<Family>,
  'challenges' : Array<Challenge>,
  'roles' : Array<AccountRole>,
  'next_challenge' : bigint,
}
export interface Team { 'id' : string, 'club' : string }
export interface _SERVICE {
  'accept_identity_link' : ActorMethod<[bigint], Result>,
  'begin_identity_link' : ActorMethod<[Principal], Result_1>,
  'export_acl' : ActorMethod<[], Result_2>,
  'export_frozen_club' : ActorMethod<[string], Result_3>,
  'export_identity_state' : ActorMethod<[], Result_4>,
  'export_links' : ActorMethod<[], Result_5>,
  'freeze_club' : ActorMethod<[string, bigint], Result_6>,
  'get_club_profile' : ActorMethod<[string], Result_7>,
  'get_club_settings' : ActorMethod<[string], Result_8>,
  'get_link' : ActorMethod<[string], Result_3>,
  'get_sponsor' : ActorMethod<[string], Result_9>,
  'get_team' : ActorMethod<[string], Result_10>,
  'import_frozen_club' : ActorMethod<[string, Listing], Result_11>,
  'import_links' : ActorMethod<[Snapshot], Result_11>,
  'list_clubs' : ActorMethod<[[] | [string], number], Result_12>,
  'list_links' : ActorMethod<[string, boolean], Result_3>,
  'list_sponsors' : ActorMethod<[string], Result_13>,
  'list_teams' : ActorMethod<[string], Result_14>,
  'mutate' : ActorMethod<[Request], Result_15>,
  'replace_acl' : ActorMethod<[bigint, Acl], Result_6>,
  'revoke_identity' : ActorMethod<[Principal, bigint], Result>,
  'save_club_profile' : ActorMethod<[ClubProfile], Result_16>,
  'save_club_settings' : ActorMethod<[ClubSettings], Result_17>,
  'save_sponsor' : ActorMethod<[ClubSponsor], Result_18>,
  'save_team' : ActorMethod<[ClubTeam], Result_19>,
  'unfreeze_club' : ActorMethod<[string, bigint], Result_11>,
  'whoami' : ActorMethod<[], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];