/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'version' : IDL.Nat64,
    'principals' : IDL.Vec(IDL.Principal),
  });
  const Result = IDL.Variant({ 'Ok' : Account, 'Err' : IDL.Text });
  const Access = IDL.Record({
    'account_id' : IDL.Text,
    'app_admin' : IDL.Bool,
    'club_admin' : IDL.Bool,
    'guardian' : IDL.Bool,
    'team_member' : IDL.Bool,
  });
  const Result_1 = IDL.Variant({ 'Ok' : Access, 'Err' : IDL.Text });
  const LinkChallenge = IDL.Record({
    'id' : IDL.Nat64,
    'account_id' : IDL.Text,
    'issuer' : IDL.Principal,
    'target' : IDL.Principal,
    'accepted' : IDL.Bool,
    'expires_at_ns' : IDL.Nat64,
    'expected_version' : IDL.Nat64,
  });
  const Result_2 = IDL.Variant({ 'Ok' : LinkChallenge, 'Err' : IDL.Text });
  const ExternalSiteBinding = IDL.Record({
    'account_id' : IDL.Text,
    'external_user_id' : IDL.Text,
    'linked_at_ns' : IDL.Nat64,
    'site_id' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'Ok' : ExternalSiteBinding,
    'Err' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'Ok' : IDL.Bool, 'Err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const PrivacyConsent = IDL.Record({
    'account_id' : IDL.Text,
    'updated_at_ns' : IDL.Nat64,
    'granted' : IDL.Bool,
    'purpose' : IDL.Text,
  });
  const Exclusion = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'site_id' : IDL.Opt(IDL.Text),
  });
  const FamilyLink = IDL.Record({
    'account_id' : IDL.Text,
    'child_id' : IDL.Text,
  });
  const RoleGrant = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'site_id' : IDL.Opt(IDL.Text),
  });
  const State = IDL.Record({
    'privacy_consents' : IDL.Vec(PrivacyConsent),
    'schema' : IDL.Nat32,
    'accounts' : IDL.Vec(Account),
    'governor' : IDL.Principal,
    'exclusions' : IDL.Vec(Exclusion),
    'external_bindings' : IDL.Vec(ExternalSiteBinding),
    'families' : IDL.Vec(FamilyLink),
    'challenges' : IDL.Vec(LinkChallenge),
    'roles' : IDL.Vec(RoleGrant),
    'next_challenge' : IDL.Nat64,
  });
  const Result_3 = IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text });
  const Result_6 = IDL.Variant({
    'Ok' : IDL.Vec(ExternalSiteBinding),
    'Err' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'Ok' : PrivacyConsent, 'Err' : IDL.Text });
  
  return IDL.Service({
    'accept_link' : IDL.Func([IDL.Nat64], [Result], []),
    'access' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result_1],
        ['query'],
      ),
    'access_scoped' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_1],
        ['query'],
      ),
    'begin_link' : IDL.Func([IDL.Principal], [Result_2], []),
    'bind_external_site' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_5],
        [],
      ),
    'check_field_access' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_8],
        ['query'],
      ),
    'erase_account' : IDL.Func([IDL.Text], [Result_4], []),
    'export_state' : IDL.Func([], [Result_3], ['query']),
    'get_external_bindings' : IDL.Func([IDL.Text], [Result_6], ['query']),
    'get_privacy_consent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_8],
        ['query'],
      ),
    'grant_role' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'grant_role_scoped' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_4],
        [],
      ),
    'revoke' : IDL.Func([IDL.Principal, IDL.Nat64], [Result], []),
    'set_exclusion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'set_exclusion_scoped' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'set_family' : IDL.Func([IDL.Text, IDL.Text], [Result_4], []),
    'set_privacy_consent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [Result_7],
        [],
      ),
    'whoami' : IDL.Func([], [Result], ['query']),
  });
};

export const init = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [Init];
};