/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditFilter {
  'opt_from_ts' : [] | [bigint],
  'opt_to_ts' : [] | [bigint],
  'opt_pii_id' : [] | [string],
  'opt_principal' : [] | [Principal],
  'opt_field_id' : [] | [string],
}
export interface AuditRecord {
  'allowed' : boolean,
  'requesting_principal' : Principal,
  'pii_id' : string,
  'operation' : string,
  'timestamp' : bigint,
  'field_id' : string,
  'purpose' : string,
}
export interface DecryptedPii {
  'pii_id' : string,
  'field_id' : string,
  'plaintext' : Uint8Array,
}
export interface EncryptedPii {
  'master_key_id' : string,
  'ciphertext' : Uint8Array,
  'pii_id' : string,
  'nonce' : Uint8Array,
  'field_id' : string,
}
export interface KeyMetadata {
  'status' : { 'Active' : null } |
    { 'Shredded' : null } |
    { 'RotationPending' : null } |
    { 'Revoked' : null },
  'key_id' : string,
  'created_at' : bigint,
  'rotation_due_at' : bigint,
}
export interface KeyRotationResult {
  'new_key_id' : string,
  'old_key_id' : string,
  'rotated_at' : bigint,
}
export interface PiiDeleteResult {
  'shredded_at' : bigint,
  'key_destroyed' : boolean,
}
/**
 * / PII Access Control Canister
 * / Encrypts and mediates access to personally identifiable information (PII)
 * / Enforces field-level access policies and maintains audit trail
 * /
 * / Production note: This uses synthetic encryption for lab testing.
 * / Production deployment should integrate with:
 * / - Hardware Security Module (HSM) or KMS for master key storage
 * / - vetKeys for child media key derivation
 * / - External vault for secret workload identity
 */
export interface _SERVICE {
  'audit_access' : ActorMethod<[AuditFilter], Array<AuditRecord>>,
  'delete_pii' : ActorMethod<
    [string, string],
    { 'Ok' : PiiDeleteResult } |
      { 'Err' : string }
  >,
  'derive_media_key' : ActorMethod<
    [string, Principal, string, bigint],
    { 'Ok' : Uint8Array } |
      { 'Err' : string }
  >,
  'emergency_shutdown' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'get_decrypted_pii' : ActorMethod<
    [string, string, string, string],
    { 'Ok' : DecryptedPii } |
      { 'Err' : string }
  >,
  'get_encrypted_pii' : ActorMethod<
    [string, string],
    { 'Ok' : EncryptedPii } |
      { 'Err' : string }
  >,
  'get_key_metadata' : ActorMethod<[], Array<KeyMetadata>>,
  'initialize_master_key' : ActorMethod<
    [string],
    { 'Ok' : string } |
      { 'Err' : string }
  >,
  'register_pii' : ActorMethod<
    [string, string, Uint8Array, Principal],
    { 'Ok' : EncryptedPii } |
      { 'Err' : string }
  >,
  'rotate_key' : ActorMethod<
    [string],
    { 'Ok' : KeyRotationResult } |
      { 'Err' : string }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];