/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/events_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Rsvp {
    account_id: string;
    updated_at_ms: bigint;
    state: string;
    event_id: string;
}
export interface Recurrence {
    until_ms: bigint;
    frequency: string;
    event_id: string;
}
export interface RosterEntry {
    account_id: string;
    child_id?: string;
    event_id: string;
}
export interface Attendance {
    account_id: string;
    present: boolean;
    note: string;
    event_id: string;
}
export interface Event {
    id: string;
    title: string;
    creator: Principal;
    team_id?: string;
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
}
export interface Duty {
    account_id: string;
    duty: string;
    event_id: string;
}
export interface RoleGrant {
    role: string;
    user: Principal;
    team_id?: string;
    club_id: string;
}
export interface LineupEntry {
    member: string;
    slot: string;
    team_id?: string;
    event_id: string;
}
export interface events_domainInterface {
    add_lineup(event_id: string, member: string, slot: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_event(club_id: string, team_id: string | null, title: string, description: string, starts_at_ms: bigint, ends_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    export_state(): Promise<{
        __kind__: "Ok";
        Ok: {
            lineups: Array<LineupEntry>;
            schema: number;
            recurrences: Array<Recurrence>;
            attendance: Array<Attendance>;
            events: Array<Event>;
            duties: Array<Duty>;
            governor: Principal;
            roster: Array<RosterEntry>;
            roles: Array<RoleGrant>;
            rsvps: Array<Rsvp>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    grant_role(principal: Principal, role: string, club_id: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_events(club_id: string | null, team_id: string | null): Promise<Array<Event>>;
    set_attendance(event_id: string, account_id: string, present: boolean, note: string): Promise<{
        __kind__: "Ok";
        Ok: Attendance;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_duty(event_id: string, account_id: string, duty: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_recurrence(event_id: string, frequency: string, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Recurrence;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_roster(event_id: string, account_id: string, child_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: RosterEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_rsvp(event_id: string, account_id: string, state: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_event(id: string, title: string, description: string, starts_at_ms: bigint, ends_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
import type { Attendance as _Attendance, Duty as _Duty, Event as _Event, LineupEntry as _LineupEntry, Recurrence as _Recurrence, RoleGrant as _RoleGrant, RosterEntry as _RosterEntry, Rsvp as _Rsvp } from "./declarations/events_domain.did";
export class Events_domain implements events_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async add_lineup(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_lineup(arg0, arg1, arg2, to_candid_opt_n1(arg3));
        return from_candid_variant_n2(result);
    }
    async create_event(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_event(arg0, to_candid_opt_n1(arg1), arg2, arg3, arg4, arg5);
        return from_candid_variant_n6(result);
    }
    async export_state(): Promise<{
        __kind__: "Ok";
        Ok: {
            lineups: Array<LineupEntry>;
            schema: number;
            recurrences: Array<Recurrence>;
            attendance: Array<Attendance>;
            events: Array<Event>;
            duties: Array<Duty>;
            governor: Principal;
            roster: Array<RosterEntry>;
            roles: Array<RoleGrant>;
            rsvps: Array<Rsvp>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.export_state();
        return from_candid_variant_n9(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, arg2, to_candid_opt_n1(arg3));
        return from_candid_variant_n19(result);
    }
    async initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize();
        return from_candid_variant_n19(result);
    }
    async list_events(arg0: string | null, arg1: string | null): Promise<Array<Event>> {
        const result = await this.actor.list_events(to_candid_opt_n1(arg0), to_candid_opt_n1(arg1));
        return from_candid_vec_n12(result);
    }
    async set_attendance(arg0: string, arg1: string, arg2: boolean, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: Attendance;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_attendance(arg0, arg1, arg2, arg3);
        return from_candid_variant_n20(result);
    }
    async set_duty(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_duty(arg0, arg1, arg2);
        return from_candid_variant_n21(result);
    }
    async set_recurrence(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Recurrence;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_recurrence(arg0, arg1, arg2);
        return from_candid_variant_n22(result);
    }
    async set_roster(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: RosterEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_roster(arg0, arg1, to_candid_opt_n1(arg2));
        return from_candid_variant_n23(result);
    }
    async set_rsvp(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_rsvp(arg0, arg1, arg2);
        return from_candid_variant_n24(result);
    }
    async update_event(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_event(arg0, arg1, arg2, arg3, arg4);
        return from_candid_variant_n6(result);
    }
}
function from_candid_Event_n7(value: _Event): Event {
    return from_candid_record_n8(value);
}
function from_candid_LineupEntry_n3(value: _LineupEntry): LineupEntry {
    return from_candid_record_n4(value);
}
function from_candid_RoleGrant_n17(value: _RoleGrant): RoleGrant {
    return from_candid_record_n18(value);
}
function from_candid_RosterEntry_n14(value: _RosterEntry): RosterEntry {
    return from_candid_record_n15(value);
}
function from_candid_opt_n5(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(value: {
    lineups: Array<_LineupEntry>;
    schema: number;
    recurrences: Array<_Recurrence>;
    attendance: Array<_Attendance>;
    events: Array<_Event>;
    duties: Array<_Duty>;
    governor: Principal;
    roster: Array<_RosterEntry>;
    roles: Array<_RoleGrant>;
    rsvps: Array<_Rsvp>;
}): {
    lineups: Array<LineupEntry>;
    schema: number;
    recurrences: Array<Recurrence>;
    attendance: Array<Attendance>;
    events: Array<Event>;
    duties: Array<Duty>;
    governor: Principal;
    roster: Array<RosterEntry>;
    roles: Array<RoleGrant>;
    rsvps: Array<Rsvp>;
} {
    return {
        lineups: from_candid_vec_n11(value.lineups),
        schema: value.schema,
        recurrences: value.recurrences,
        attendance: value.attendance,
        events: from_candid_vec_n12(value.events),
        duties: value.duties,
        governor: value.governor,
        roster: from_candid_vec_n13(value.roster),
        roles: from_candid_vec_n16(value.roles),
        rsvps: value.rsvps
    };
}
function from_candid_record_n15(value: {
    account_id: string;
    child_id: [] | [string];
    event_id: string;
}): {
    account_id: string;
    child_id?: string;
    event_id: string;
} {
    return {
        account_id: value.account_id,
        child_id: record_opt_to_undefined(from_candid_opt_n5(value.child_id)),
        event_id: value.event_id
    };
}
function from_candid_record_n18(value: {
    role: string;
    user: Principal;
    team_id: [] | [string];
    club_id: string;
}): {
    role: string;
    user: Principal;
    team_id?: string;
    club_id: string;
} {
    return {
        role: value.role,
        user: value.user,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        club_id: value.club_id
    };
}
function from_candid_record_n4(value: {
    member: string;
    slot: string;
    team_id: [] | [string];
    event_id: string;
}): {
    member: string;
    slot: string;
    team_id?: string;
    event_id: string;
} {
    return {
        member: value.member,
        slot: value.slot,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        event_id: value.event_id
    };
}
function from_candid_record_n8(value: {
    id: string;
    title: string;
    creator: Principal;
    team_id: [] | [string];
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
}): {
    id: string;
    title: string;
    creator: Principal;
    team_id?: string;
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        description: value.description,
        starts_at_ms: value.starts_at_ms,
        ends_at_ms: value.ends_at_ms,
        revision: value.revision,
        club_id: value.club_id
    };
}
function from_candid_variant_n19(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _LineupEntry;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LineupEntry;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_LineupEntry_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: _Attendance;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Attendance;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: _Duty;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Duty;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n22(value: {
    Ok: _Recurrence;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Recurrence;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n23(value: {
    Ok: _RosterEntry;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: RosterEntry;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_RosterEntry_n14(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: _Rsvp;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Rsvp;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _Event;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Event;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Event_n7(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: {
        lineups: Array<_LineupEntry>;
        schema: number;
        recurrences: Array<_Recurrence>;
        attendance: Array<_Attendance>;
        events: Array<_Event>;
        duties: Array<_Duty>;
        governor: Principal;
        roster: Array<_RosterEntry>;
        roles: Array<_RoleGrant>;
        rsvps: Array<_Rsvp>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        lineups: Array<LineupEntry>;
        schema: number;
        recurrences: Array<Recurrence>;
        attendance: Array<Attendance>;
        events: Array<Event>;
        duties: Array<Duty>;
        governor: Principal;
        roster: Array<RosterEntry>;
        roles: Array<RoleGrant>;
        rsvps: Array<Rsvp>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n10(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n11(value: Array<_LineupEntry>): Array<LineupEntry> {
    return value.map((x)=>from_candid_LineupEntry_n3(x));
}
function from_candid_vec_n12(value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n7(x));
}
function from_candid_vec_n13(value: Array<_RosterEntry>): Array<RosterEntry> {
    return value.map((x)=>from_candid_RosterEntry_n14(x));
}
function from_candid_vec_n16(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n17(x));
}
function to_candid_opt_n1(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Events_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Events_domain(actor);
}
