/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/timer_jobs.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type result_job = {
    __kind__: "Ok";
    Ok: job;
} | {
    __kind__: "Err";
    Err: string;
};
export interface snapshot {
    jobs: Array<job>;
    state: queue_state;
}
export type result_snapshot = {
    __kind__: "Ok";
    Ok: snapshot;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_nat16 = {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_state = {
    __kind__: "Ok";
    Ok: queue_state;
} | {
    __kind__: "Err";
    Err: string;
};
export interface queue_state {
    armed: boolean;
    next_run_at_ms?: bigint;
}
export interface page {
    jobs: Array<job>;
    next?: string;
}
export interface reconciliation {
    incoming_jobs: number;
    matching_jobs: number;
    local_jobs: number;
}
export type result_page = {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_reconciliation = {
    __kind__: "Ok";
    Ok: reconciliation;
} | {
    __kind__: "Err";
    Err: string;
};
export interface job {
    id: string;
    last_error?: string;
    status: status;
    run_at_ms: bigint;
    attempts: number;
    scope: string;
    idempotency_key: string;
}
export type result_unit = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_jobs = {
    __kind__: "Ok";
    Ok: Array<job>;
} | {
    __kind__: "Err";
    Err: string;
};
export enum status {
    Failed = "Failed",
    Processing = "Processing",
    Completed = "Completed",
    Pending = "Pending"
}
export interface timer_jobsInterface {
    arm(arg0: bigint): Promise<result_state>;
    claim(arg0: bigint, arg1: number): Promise<result_jobs>;
    complete(arg0: string, arg1: string): Promise<result_job>;
    export_state(): Promise<result_snapshot>;
    fail(arg0: string, arg1: string, arg2: bigint | null): Promise<result_job>;
    get_job(arg0: string): Promise<job | null>;
    get_state(): Promise<queue_state>;
    grant_worker(arg0: Principal): Promise<result_unit>;
    import_state(arg0: snapshot): Promise<result_unit>;
    initialize(): Promise<result_unit>;
    list_jobs(arg0: string | null, arg1: number): Promise<result_page>;
    reconcile(arg0: snapshot): Promise<result_reconciliation>;
    recover_interrupted(): Promise<result_nat16>;
    schedule(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<result_job>;
}
import type { job as _job, page as _page, queue_state as _queue_state, reconciliation as _reconciliation, result_job as _result_job, result_jobs as _result_jobs, result_nat16 as _result_nat16, result_page as _result_page, result_reconciliation as _result_reconciliation, result_snapshot as _result_snapshot, result_state as _result_state, result_unit as _result_unit, snapshot as _snapshot, status as _status } from "./declarations/timer_jobs.did";
export class Timer_jobs implements timer_jobsInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async arm(arg0: bigint): Promise<result_state> {
        const result = await this.actor.arm(arg0);
        return from_candid_result_state_n1(result);
    }
    async claim(arg0: bigint, arg1: number): Promise<result_jobs> {
        const result = await this.actor.claim(arg0, arg1);
        return from_candid_result_jobs_n6(result);
    }
    async complete(arg0: string, arg1: string): Promise<result_job> {
        const result = await this.actor.complete(arg0, arg1);
        return from_candid_result_job_n14(result);
    }
    async export_state(): Promise<result_snapshot> {
        const result = await this.actor.export_state();
        return from_candid_result_snapshot_n16(result);
    }
    async fail(arg0: string, arg1: string, arg2: bigint | null): Promise<result_job> {
        const result = await this.actor.fail(arg0, arg1, to_candid_opt_n20(arg2));
        return from_candid_result_job_n14(result);
    }
    async get_job(arg0: string): Promise<job | null> {
        const result = await this.actor.get_job(arg0);
        return from_candid_opt_n21(result);
    }
    async get_state(): Promise<queue_state> {
        const result = await this.actor.get_state();
        return from_candid_queue_state_n3(result);
    }
    async grant_worker(arg0: Principal): Promise<result_unit> {
        const result = await this.actor.grant_worker(arg0);
        return from_candid_result_unit_n22(result);
    }
    async import_state(arg0: snapshot): Promise<result_unit> {
        const result = await this.actor.import_state(to_candid_snapshot_n24(arg0));
        return from_candid_result_unit_n22(result);
    }
    async initialize(): Promise<result_unit> {
        const result = await this.actor.initialize();
        return from_candid_result_unit_n22(result);
    }
    async list_jobs(arg0: string | null, arg1: number): Promise<result_page> {
        const result = await this.actor.list_jobs(to_candid_opt_n33(arg0), arg1);
        return from_candid_result_page_n34(result);
    }
    async reconcile(arg0: snapshot): Promise<result_reconciliation> {
        const result = await this.actor.reconcile(to_candid_snapshot_n24(arg0));
        return from_candid_result_reconciliation_n38(result);
    }
    async recover_interrupted(): Promise<result_nat16> {
        const result = await this.actor.recover_interrupted();
        return from_candid_result_nat16_n40(result);
    }
    async schedule(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<result_job> {
        const result = await this.actor.schedule(arg0, arg1, arg2, arg3);
        return from_candid_result_job_n14(result);
    }
}
function from_candid_job_n9(value: _job): job {
    return from_candid_record_n10(value);
}
function from_candid_opt_n11(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(value: [] | [_job]): job | null {
    return value.length === 0 ? null : from_candid_job_n9(value[0]);
}
function from_candid_opt_n5(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_page_n36(value: _page): page {
    return from_candid_record_n37(value);
}
function from_candid_queue_state_n3(value: _queue_state): queue_state {
    return from_candid_record_n4(value);
}
function from_candid_record_n10(value: {
    id: string;
    last_error: [] | [string];
    status: _status;
    run_at_ms: bigint;
    attempts: number;
    scope: string;
    idempotency_key: string;
}): {
    id: string;
    last_error?: string;
    status: status;
    run_at_ms: bigint;
    attempts: number;
    scope: string;
    idempotency_key: string;
} {
    return {
        id: value.id,
        last_error: record_opt_to_undefined(from_candid_opt_n11(value.last_error)),
        status: from_candid_status_n12(value.status),
        run_at_ms: value.run_at_ms,
        attempts: value.attempts,
        scope: value.scope,
        idempotency_key: value.idempotency_key
    };
}
function from_candid_record_n19(value: {
    jobs: Array<_job>;
    state: _queue_state;
}): {
    jobs: Array<job>;
    state: queue_state;
} {
    return {
        jobs: from_candid_vec_n8(value.jobs),
        state: from_candid_queue_state_n3(value.state)
    };
}
function from_candid_record_n37(value: {
    jobs: Array<_job>;
    next: [] | [string];
}): {
    jobs: Array<job>;
    next?: string;
} {
    return {
        jobs: from_candid_vec_n8(value.jobs),
        next: record_opt_to_undefined(from_candid_opt_n11(value.next))
    };
}
function from_candid_record_n4(value: {
    armed: boolean;
    next_run_at_ms: [] | [bigint];
}): {
    armed: boolean;
    next_run_at_ms?: bigint;
} {
    return {
        armed: value.armed,
        next_run_at_ms: record_opt_to_undefined(from_candid_opt_n5(value.next_run_at_ms))
    };
}
function from_candid_result_job_n14(value: _result_job): result_job {
    return from_candid_variant_n15(value);
}
function from_candid_result_jobs_n6(value: _result_jobs): result_jobs {
    return from_candid_variant_n7(value);
}
function from_candid_result_nat16_n40(value: _result_nat16): result_nat16 {
    return from_candid_variant_n41(value);
}
function from_candid_result_page_n34(value: _result_page): result_page {
    return from_candid_variant_n35(value);
}
function from_candid_result_reconciliation_n38(value: _result_reconciliation): result_reconciliation {
    return from_candid_variant_n39(value);
}
function from_candid_result_snapshot_n16(value: _result_snapshot): result_snapshot {
    return from_candid_variant_n17(value);
}
function from_candid_result_state_n1(value: _result_state): result_state {
    return from_candid_variant_n2(value);
}
function from_candid_result_unit_n22(value: _result_unit): result_unit {
    return from_candid_variant_n23(value);
}
function from_candid_snapshot_n18(value: _snapshot): snapshot {
    return from_candid_record_n19(value);
}
function from_candid_status_n12(value: _status): status {
    return from_candid_variant_n13(value);
}
function from_candid_variant_n13(value: {
    Failed: null;
} | {
    Processing: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): status {
    return "Failed" in value ? status.Failed : "Processing" in value ? status.Processing : "Completed" in value ? status.Completed : "Pending" in value ? status.Pending : value;
}
function from_candid_variant_n15(value: {
    Ok: _job;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: job;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_job_n9(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n17(value: {
    Ok: _snapshot;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: snapshot;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_snapshot_n18(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _queue_state;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: queue_state;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_queue_state_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n23(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n35(value: {
    Ok: _page;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_page_n36(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n39(value: {
    Ok: _reconciliation;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: reconciliation;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n41(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: Array<_job>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<job>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n8(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n8(value: Array<_job>): Array<job> {
    return value.map((x)=>from_candid_job_n9(x));
}
function to_candid_job_n27(value: job): _job {
    return to_candid_record_n28(value);
}
function to_candid_opt_n20(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_queue_state_n31(value: queue_state): _queue_state {
    return to_candid_record_n32(value);
}
function to_candid_record_n25(value: {
    jobs: Array<job>;
    state: queue_state;
}): {
    jobs: Array<_job>;
    state: _queue_state;
} {
    return {
        jobs: to_candid_vec_n26(value.jobs),
        state: to_candid_queue_state_n31(value.state)
    };
}
function to_candid_record_n28(value: {
    id: string;
    last_error?: string;
    status: status;
    run_at_ms: bigint;
    attempts: number;
    scope: string;
    idempotency_key: string;
}): {
    id: string;
    last_error: [] | [string];
    status: _status;
    run_at_ms: bigint;
    attempts: number;
    scope: string;
    idempotency_key: string;
} {
    return {
        id: value.id,
        last_error: value.last_error ? candid_some(value.last_error) : candid_none(),
        status: to_candid_status_n29(value.status),
        run_at_ms: value.run_at_ms,
        attempts: value.attempts,
        scope: value.scope,
        idempotency_key: value.idempotency_key
    };
}
function to_candid_record_n32(value: {
    armed: boolean;
    next_run_at_ms?: bigint;
}): {
    armed: boolean;
    next_run_at_ms: [] | [bigint];
} {
    return {
        armed: value.armed,
        next_run_at_ms: value.next_run_at_ms ? candid_some(value.next_run_at_ms) : candid_none()
    };
}
function to_candid_snapshot_n24(value: snapshot): _snapshot {
    return to_candid_record_n25(value);
}
function to_candid_status_n29(value: status): _status {
    return to_candid_variant_n30(value);
}
function to_candid_variant_n30(value: status): {
    Failed: null;
} | {
    Processing: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == status.Failed ? {
        Failed: null
    } : value == status.Processing ? {
        Processing: null
    } : value == status.Completed ? {
        Completed: null
    } : value == status.Pending ? {
        Pending: null
    } : value;
}
function to_candid_vec_n26(value: Array<job>): Array<_job> {
    return value.map((x)=>to_candid_job_n27(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Timer_jobs {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Timer_jobs(actor);
}
