/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface assign_domain_request {
  'domain' : string,
  'shard' : Principal,
  'expected_revision' : bigint,
  'club_id' : string,
}
export interface assign_domain_result {
  'revision' : bigint,
  'route' : domain_route,
}
export interface assign_request {
  'shard' : Principal,
  'expected_revision' : bigint,
  'club_id' : string,
}
export interface assign_result { 'revision' : bigint, 'route' : route }
export interface domain_migration {
  'destination' : Principal,
  'domain' : string,
  'source' : Principal,
  'route_revision' : bigint,
  'club_id' : string,
  'migration_revision' : bigint,
}
export interface domain_route {
  'domain' : string,
  'shard' : Principal,
  'revision' : bigint,
  'club_id' : string,
}
export interface init { 'governor' : Principal }
export interface migration {
  'destination' : Principal,
  'source' : Principal,
  'route_revision' : bigint,
  'club_id' : string,
  'migration_revision' : bigint,
}
export interface page {
  'next' : [] | [string],
  'routes' : Array<route>,
  'revision' : bigint,
}
export type result_assign = { 'Ok' : assign_result } |
  { 'Err' : string };
export type result_assign_domain = { 'Ok' : assign_domain_result } |
  { 'Err' : string };
export type result_domain_migration = { 'Ok' : domain_migration } |
  { 'Err' : string };
export type result_migration = { 'Ok' : migration } |
  { 'Err' : string };
export type result_nat64 = { 'Ok' : bigint } |
  { 'Err' : string };
export type result_opt_domain_migration = { 'Ok' : [] | [domain_migration] } |
  { 'Err' : string };
export type result_opt_domain_route = { 'Ok' : [] | [domain_route] } |
  { 'Err' : string };
export type result_opt_migration = { 'Ok' : [] | [migration] } |
  { 'Err' : string };
export type result_opt_route = { 'Ok' : [] | [route] } |
  { 'Err' : string };
export type result_page = { 'Ok' : page } |
  { 'Err' : string };
export interface route {
  'shard' : Principal,
  'revision' : bigint,
  'club_id' : string,
}
export interface _SERVICE {
  'abort_domain_migration' : ActorMethod<
    [string, string, bigint],
    result_nat64
  >,
  'abort_migration' : ActorMethod<[string, bigint], result_nat64>,
  'assign' : ActorMethod<[assign_request], result_assign>,
  'assign_domain' : ActorMethod<[assign_domain_request], result_assign_domain>,
  'begin_domain_migration' : ActorMethod<
    [string, string, Principal, bigint],
    result_domain_migration
  >,
  'begin_migration' : ActorMethod<
    [string, Principal, bigint],
    result_migration
  >,
  'commit_domain_migration' : ActorMethod<
    [string, string, bigint],
    result_assign_domain
  >,
  'commit_migration' : ActorMethod<[string, bigint], result_assign>,
  'get_domain_migration' : ActorMethod<
    [string, string],
    result_opt_domain_migration
  >,
  'get_domain_route' : ActorMethod<[string, string], result_opt_domain_route>,
  'get_migration' : ActorMethod<[string], result_opt_migration>,
  'get_route' : ActorMethod<[string], result_opt_route>,
  'list_routes' : ActorMethod<[[] | [string], number], result_page>,
  'version' : ActorMethod<[], bigint>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];