/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Access {
  'account_id' : string,
  'app_admin' : boolean,
  'club_admin' : boolean,
  'guardian' : boolean,
  'team_member' : boolean,
}
export interface Account {
  'id' : string,
  'version' : bigint,
  'principals' : Array<Principal>,
}
export interface Exclusion {
  'account_id' : string,
  'club' : string,
  'team' : [] | [string],
  'site_id' : [] | [string],
}
export interface ExternalSiteBinding {
  'account_id' : string,
  'external_user_id' : string,
  'linked_at_ns' : bigint,
  'site_id' : string,
}
export interface FamilyLink { 'account_id' : string, 'child_id' : string }
export interface Init { 'governor' : Principal }
export interface LinkChallenge {
  'id' : bigint,
  'account_id' : string,
  'issuer' : Principal,
  'target' : Principal,
  'accepted' : boolean,
  'expires_at_ns' : bigint,
  'expected_version' : bigint,
}
export interface PrivacyConsent {
  'account_id' : string,
  'updated_at_ns' : bigint,
  'granted' : boolean,
  'purpose' : string,
}
export type Result = { 'Ok' : Account } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Access } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : LinkChallenge } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : State } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : ExternalSiteBinding } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Array<ExternalSiteBinding> } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : PrivacyConsent } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : boolean } |
  { 'Err' : string };
export interface RoleGrant {
  'account_id' : string,
  'club' : [] | [string],
  'role' : string,
  'team' : [] | [string],
  'site_id' : [] | [string],
}
export interface State {
  'privacy_consents' : Array<PrivacyConsent>,
  'schema' : number,
  'accounts' : Array<Account>,
  'governor' : Principal,
  'exclusions' : Array<Exclusion>,
  'external_bindings' : Array<ExternalSiteBinding>,
  'families' : Array<FamilyLink>,
  'challenges' : Array<LinkChallenge>,
  'roles' : Array<RoleGrant>,
  'next_challenge' : bigint,
}
export interface _SERVICE {
  'accept_link' : ActorMethod<[bigint], Result>,
  'access' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    Result_1
  >,
  'access_scoped' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string]],
    Result_1
  >,
  'begin_link' : ActorMethod<[Principal], Result_2>,
  'bind_external_site' : ActorMethod<[string, string, string], Result_5>,
  'check_field_access' : ActorMethod<[string, string], Result_8>,
  'erase_account' : ActorMethod<[string], Result_4>,
  'export_state' : ActorMethod<[], Result_3>,
  'get_external_bindings' : ActorMethod<[string], Result_6>,
  'get_privacy_consent' : ActorMethod<[string, string], Result_8>,
  'grant_role' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    Result_4
  >,
  'grant_role_scoped' : ActorMethod<
    [string, string, [] | [string], [] | [string], [] | [string]],
    Result_4
  >,
  'register_account' : ActorMethod<[], Result>,
  'revoke' : ActorMethod<[Principal, bigint], Result>,
  'set_exclusion' : ActorMethod<[string, string, [] | [string]], Result_4>,
  'set_exclusion_scoped' : ActorMethod<
    [string, [] | [string], string, [] | [string]],
    Result_4
  >,
  'set_family' : ActorMethod<[string, string], Result_4>,
  'set_privacy_consent' : ActorMethod<[string, string, boolean], Result_7>,
  'whoami' : ActorMethod<[], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];