/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/media_metadata.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result = {
    __kind__: "Ok";
    Ok: Asset;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: Asset;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Asset {
    id: string;
    storage_path: string;
    retention_until_ms: bigint;
    deleted: boolean;
    owner: Principal;
    kind: string;
    mime: string;
    encrypted: boolean;
    content_length: bigint;
    checksum: string;
    child_sensitive: boolean;
    visibility: string;
    club_id: string;
    expires_at_ms: bigint;
}
export interface Init {
    governor: Principal;
}
export interface State {
    capabilities: Array<Capability>;
    schema: number;
    assets: Array<Asset>;
    governor: Principal;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: Capability;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Capability {
    action: string;
    owner: Principal;
    allowed: boolean;
    asset_id: string;
    purpose: string;
    expires_at_ms: bigint;
}
export interface media_metadataInterface {
    delete_asset(arg0: string): Promise<Result_3>;
    export_state(): Promise<Result_2>;
    get_asset(arg0: string): Promise<Asset | null>;
    issue_capability(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<Result_1>;
    register_asset(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<Result>;
}
import type { Asset as _Asset, Capability as _Capability, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, State as _State } from "./declarations/media_metadata.did";
export class Media_metadata implements media_metadataInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async delete_asset(arg0: string): Promise<Result_3> {
        const result = await this.actor.delete_asset(arg0);
        return from_candid_Result_3_n1(result);
    }
    async export_state(): Promise<Result_2> {
        const result = await this.actor.export_state();
        return from_candid_Result_2_n3(result);
    }
    async get_asset(arg0: string): Promise<Asset | null> {
        const result = await this.actor.get_asset(arg0);
        return from_candid_opt_n5(result);
    }
    async issue_capability(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<Result_1> {
        const result = await this.actor.issue_capability(arg0, arg1, arg2, arg3);
        return from_candid_Result_1_n6(result);
    }
    async register_asset(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<Result> {
        const result = await this.actor.register_asset(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        return from_candid_Result_n8(result);
    }
}
function from_candid_Result_1_n6(value: _Result_1): Result_1 {
    return from_candid_variant_n7(value);
}
function from_candid_Result_2_n3(value: _Result_2): Result_2 {
    return from_candid_variant_n4(value);
}
function from_candid_Result_3_n1(value: _Result_3): Result_3 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_n8(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_opt_n5(value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n2(value: {
    Ok: _Asset;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Asset;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: _Capability;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Capability;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Media_metadata {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Media_metadata(actor);
}
