import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react';
import { afterEach, expect, test } from 'vitest';
import LabApp from '../src/lab/LabApp';
afterEach(cleanup);
test('existing editor creates, edits, hides and deletes a synthetic link', async () => {
  globalThis.fetch = async () => { throw new Error('No network permitted in editor test'); };
  render(<LabApp />);
  fireEvent.click(screen.getByRole('button', { name: /^Add$/ }));
  fireEvent.change(screen.getByLabelText('Title'), { target: { value: 'Synthetic registration' } });
  fireEvent.change(screen.getByLabelText('Web address'), { target: { value: 'https://example.invalid/register' } });
  fireEvent.click(screen.getByRole('button', { name: /add link/i }));
  await waitFor(() => expect(screen.getAllByText('Synthetic registration').length).toBe(2));
  fireEvent.click(screen.getByRole('button', { name: 'Edit link' }));
  fireEvent.change(screen.getByLabelText('Title'), { target: { value: 'Updated synthetic link' } });
  fireEvent.click(screen.getByRole('button', { name: 'Save changes' }));
  await waitFor(() => expect(screen.getAllByText('Updated synthetic link').length).toBe(2));
  fireEvent.click(screen.getByRole('switch', { name: 'Visible to members' }));
  await waitFor(() => expect(screen.getAllByText('Updated synthetic link').length).toBe(1));
  fireEvent.click(screen.getByRole('button', { name: 'Remove link' }));
  await waitFor(() => expect(screen.queryByText('Updated synthetic link')).toBeNull());
});
