/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/shard_router.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface init {
    governor: Principal;
}
export type result_assign = {
    __kind__: "Ok";
    Ok: assign_result;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_migration = {
    __kind__: "Ok";
    Ok: migration;
} | {
    __kind__: "Err";
    Err: string;
};
export interface assign_domain_request {
    domain: string;
    shard: Principal;
    expected_revision: bigint;
    club_id: string;
}
export interface assign_request {
    shard: Principal;
    expected_revision: bigint;
    club_id: string;
}
export interface route {
    shard: Principal;
    revision: bigint;
    club_id: string;
}
export type result_assign_domain = {
    __kind__: "Ok";
    Ok: assign_domain_result;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_opt_route = {
    __kind__: "Ok";
    Ok: route | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_opt_domain_route = {
    __kind__: "Ok";
    Ok: domain_route | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface assign_domain_result {
    revision: bigint;
    route: domain_route;
}
export interface migration {
    destination: Principal;
    source: Principal;
    route_revision: bigint;
    club_id: string;
    migration_revision: bigint;
}
export interface page {
    next?: string;
    routes: Array<route>;
    revision: bigint;
}
export type result_page = {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_nat64 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_domain_migration = {
    __kind__: "Ok";
    Ok: domain_migration;
} | {
    __kind__: "Err";
    Err: string;
};
export interface assign_result {
    revision: bigint;
    route: route;
}
export type result_opt_migration = {
    __kind__: "Ok";
    Ok: migration | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_opt_domain_migration = {
    __kind__: "Ok";
    Ok: domain_migration | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface domain_route {
    domain: string;
    shard: Principal;
    revision: bigint;
    club_id: string;
}
export interface domain_migration {
    destination: Principal;
    domain: string;
    source: Principal;
    route_revision: bigint;
    club_id: string;
    migration_revision: bigint;
}
export interface shard_routerInterface {
    abort_domain_migration(arg0: string, arg1: string, arg2: bigint): Promise<result_nat64>;
    abort_migration(arg0: string, arg1: bigint): Promise<result_nat64>;
    assign(arg0: assign_request): Promise<result_assign>;
    assign_domain(arg0: assign_domain_request): Promise<result_assign_domain>;
    begin_domain_migration(arg0: string, arg1: string, arg2: Principal, arg3: bigint): Promise<result_domain_migration>;
    begin_migration(arg0: string, arg1: Principal, arg2: bigint): Promise<result_migration>;
    commit_domain_migration(arg0: string, arg1: string, arg2: bigint): Promise<result_assign_domain>;
    commit_migration(arg0: string, arg1: bigint): Promise<result_assign>;
    get_domain_migration(arg0: string, arg1: string): Promise<result_opt_domain_migration>;
    get_domain_route(arg0: string, arg1: string): Promise<result_opt_domain_route>;
    get_migration(arg0: string): Promise<result_opt_migration>;
    get_route(arg0: string): Promise<result_opt_route>;
    list_routes(arg0: string | null, arg1: number): Promise<result_page>;
    version(): Promise<bigint>;
}
import type { assign_domain_result as _assign_domain_result, assign_result as _assign_result, domain_migration as _domain_migration, domain_route as _domain_route, migration as _migration, page as _page, result_assign as _result_assign, result_assign_domain as _result_assign_domain, result_domain_migration as _result_domain_migration, result_migration as _result_migration, result_nat64 as _result_nat64, result_opt_domain_migration as _result_opt_domain_migration, result_opt_domain_route as _result_opt_domain_route, result_opt_migration as _result_opt_migration, result_opt_route as _result_opt_route, result_page as _result_page, route as _route } from "./declarations/shard_router.did";
export class Shard_router implements shard_routerInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async abort_domain_migration(arg0: string, arg1: string, arg2: bigint): Promise<result_nat64> {
        const result = await this.actor.abort_domain_migration(arg0, arg1, arg2);
        return from_candid_result_nat64_n1(result);
    }
    async abort_migration(arg0: string, arg1: bigint): Promise<result_nat64> {
        const result = await this.actor.abort_migration(arg0, arg1);
        return from_candid_result_nat64_n1(result);
    }
    async assign(arg0: assign_request): Promise<result_assign> {
        const result = await this.actor.assign(arg0);
        return from_candid_result_assign_n3(result);
    }
    async assign_domain(arg0: assign_domain_request): Promise<result_assign_domain> {
        const result = await this.actor.assign_domain(arg0);
        return from_candid_result_assign_domain_n5(result);
    }
    async begin_domain_migration(arg0: string, arg1: string, arg2: Principal, arg3: bigint): Promise<result_domain_migration> {
        const result = await this.actor.begin_domain_migration(arg0, arg1, arg2, arg3);
        return from_candid_result_domain_migration_n7(result);
    }
    async begin_migration(arg0: string, arg1: Principal, arg2: bigint): Promise<result_migration> {
        const result = await this.actor.begin_migration(arg0, arg1, arg2);
        return from_candid_result_migration_n9(result);
    }
    async commit_domain_migration(arg0: string, arg1: string, arg2: bigint): Promise<result_assign_domain> {
        const result = await this.actor.commit_domain_migration(arg0, arg1, arg2);
        return from_candid_result_assign_domain_n5(result);
    }
    async commit_migration(arg0: string, arg1: bigint): Promise<result_assign> {
        const result = await this.actor.commit_migration(arg0, arg1);
        return from_candid_result_assign_n3(result);
    }
    async get_domain_migration(arg0: string, arg1: string): Promise<result_opt_domain_migration> {
        const result = await this.actor.get_domain_migration(arg0, arg1);
        return from_candid_result_opt_domain_migration_n11(result);
    }
    async get_domain_route(arg0: string, arg1: string): Promise<result_opt_domain_route> {
        const result = await this.actor.get_domain_route(arg0, arg1);
        return from_candid_result_opt_domain_route_n14(result);
    }
    async get_migration(arg0: string): Promise<result_opt_migration> {
        const result = await this.actor.get_migration(arg0);
        return from_candid_result_opt_migration_n17(result);
    }
    async get_route(arg0: string): Promise<result_opt_route> {
        const result = await this.actor.get_route(arg0);
        return from_candid_result_opt_route_n20(result);
    }
    async list_routes(arg0: string | null, arg1: number): Promise<result_page> {
        const result = await this.actor.list_routes(to_candid_opt_n23(arg0), arg1);
        return from_candid_result_page_n24(result);
    }
    async version(): Promise<bigint> {
        const result = await this.actor.version();
        return result;
    }
}
function from_candid_opt_n13(value: [] | [_domain_migration]): domain_migration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(value: [] | [_domain_route]): domain_route | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(value: [] | [_migration]): migration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(value: [] | [_route]): route | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_page_n26(value: _page): page {
    return from_candid_record_n27(value);
}
function from_candid_record_n27(value: {
    next: [] | [string];
    routes: Array<_route>;
    revision: bigint;
}): {
    next?: string;
    routes: Array<route>;
    revision: bigint;
} {
    return {
        next: record_opt_to_undefined(from_candid_opt_n28(value.next)),
        routes: value.routes,
        revision: value.revision
    };
}
function from_candid_result_assign_domain_n5(value: _result_assign_domain): result_assign_domain {
    return from_candid_variant_n6(value);
}
function from_candid_result_assign_n3(value: _result_assign): result_assign {
    return from_candid_variant_n4(value);
}
function from_candid_result_domain_migration_n7(value: _result_domain_migration): result_domain_migration {
    return from_candid_variant_n8(value);
}
function from_candid_result_migration_n9(value: _result_migration): result_migration {
    return from_candid_variant_n10(value);
}
function from_candid_result_nat64_n1(value: _result_nat64): result_nat64 {
    return from_candid_variant_n2(value);
}
function from_candid_result_opt_domain_migration_n11(value: _result_opt_domain_migration): result_opt_domain_migration {
    return from_candid_variant_n12(value);
}
function from_candid_result_opt_domain_route_n14(value: _result_opt_domain_route): result_opt_domain_route {
    return from_candid_variant_n15(value);
}
function from_candid_result_opt_migration_n17(value: _result_opt_migration): result_opt_migration {
    return from_candid_variant_n18(value);
}
function from_candid_result_opt_route_n20(value: _result_opt_route): result_opt_route {
    return from_candid_variant_n21(value);
}
function from_candid_result_page_n24(value: _result_page): result_page {
    return from_candid_variant_n25(value);
}
function from_candid_variant_n10(value: {
    Ok: _migration;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: migration;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n12(value: {
    Ok: [] | [_domain_migration];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: domain_migration | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n13(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n15(value: {
    Ok: [] | [_domain_route];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: domain_route | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n16(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n18(value: {
    Ok: [] | [_migration];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: migration | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n19(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: bigint;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: [] | [_route];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: route | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n22(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n25(value: {
    Ok: _page;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_page_n26(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _assign_result;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: assign_result;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _assign_domain_result;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: assign_domain_result;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: _domain_migration;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: domain_migration;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function to_candid_opt_n23(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Shard_router {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Shard_router(actor);
}
