/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/identity_access.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Account {
    id: string;
    version: bigint;
    principals: Array<Principal>;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: LinkChallenge;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_6 = {
    __kind__: "Ok";
    Ok: Array<ExternalSiteBinding>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface LinkChallenge {
    id: bigint;
    account_id: string;
    issuer: Principal;
    target: Principal;
    accepted: boolean;
    expires_at_ns: bigint;
    expected_version: bigint;
}
export interface Init {
    governor: Principal;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: ExternalSiteBinding;
} | {
    __kind__: "Err";
    Err: string;
};
export interface PrivacyConsent {
    account_id: string;
    updated_at_ns: bigint;
    granted: boolean;
    purpose: string;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: Access;
} | {
    __kind__: "Err";
    Err: string;
};
export interface RoleGrant {
    account_id: string;
    club?: string;
    role: string;
    team?: string;
    site_id?: string;
}
export interface FamilyLink {
    account_id: string;
    child_id: string;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result = {
    __kind__: "Ok";
    Ok: Account;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Access {
    account_id: string;
    app_admin: boolean;
    club_admin: boolean;
    guardian: boolean;
    team_member: boolean;
}
export type Result_8 = {
    __kind__: "Ok";
    Ok: boolean;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Exclusion {
    account_id: string;
    club: string;
    team?: string;
    site_id?: string;
}
export type Result_7 = {
    __kind__: "Ok";
    Ok: PrivacyConsent;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ExternalSiteBinding {
    account_id: string;
    external_user_id: string;
    linked_at_ns: bigint;
    site_id: string;
}
export interface State {
    privacy_consents: Array<PrivacyConsent>;
    schema: number;
    accounts: Array<Account>;
    governor: Principal;
    exclusions: Array<Exclusion>;
    external_bindings: Array<ExternalSiteBinding>;
    families: Array<FamilyLink>;
    challenges: Array<LinkChallenge>;
    roles: Array<RoleGrant>;
    next_challenge: bigint;
}
export interface identity_accessInterface {
    accept_link(arg0: bigint): Promise<Result>;
    access(arg0: string | null, arg1: string | null, arg2: string | null): Promise<Result_1>;
    access_scoped(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<Result_1>;
    begin_link(arg0: Principal): Promise<Result_2>;
    bind_external_site(arg0: string, arg1: string, arg2: string): Promise<Result_5>;
    check_field_access(arg0: string, arg1: string): Promise<Result_8>;
    export_state(): Promise<Result_3>;
    get_external_bindings(arg0: string): Promise<Result_6>;
    get_privacy_consent(arg0: string, arg1: string): Promise<Result_8>;
    grant_role(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<Result_4>;
    grant_role_scoped(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null): Promise<Result_4>;
    revoke(arg0: Principal, arg1: bigint): Promise<Result>;
    set_exclusion(arg0: string, arg1: string, arg2: string | null): Promise<Result_4>;
    set_exclusion_scoped(arg0: string, arg1: string | null, arg2: string, arg3: string | null): Promise<Result_4>;
    set_family(arg0: string, arg1: string): Promise<Result_4>;
    set_privacy_consent(arg0: string, arg1: string, arg2: boolean): Promise<Result_7>;
    whoami(): Promise<Result>;
}
import type { Access as _Access, Account as _Account, Exclusion as _Exclusion, ExternalSiteBinding as _ExternalSiteBinding, FamilyLink as _FamilyLink, LinkChallenge as _LinkChallenge, PrivacyConsent as _PrivacyConsent, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, RoleGrant as _RoleGrant, State as _State } from "./declarations/identity_access.did";
export class Identity_access implements identity_accessInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async accept_link(arg0: bigint): Promise<Result> {
        const result = await this.actor.accept_link(arg0);
        return from_candid_Result_n1(result);
    }
    async access(arg0: string | null, arg1: string | null, arg2: string | null): Promise<Result_1> {
        const result = await this.actor.access(to_candid_opt_n3(arg0), to_candid_opt_n3(arg1), to_candid_opt_n3(arg2));
        return from_candid_Result_1_n4(result);
    }
    async access_scoped(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<Result_1> {
        const result = await this.actor.access_scoped(to_candid_opt_n3(arg0), to_candid_opt_n3(arg1), to_candid_opt_n3(arg2), to_candid_opt_n3(arg3));
        return from_candid_Result_1_n4(result);
    }
    async begin_link(arg0: Principal): Promise<Result_2> {
        const result = await this.actor.begin_link(arg0);
        return from_candid_Result_2_n6(result);
    }
    async bind_external_site(arg0: string, arg1: string, arg2: string): Promise<Result_5> {
        const result = await this.actor.bind_external_site(arg0, arg1, arg2);
        return from_candid_Result_5_n8(result);
    }
    async check_field_access(arg0: string, arg1: string): Promise<Result_8> {
        const result = await this.actor.check_field_access(arg0, arg1);
        return from_candid_Result_8_n23(result);
    }
    async export_state(): Promise<Result_3> {
        const result = await this.actor.export_state();
        return from_candid_Result_3_n10(result);
    }
    async get_external_bindings(arg0: string): Promise<Result_6> {
        const result = await this.actor.get_external_bindings(arg0);
        return from_candid_Result_6_n21(result);
    }
    async get_privacy_consent(arg0: string, arg1: string): Promise<Result_8> {
        const result = await this.actor.get_privacy_consent(arg0, arg1);
        return from_candid_Result_8_n23(result);
    }
    async grant_role(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<Result_4> {
        const result = await this.actor.grant_role(arg0, arg1, to_candid_opt_n3(arg2), to_candid_opt_n3(arg3));
        return from_candid_Result_4_n25(result);
    }
    async grant_role_scoped(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null): Promise<Result_4> {
        const result = await this.actor.grant_role_scoped(arg0, arg1, to_candid_opt_n3(arg2), to_candid_opt_n3(arg3), to_candid_opt_n3(arg4));
        return from_candid_Result_4_n25(result);
    }
    async revoke(arg0: Principal, arg1: bigint): Promise<Result> {
        const result = await this.actor.revoke(arg0, arg1);
        return from_candid_Result_n1(result);
    }
    async set_exclusion(arg0: string, arg1: string, arg2: string | null): Promise<Result_4> {
        const result = await this.actor.set_exclusion(arg0, arg1, to_candid_opt_n3(arg2));
        return from_candid_Result_4_n25(result);
    }
    async set_exclusion_scoped(arg0: string, arg1: string | null, arg2: string, arg3: string | null): Promise<Result_4> {
        const result = await this.actor.set_exclusion_scoped(arg0, to_candid_opt_n3(arg1), arg2, to_candid_opt_n3(arg3));
        return from_candid_Result_4_n25(result);
    }
    async set_family(arg0: string, arg1: string): Promise<Result_4> {
        const result = await this.actor.set_family(arg0, arg1);
        return from_candid_Result_4_n25(result);
    }
    async set_privacy_consent(arg0: string, arg1: string, arg2: boolean): Promise<Result_7> {
        const result = await this.actor.set_privacy_consent(arg0, arg1, arg2);
        return from_candid_Result_7_n27(result);
    }
    async whoami(): Promise<Result> {
        const result = await this.actor.whoami();
        return from_candid_Result_n1(result);
    }
}
function from_candid_Exclusion_n15(value: _Exclusion): Exclusion {
    return from_candid_record_n16(value);
}
function from_candid_Result_1_n4(value: _Result_1): Result_1 {
    return from_candid_variant_n5(value);
}
function from_candid_Result_2_n6(value: _Result_2): Result_2 {
    return from_candid_variant_n7(value);
}
function from_candid_Result_3_n10(value: _Result_3): Result_3 {
    return from_candid_variant_n11(value);
}
function from_candid_Result_4_n25(value: _Result_4): Result_4 {
    return from_candid_variant_n26(value);
}
function from_candid_Result_5_n8(value: _Result_5): Result_5 {
    return from_candid_variant_n9(value);
}
function from_candid_Result_6_n21(value: _Result_6): Result_6 {
    return from_candid_variant_n22(value);
}
function from_candid_Result_7_n27(value: _Result_7): Result_7 {
    return from_candid_variant_n28(value);
}
function from_candid_Result_8_n23(value: _Result_8): Result_8 {
    return from_candid_variant_n24(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_RoleGrant_n19(value: _RoleGrant): RoleGrant {
    return from_candid_record_n20(value);
}
function from_candid_State_n12(value: _State): State {
    return from_candid_record_n13(value);
}
function from_candid_opt_n17(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(value: {
    privacy_consents: Array<_PrivacyConsent>;
    schema: number;
    accounts: Array<_Account>;
    governor: Principal;
    exclusions: Array<_Exclusion>;
    external_bindings: Array<_ExternalSiteBinding>;
    families: Array<_FamilyLink>;
    challenges: Array<_LinkChallenge>;
    roles: Array<_RoleGrant>;
    next_challenge: bigint;
}): {
    privacy_consents: Array<PrivacyConsent>;
    schema: number;
    accounts: Array<Account>;
    governor: Principal;
    exclusions: Array<Exclusion>;
    external_bindings: Array<ExternalSiteBinding>;
    families: Array<FamilyLink>;
    challenges: Array<LinkChallenge>;
    roles: Array<RoleGrant>;
    next_challenge: bigint;
} {
    return {
        privacy_consents: value.privacy_consents,
        schema: value.schema,
        accounts: value.accounts,
        governor: value.governor,
        exclusions: from_candid_vec_n14(value.exclusions),
        external_bindings: value.external_bindings,
        families: value.families,
        challenges: value.challenges,
        roles: from_candid_vec_n18(value.roles),
        next_challenge: value.next_challenge
    };
}
function from_candid_record_n16(value: {
    account_id: string;
    club: string;
    team: [] | [string];
    site_id: [] | [string];
}): {
    account_id: string;
    club: string;
    team?: string;
    site_id?: string;
} {
    return {
        account_id: value.account_id,
        club: value.club,
        team: record_opt_to_undefined(from_candid_opt_n17(value.team)),
        site_id: record_opt_to_undefined(from_candid_opt_n17(value.site_id))
    };
}
function from_candid_record_n20(value: {
    account_id: string;
    club: [] | [string];
    role: string;
    team: [] | [string];
    site_id: [] | [string];
}): {
    account_id: string;
    club?: string;
    role: string;
    team?: string;
    site_id?: string;
} {
    return {
        account_id: value.account_id,
        club: record_opt_to_undefined(from_candid_opt_n17(value.club)),
        role: value.role,
        team: record_opt_to_undefined(from_candid_opt_n17(value.team)),
        site_id: record_opt_to_undefined(from_candid_opt_n17(value.site_id))
    };
}
function from_candid_variant_n11(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_State_n12(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _Account;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Account;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n22(value: {
    Ok: Array<_ExternalSiteBinding>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ExternalSiteBinding>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: boolean;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: boolean;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n26(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n28(value: {
    Ok: _PrivacyConsent;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PrivacyConsent;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n5(value: {
    Ok: _Access;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Access;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: _LinkChallenge;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LinkChallenge;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: _ExternalSiteBinding;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ExternalSiteBinding;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n14(value: Array<_Exclusion>): Array<Exclusion> {
    return value.map((x)=>from_candid_Exclusion_n15(x));
}
function from_candid_vec_n18(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n19(x));
}
function to_candid_opt_n3(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Identity_access {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Identity_access(actor);
}
