/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/placement_registry.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type result_site_availability = {
    __kind__: "Ok";
    Ok: site_availability;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_target = {
    __kind__: "Ok";
    Ok: target;
} | {
    __kind__: "Err";
    Err: string;
};
export interface site_availability {
    version: bigint;
    enabled: boolean;
    site_id: string;
}
export interface audit_event {
    id: bigint;
    action: string;
    at_ns: bigint;
    registry_version: bigint;
    detail: string;
    caller: Principal;
    club_id?: string;
}
export interface decision {
    writable: boolean;
    placement: placement;
    country_allowed: boolean;
    backend_enabled: boolean;
    reason: string;
}
export type result_opt_residency = {
    __kind__: "Ok";
    Ok: residency_assignment | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_residency = {
    __kind__: "Ok";
    Ok: residency_assignment;
} | {
    __kind__: "Err";
    Err: string;
};
export interface placement {
    country: string;
    version: bigint;
    state: placement_state;
    club_id: string;
    backend: backend;
}
export type result_audit_page = {
    __kind__: "Ok";
    Ok: audit_page;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_page = {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_decision = {
    __kind__: "Ok";
    Ok: decision | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_unit = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export type backend = {
    __kind__: "Icp";
    Icp: {
        canister: Principal;
    };
} | {
    __kind__: "Supabase";
    Supabase: {
        environment: string;
    };
};
export interface residency_assignment {
    version: bigint;
    target_alias: string;
    club_id: string;
    profile: string;
}
export interface init {
    governor: Principal;
}
export type result_residency_policy = {
    __kind__: "Ok";
    Ok: residency_policy;
} | {
    __kind__: "Err";
    Err: string;
};
export interface residency_policy {
    country: string;
    allowed_profiles: Array<string>;
    version: bigint;
}
export type result_policy = {
    __kind__: "Ok";
    Ok: policy;
} | {
    __kind__: "Err";
    Err: string;
};
export interface audit_page {
    next?: bigint;
    events: Array<audit_event>;
}
export type result_placement = {
    __kind__: "Ok";
    Ok: placement;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_opt_target = {
    __kind__: "Ok";
    Ok: target | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface page {
    placements: Array<placement>;
    next?: string;
    registry_version: bigint;
}
export type result_bool = {
    __kind__: "Ok";
    Ok: boolean;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_availability = {
    __kind__: "Ok";
    Ok: availability;
} | {
    __kind__: "Err";
    Err: string;
};
export type result_operator = {
    __kind__: "Ok";
    Ok: operator_record;
} | {
    __kind__: "Err";
    Err: string;
};
export interface operator_record {
    user: Principal;
    roles: Array<operator_role>;
}
export type result_opt_placement = {
    __kind__: "Ok";
    Ok: placement | null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface target {
    alias: string;
    deployment_class: string;
    healthy: boolean;
    version: bigint;
    enabled: boolean;
    site_id?: string;
    profile: string;
    backend: backend;
}
export interface availability {
    icp_enabled: boolean;
    version: bigint;
    supabase_enabled: boolean;
}
export interface policy {
    country: string;
    icp_enabled: boolean;
    version: bigint;
    supabase_enabled: boolean;
}
export enum backend_kind {
    Icp = "Icp",
    Supabase = "Supabase"
}
export enum operator_role {
    Auditor = "Auditor",
    PlacementAdmin = "PlacementAdmin",
    SecurityAdmin = "SecurityAdmin",
    InfrastructureAdmin = "InfrastructureAdmin",
    MigrationOperator = "MigrationOperator"
}
export enum placement_state {
    Blocked = "Blocked",
    Active = "Active",
    ReadOnly = "ReadOnly",
    MigrationRequired = "MigrationRequired"
}
export interface placement_registryInterface {
    get_availability(): Promise<availability>;
    get_decision(arg0: string): Promise<result_decision>;
    get_operator(arg0: Principal): Promise<result_operator>;
    get_placement(arg0: string): Promise<result_opt_placement>;
    get_policy(arg0: string): Promise<result_policy>;
    get_residency(arg0: string): Promise<result_opt_residency>;
    get_residency_policy(arg0: string): Promise<result_residency_policy>;
    get_site_availability(arg0: string): Promise<result_bool>;
    get_target(arg0: string): Promise<result_opt_target>;
    grant_operator(arg0: Principal, arg1: Array<operator_role>): Promise<result_operator>;
    list_audit(arg0: bigint | null, arg1: number): Promise<result_audit_page>;
    list_placements(arg0: string | null, arg1: number): Promise<result_page>;
    revoke_operator(arg0: Principal): Promise<result_unit>;
    set_availability(arg0: backend_kind, arg1: boolean, arg2: bigint): Promise<result_availability>;
    set_placement(arg0: string, arg1: string, arg2: backend, arg3: bigint): Promise<result_placement>;
    set_policy(arg0: string, arg1: boolean, arg2: boolean, arg3: bigint): Promise<result_policy>;
    set_residency(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<result_residency>;
    set_residency_policy(arg0: string, arg1: Array<string>, arg2: bigint): Promise<result_residency_policy>;
    set_site_availability(arg0: string, arg1: boolean, arg2: bigint): Promise<result_site_availability>;
    set_state(arg0: string, arg1: placement_state, arg2: bigint): Promise<result_placement>;
    set_target(arg0: string, arg1: string | null, arg2: string, arg3: backend, arg4: string, arg5: boolean, arg6: bigint): Promise<result_target>;
    set_target_health(arg0: string, arg1: boolean, arg2: bigint): Promise<result_target>;
    version(): Promise<bigint>;
}
import type { audit_event as _audit_event, audit_page as _audit_page, availability as _availability, backend as _backend, backend_kind as _backend_kind, decision as _decision, operator_record as _operator_record, operator_role as _operator_role, page as _page, placement as _placement, placement_state as _placement_state, policy as _policy, residency_assignment as _residency_assignment, residency_policy as _residency_policy, result_audit_page as _result_audit_page, result_availability as _result_availability, result_bool as _result_bool, result_decision as _result_decision, result_operator as _result_operator, result_opt_placement as _result_opt_placement, result_opt_residency as _result_opt_residency, result_opt_target as _result_opt_target, result_page as _result_page, result_placement as _result_placement, result_policy as _result_policy, result_residency as _result_residency, result_residency_policy as _result_residency_policy, result_site_availability as _result_site_availability, result_target as _result_target, result_unit as _result_unit, site_availability as _site_availability, target as _target } from "./declarations/placement_registry.did";
export class Placement_registry implements placement_registryInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_availability(): Promise<availability> {
        const result = await this.actor.get_availability();
        return result;
    }
    async get_decision(arg0: string): Promise<result_decision> {
        const result = await this.actor.get_decision(arg0);
        return from_candid_result_decision_n1(result);
    }
    async get_operator(arg0: Principal): Promise<result_operator> {
        const result = await this.actor.get_operator(arg0);
        return from_candid_result_operator_n12(result);
    }
    async get_placement(arg0: string): Promise<result_opt_placement> {
        const result = await this.actor.get_placement(arg0);
        return from_candid_result_opt_placement_n19(result);
    }
    async get_policy(arg0: string): Promise<result_policy> {
        const result = await this.actor.get_policy(arg0);
        return from_candid_result_policy_n22(result);
    }
    async get_residency(arg0: string): Promise<result_opt_residency> {
        const result = await this.actor.get_residency(arg0);
        return from_candid_result_opt_residency_n24(result);
    }
    async get_residency_policy(arg0: string): Promise<result_residency_policy> {
        const result = await this.actor.get_residency_policy(arg0);
        return from_candid_result_residency_policy_n27(result);
    }
    async get_site_availability(arg0: string): Promise<result_bool> {
        const result = await this.actor.get_site_availability(arg0);
        return from_candid_result_bool_n29(result);
    }
    async get_target(arg0: string): Promise<result_opt_target> {
        const result = await this.actor.get_target(arg0);
        return from_candid_result_opt_target_n31(result);
    }
    async grant_operator(arg0: Principal, arg1: Array<operator_role>): Promise<result_operator> {
        const result = await this.actor.grant_operator(arg0, to_candid_vec_n37(arg1));
        return from_candid_result_operator_n12(result);
    }
    async list_audit(arg0: bigint | null, arg1: number): Promise<result_audit_page> {
        const result = await this.actor.list_audit(to_candid_opt_n40(arg0), arg1);
        return from_candid_result_audit_page_n41(result);
    }
    async list_placements(arg0: string | null, arg1: number): Promise<result_page> {
        const result = await this.actor.list_placements(to_candid_opt_n49(arg0), arg1);
        return from_candid_result_page_n50(result);
    }
    async revoke_operator(arg0: Principal): Promise<result_unit> {
        const result = await this.actor.revoke_operator(arg0);
        return from_candid_result_unit_n55(result);
    }
    async set_availability(arg0: backend_kind, arg1: boolean, arg2: bigint): Promise<result_availability> {
        const result = await this.actor.set_availability(to_candid_backend_kind_n57(arg0), arg1, arg2);
        return from_candid_result_availability_n59(result);
    }
    async set_placement(arg0: string, arg1: string, arg2: backend, arg3: bigint): Promise<result_placement> {
        const result = await this.actor.set_placement(arg0, arg1, to_candid_backend_n61(arg2), arg3);
        return from_candid_result_placement_n63(result);
    }
    async set_policy(arg0: string, arg1: boolean, arg2: boolean, arg3: bigint): Promise<result_policy> {
        const result = await this.actor.set_policy(arg0, arg1, arg2, arg3);
        return from_candid_result_policy_n22(result);
    }
    async set_residency(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<result_residency> {
        const result = await this.actor.set_residency(arg0, arg1, arg2, arg3);
        return from_candid_result_residency_n65(result);
    }
    async set_residency_policy(arg0: string, arg1: Array<string>, arg2: bigint): Promise<result_residency_policy> {
        const result = await this.actor.set_residency_policy(arg0, arg1, arg2);
        return from_candid_result_residency_policy_n27(result);
    }
    async set_site_availability(arg0: string, arg1: boolean, arg2: bigint): Promise<result_site_availability> {
        const result = await this.actor.set_site_availability(arg0, arg1, arg2);
        return from_candid_result_site_availability_n67(result);
    }
    async set_state(arg0: string, arg1: placement_state, arg2: bigint): Promise<result_placement> {
        const result = await this.actor.set_state(arg0, to_candid_placement_state_n69(arg1), arg2);
        return from_candid_result_placement_n63(result);
    }
    async set_target(arg0: string, arg1: string | null, arg2: string, arg3: backend, arg4: string, arg5: boolean, arg6: bigint): Promise<result_target> {
        const result = await this.actor.set_target(arg0, to_candid_opt_n49(arg1), arg2, to_candid_backend_n61(arg3), arg4, arg5, arg6);
        return from_candid_result_target_n71(result);
    }
    async set_target_health(arg0: string, arg1: boolean, arg2: bigint): Promise<result_target> {
        const result = await this.actor.set_target_health(arg0, arg1, arg2);
        return from_candid_result_target_n71(result);
    }
    async version(): Promise<bigint> {
        const result = await this.actor.version();
        return result;
    }
}
function from_candid_audit_event_n47(value: _audit_event): audit_event {
    return from_candid_record_n48(value);
}
function from_candid_audit_page_n43(value: _audit_page): audit_page {
    return from_candid_record_n44(value);
}
function from_candid_backend_n10(value: _backend): backend {
    return from_candid_variant_n11(value);
}
function from_candid_decision_n4(value: _decision): decision {
    return from_candid_record_n5(value);
}
function from_candid_operator_record_n14(value: _operator_record): operator_record {
    return from_candid_record_n15(value);
}
function from_candid_operator_role_n17(value: _operator_role): operator_role {
    return from_candid_variant_n18(value);
}
function from_candid_opt_n21(value: [] | [_placement]): placement | null {
    return value.length === 0 ? null : from_candid_placement_n6(value[0]);
}
function from_candid_opt_n26(value: [] | [_residency_assignment]): residency_assignment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(value: [] | [_decision]): decision | null {
    return value.length === 0 ? null : from_candid_decision_n4(value[0]);
}
function from_candid_opt_n33(value: [] | [_target]): target | null {
    return value.length === 0 ? null : from_candid_target_n34(value[0]);
}
function from_candid_opt_n36(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_page_n52(value: _page): page {
    return from_candid_record_n53(value);
}
function from_candid_placement_n6(value: _placement): placement {
    return from_candid_record_n7(value);
}
function from_candid_placement_state_n8(value: _placement_state): placement_state {
    return from_candid_variant_n9(value);
}
function from_candid_record_n15(value: {
    user: Principal;
    roles: Array<_operator_role>;
}): {
    user: Principal;
    roles: Array<operator_role>;
} {
    return {
        user: value.user,
        roles: from_candid_vec_n16(value.roles)
    };
}
function from_candid_record_n35(value: {
    alias: string;
    deployment_class: string;
    healthy: boolean;
    version: bigint;
    enabled: boolean;
    site_id: [] | [string];
    profile: string;
    backend: _backend;
}): {
    alias: string;
    deployment_class: string;
    healthy: boolean;
    version: bigint;
    enabled: boolean;
    site_id?: string;
    profile: string;
    backend: backend;
} {
    return {
        alias: value.alias,
        deployment_class: value.deployment_class,
        healthy: value.healthy,
        version: value.version,
        enabled: value.enabled,
        site_id: record_opt_to_undefined(from_candid_opt_n36(value.site_id)),
        profile: value.profile,
        backend: from_candid_backend_n10(value.backend)
    };
}
function from_candid_record_n44(value: {
    next: [] | [bigint];
    events: Array<_audit_event>;
}): {
    next?: bigint;
    events: Array<audit_event>;
} {
    return {
        next: record_opt_to_undefined(from_candid_opt_n45(value.next)),
        events: from_candid_vec_n46(value.events)
    };
}
function from_candid_record_n48(value: {
    id: bigint;
    action: string;
    at_ns: bigint;
    registry_version: bigint;
    detail: string;
    caller: Principal;
    club_id: [] | [string];
}): {
    id: bigint;
    action: string;
    at_ns: bigint;
    registry_version: bigint;
    detail: string;
    caller: Principal;
    club_id?: string;
} {
    return {
        id: value.id,
        action: value.action,
        at_ns: value.at_ns,
        registry_version: value.registry_version,
        detail: value.detail,
        caller: value.caller,
        club_id: record_opt_to_undefined(from_candid_opt_n36(value.club_id))
    };
}
function from_candid_record_n5(value: {
    writable: boolean;
    placement: _placement;
    country_allowed: boolean;
    backend_enabled: boolean;
    reason: string;
}): {
    writable: boolean;
    placement: placement;
    country_allowed: boolean;
    backend_enabled: boolean;
    reason: string;
} {
    return {
        writable: value.writable,
        placement: from_candid_placement_n6(value.placement),
        country_allowed: value.country_allowed,
        backend_enabled: value.backend_enabled,
        reason: value.reason
    };
}
function from_candid_record_n53(value: {
    placements: Array<_placement>;
    next: [] | [string];
    registry_version: bigint;
}): {
    placements: Array<placement>;
    next?: string;
    registry_version: bigint;
} {
    return {
        placements: from_candid_vec_n54(value.placements),
        next: record_opt_to_undefined(from_candid_opt_n36(value.next)),
        registry_version: value.registry_version
    };
}
function from_candid_record_n7(value: {
    country: string;
    version: bigint;
    state: _placement_state;
    club_id: string;
    backend: _backend;
}): {
    country: string;
    version: bigint;
    state: placement_state;
    club_id: string;
    backend: backend;
} {
    return {
        country: value.country,
        version: value.version,
        state: from_candid_placement_state_n8(value.state),
        club_id: value.club_id,
        backend: from_candid_backend_n10(value.backend)
    };
}
function from_candid_result_audit_page_n41(value: _result_audit_page): result_audit_page {
    return from_candid_variant_n42(value);
}
function from_candid_result_availability_n59(value: _result_availability): result_availability {
    return from_candid_variant_n60(value);
}
function from_candid_result_bool_n29(value: _result_bool): result_bool {
    return from_candid_variant_n30(value);
}
function from_candid_result_decision_n1(value: _result_decision): result_decision {
    return from_candid_variant_n2(value);
}
function from_candid_result_operator_n12(value: _result_operator): result_operator {
    return from_candid_variant_n13(value);
}
function from_candid_result_opt_placement_n19(value: _result_opt_placement): result_opt_placement {
    return from_candid_variant_n20(value);
}
function from_candid_result_opt_residency_n24(value: _result_opt_residency): result_opt_residency {
    return from_candid_variant_n25(value);
}
function from_candid_result_opt_target_n31(value: _result_opt_target): result_opt_target {
    return from_candid_variant_n32(value);
}
function from_candid_result_page_n50(value: _result_page): result_page {
    return from_candid_variant_n51(value);
}
function from_candid_result_placement_n63(value: _result_placement): result_placement {
    return from_candid_variant_n64(value);
}
function from_candid_result_policy_n22(value: _result_policy): result_policy {
    return from_candid_variant_n23(value);
}
function from_candid_result_residency_n65(value: _result_residency): result_residency {
    return from_candid_variant_n66(value);
}
function from_candid_result_residency_policy_n27(value: _result_residency_policy): result_residency_policy {
    return from_candid_variant_n28(value);
}
function from_candid_result_site_availability_n67(value: _result_site_availability): result_site_availability {
    return from_candid_variant_n68(value);
}
function from_candid_result_target_n71(value: _result_target): result_target {
    return from_candid_variant_n72(value);
}
function from_candid_result_unit_n55(value: _result_unit): result_unit {
    return from_candid_variant_n56(value);
}
function from_candid_target_n34(value: _target): target {
    return from_candid_record_n35(value);
}
function from_candid_variant_n11(value: {
    Icp: {
        canister: Principal;
    };
} | {
    Supabase: {
        environment: string;
    };
}): {
    __kind__: "Icp";
    Icp: {
        canister: Principal;
    };
} | {
    __kind__: "Supabase";
    Supabase: {
        environment: string;
    };
} {
    return "Icp" in value ? {
        __kind__: "Icp",
        Icp: value.Icp
    } : "Supabase" in value ? {
        __kind__: "Supabase",
        Supabase: value.Supabase
    } : value;
}
function from_candid_variant_n13(value: {
    Ok: _operator_record;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: operator_record;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_operator_record_n14(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n18(value: {
    Auditor: null;
} | {
    PlacementAdmin: null;
} | {
    SecurityAdmin: null;
} | {
    InfrastructureAdmin: null;
} | {
    MigrationOperator: null;
}): operator_role {
    return "Auditor" in value ? operator_role.Auditor : "PlacementAdmin" in value ? operator_role.PlacementAdmin : "SecurityAdmin" in value ? operator_role.SecurityAdmin : "InfrastructureAdmin" in value ? operator_role.InfrastructureAdmin : "MigrationOperator" in value ? operator_role.MigrationOperator : value;
}
function from_candid_variant_n2(value: {
    Ok: [] | [_decision];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: decision | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: [] | [_placement];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: placement | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n21(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n23(value: {
    Ok: _policy;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: policy;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n25(value: {
    Ok: [] | [_residency_assignment];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: residency_assignment | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n26(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n28(value: {
    Ok: _residency_policy;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: residency_policy;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n30(value: {
    Ok: boolean;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: boolean;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n32(value: {
    Ok: [] | [_target];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: target | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n33(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n42(value: {
    Ok: _audit_page;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: audit_page;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_audit_page_n43(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n51(value: {
    Ok: _page;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: page;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_page_n52(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n56(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n60(value: {
    Ok: _availability;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: availability;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n64(value: {
    Ok: _placement;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: placement;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_placement_n6(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n66(value: {
    Ok: _residency_assignment;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: residency_assignment;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n68(value: {
    Ok: _site_availability;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: site_availability;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n72(value: {
    Ok: _target;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: target;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_target_n34(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Blocked: null;
} | {
    Active: null;
} | {
    ReadOnly: null;
} | {
    MigrationRequired: null;
}): placement_state {
    return "Blocked" in value ? placement_state.Blocked : "Active" in value ? placement_state.Active : "ReadOnly" in value ? placement_state.ReadOnly : "MigrationRequired" in value ? placement_state.MigrationRequired : value;
}
function from_candid_vec_n16(value: Array<_operator_role>): Array<operator_role> {
    return value.map((x)=>from_candid_operator_role_n17(x));
}
function from_candid_vec_n46(value: Array<_audit_event>): Array<audit_event> {
    return value.map((x)=>from_candid_audit_event_n47(x));
}
function from_candid_vec_n54(value: Array<_placement>): Array<placement> {
    return value.map((x)=>from_candid_placement_n6(x));
}
function to_candid_backend_kind_n57(value: backend_kind): _backend_kind {
    return to_candid_variant_n58(value);
}
function to_candid_backend_n61(value: backend): _backend {
    return to_candid_variant_n62(value);
}
function to_candid_operator_role_n38(value: operator_role): _operator_role {
    return to_candid_variant_n39(value);
}
function to_candid_opt_n40(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n49(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_placement_state_n69(value: placement_state): _placement_state {
    return to_candid_variant_n70(value);
}
function to_candid_variant_n39(value: operator_role): {
    Auditor: null;
} | {
    PlacementAdmin: null;
} | {
    SecurityAdmin: null;
} | {
    InfrastructureAdmin: null;
} | {
    MigrationOperator: null;
} {
    return value == operator_role.Auditor ? {
        Auditor: null
    } : value == operator_role.PlacementAdmin ? {
        PlacementAdmin: null
    } : value == operator_role.SecurityAdmin ? {
        SecurityAdmin: null
    } : value == operator_role.InfrastructureAdmin ? {
        InfrastructureAdmin: null
    } : value == operator_role.MigrationOperator ? {
        MigrationOperator: null
    } : value;
}
function to_candid_variant_n58(value: backend_kind): {
    Icp: null;
} | {
    Supabase: null;
} {
    return value == backend_kind.Icp ? {
        Icp: null
    } : value == backend_kind.Supabase ? {
        Supabase: null
    } : value;
}
function to_candid_variant_n62(value: {
    __kind__: "Icp";
    Icp: {
        canister: Principal;
    };
} | {
    __kind__: "Supabase";
    Supabase: {
        environment: string;
    };
}): {
    Icp: {
        canister: Principal;
    };
} | {
    Supabase: {
        environment: string;
    };
} {
    return value.__kind__ === "Icp" ? {
        Icp: value.Icp
    } : value.__kind__ === "Supabase" ? {
        Supabase: value.Supabase
    } : value;
}
function to_candid_variant_n70(value: placement_state): {
    Blocked: null;
} | {
    Active: null;
} | {
    ReadOnly: null;
} | {
    MigrationRequired: null;
} {
    return value == placement_state.Blocked ? {
        Blocked: null
    } : value == placement_state.Active ? {
        Active: null
    } : value == placement_state.ReadOnly ? {
        ReadOnly: null
    } : value == placement_state.MigrationRequired ? {
        MigrationRequired: null
    } : value;
}
function to_candid_vec_n37(value: Array<operator_role>): Array<_operator_role> {
    return value.map((x)=>to_candid_operator_role_n38(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Placement_registry {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Placement_registry(actor);
}
