/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const WorkloadIdentityFilter = IDL.Record({
    'opt_from_ts' : IDL.Opt(IDL.Nat64),
    'opt_to_ts' : IDL.Opt(IDL.Nat64),
    'opt_scope' : IDL.Opt(IDL.Text),
    'opt_principal' : IDL.Opt(IDL.Principal),
  });
  const SecretAccessAudit = IDL.Record({
    'workload_name' : IDL.Text,
    'requesting_principal' : IDL.Principal,
    'secret_scope' : IDL.Text,
    'approved' : IDL.Bool,
    'nonce' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'denial_reason' : IDL.Opt(IDL.Text),
  });
  const AuditSummary = IDL.Record({
    'total_accesses' : IDL.Nat64,
    'denied' : IDL.Nat64,
    'approved' : IDL.Nat64,
  });
  const WorkloadIdentity = IDL.Record({
    'status' : IDL.Variant({
      'Active' : IDL.Null,
      'Suspended' : IDL.Null,
      'Revoked' : IDL.Null,
    }),
    'workload_name' : IDL.Text,
    'workload_principal' : IDL.Principal,
    'allowed_scopes' : IDL.Vec(IDL.Text),
    'last_used' : IDL.Nat64,
    'registered_at' : IDL.Nat64,
  });
  const SecretAccessResult = IDL.Record({
    'approved' : IDL.Bool,
    'timestamp' : IDL.Nat64,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'audit_secret_access' : IDL.Func(
        [WorkloadIdentityFilter],
        [IDL.Vec(SecretAccessAudit)],
        ['query'],
      ),
    'get_audit_summary' : IDL.Func([], [AuditSummary], ['query']),
    'get_workload' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : WorkloadIdentity, 'Err' : IDL.Text })],
        ['query'],
      ),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_workloads' : IDL.Func([], [IDL.Vec(WorkloadIdentity)], ['query']),
    'register_workload' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : WorkloadIdentity, 'Err' : IDL.Text })],
        [],
      ),
    'revoke_workload' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'update_workload_scopes' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : WorkloadIdentity, 'Err' : IDL.Text })],
        [],
      ),
    'verify_secret_access' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [SecretAccessResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };