/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditSummary {
  'total_accesses' : bigint,
  'denied' : bigint,
  'approved' : bigint,
}
export interface SecretAccessAudit {
  'workload_name' : string,
  'requesting_principal' : Principal,
  'secret_scope' : string,
  'approved' : boolean,
  'nonce' : string,
  'timestamp' : bigint,
  'denial_reason' : [] | [string],
}
export interface SecretAccessResult {
  'approved' : boolean,
  'timestamp' : bigint,
  'reason' : string,
}
export interface WorkloadIdentity {
  'status' : { 'Active' : null } |
    { 'Suspended' : null } |
    { 'Revoked' : null },
  'workload_name' : string,
  'workload_principal' : Principal,
  'allowed_scopes' : Array<string>,
  'last_used' : bigint,
  'registered_at' : bigint,
}
export interface WorkloadIdentityFilter {
  'opt_from_ts' : [] | [bigint],
  'opt_to_ts' : [] | [bigint],
  'opt_scope' : [] | [string],
  'opt_principal' : [] | [Principal],
}
/**
 * / Secret Workload Identity Canister
 * / Manages workload identity registration and vault secret access control
 * / Enforces least-privilege access to vault secrets by canister principal
 */
export interface _SERVICE {
  'audit_secret_access' : ActorMethod<
    [WorkloadIdentityFilter],
    Array<SecretAccessAudit>
  >,
  'get_audit_summary' : ActorMethod<[], AuditSummary>,
  'get_workload' : ActorMethod<
    [Principal],
    { 'Ok' : WorkloadIdentity } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'list_workloads' : ActorMethod<[], Array<WorkloadIdentity>>,
  'register_workload' : ActorMethod<
    [Principal, string, Array<string>],
    { 'Ok' : WorkloadIdentity } |
      { 'Err' : string }
  >,
  'revoke_workload' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'update_workload_scopes' : ActorMethod<
    [Principal, Array<string>],
    { 'Ok' : WorkloadIdentity } |
      { 'Err' : string }
  >,
  'verify_secret_access' : ActorMethod<
    [Principal, string, string],
    SecretAccessResult
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];