/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/pii_access_control.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface DecryptedPii {
    pii_id: string;
    field_id: string;
    plaintext: Uint8Array;
}
export interface AuditRecord {
    allowed: boolean;
    requesting_principal: Principal;
    pii_id: string;
    operation: string;
    timestamp: bigint;
    field_id: string;
    purpose: string;
}
export interface PiiDeleteResult {
    shredded_at: bigint;
    key_destroyed: boolean;
}
export interface EncryptedPii {
    master_key_id: string;
    ciphertext: Uint8Array;
    pii_id: string;
    nonce: Uint8Array;
    field_id: string;
}
export interface KeyRotationResult {
    new_key_id: string;
    old_key_id: string;
    rotated_at: bigint;
}
export interface KeyMetadata {
    status: Variant_Active_Shredded_RotationPending_Revoked;
    key_id: string;
    created_at: bigint;
    rotation_due_at: bigint;
}
export interface AuditFilter {
    opt_from_ts?: bigint;
    opt_to_ts?: bigint;
    opt_pii_id?: string;
    opt_principal?: Principal;
    opt_field_id?: string;
}
export enum Variant_Active_Shredded_RotationPending_Revoked {
    Active = "Active",
    Shredded = "Shredded",
    RotationPending = "RotationPending",
    Revoked = "Revoked"
}
/**
 * / PII Access Control Canister
 * / Encrypts and mediates access to personally identifiable information (PII)
 * / Enforces field-level access policies and maintains audit trail
 * /
 * / Production note: This uses synthetic encryption for lab testing.
 * / Production deployment should integrate with:
 * / - Hardware Security Module (HSM) or KMS for master key storage
 * / - vetKeys for child media key derivation
 * / - External vault for secret workload identity
 */
export interface pii_access_controlInterface {
    audit_access(filter: AuditFilter): Promise<Array<AuditRecord>>;
    delete_pii(pii_id: string, field_id: string): Promise<{
        __kind__: "Ok";
        Ok: PiiDeleteResult;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    derive_media_key(child_id: string, authorizer: Principal, purpose: string, expiry_seconds: bigint): Promise<{
        __kind__: "Ok";
        Ok: Uint8Array;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    emergency_shutdown(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_decrypted_pii(pii_id: string, field_id: string, operation: string, purpose: string): Promise<{
        __kind__: "Ok";
        Ok: DecryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_encrypted_pii(pii_id: string, field_id: string): Promise<{
        __kind__: "Ok";
        Ok: EncryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_key_metadata(): Promise<Array<KeyMetadata>>;
    initialize_master_key(initial_key_id: string): Promise<{
        __kind__: "Ok";
        Ok: string;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    register_pii(pii_id: string, field_id: string, plaintext: Uint8Array, domain_owner: Principal): Promise<{
        __kind__: "Ok";
        Ok: EncryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    rotate_key(new_key_id: string): Promise<{
        __kind__: "Ok";
        Ok: KeyRotationResult;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
import type { AuditFilter as _AuditFilter, DecryptedPii as _DecryptedPii, EncryptedPii as _EncryptedPii, KeyMetadata as _KeyMetadata, KeyRotationResult as _KeyRotationResult, PiiDeleteResult as _PiiDeleteResult } from "./declarations/pii_access_control.did";
export class Pii_access_control implements pii_access_controlInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async audit_access(arg0: AuditFilter): Promise<Array<AuditRecord>> {
        const result = await this.actor.audit_access(to_candid_AuditFilter_n1(arg0));
        return result;
    }
    async delete_pii(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: PiiDeleteResult;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_pii(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async derive_media_key(arg0: string, arg1: Principal, arg2: string, arg3: bigint): Promise<{
        __kind__: "Ok";
        Ok: Uint8Array;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.derive_media_key(arg0, arg1, arg2, arg3);
        return from_candid_variant_n4(result);
    }
    async emergency_shutdown(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.emergency_shutdown();
        return from_candid_variant_n5(result);
    }
    async get_decrypted_pii(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: DecryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_decrypted_pii(arg0, arg1, arg2, arg3);
        return from_candid_variant_n6(result);
    }
    async get_encrypted_pii(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: EncryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_encrypted_pii(arg0, arg1);
        return from_candid_variant_n7(result);
    }
    async get_key_metadata(): Promise<Array<KeyMetadata>> {
        const result = await this.actor.get_key_metadata();
        return from_candid_vec_n8(result);
    }
    async initialize_master_key(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: string;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize_master_key(arg0);
        return from_candid_variant_n12(result);
    }
    async register_pii(arg0: string, arg1: string, arg2: Uint8Array, arg3: Principal): Promise<{
        __kind__: "Ok";
        Ok: EncryptedPii;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.register_pii(arg0, arg1, arg2, arg3);
        return from_candid_variant_n7(result);
    }
    async rotate_key(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: KeyRotationResult;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.rotate_key(arg0);
        return from_candid_variant_n13(result);
    }
}
function from_candid_KeyMetadata_n9(value: _KeyMetadata): KeyMetadata {
    return from_candid_record_n10(value);
}
function from_candid_record_n10(value: {
    status: {
        Active: null;
    } | {
        Shredded: null;
    } | {
        RotationPending: null;
    } | {
        Revoked: null;
    };
    key_id: string;
    created_at: bigint;
    rotation_due_at: bigint;
}): {
    status: Variant_Active_Shredded_RotationPending_Revoked;
    key_id: string;
    created_at: bigint;
    rotation_due_at: bigint;
} {
    return {
        status: from_candid_variant_n11(value.status),
        key_id: value.key_id,
        created_at: value.created_at,
        rotation_due_at: value.rotation_due_at
    };
}
function from_candid_variant_n11(value: {
    Active: null;
} | {
    Shredded: null;
} | {
    RotationPending: null;
} | {
    Revoked: null;
}): Variant_Active_Shredded_RotationPending_Revoked {
    return "Active" in value ? Variant_Active_Shredded_RotationPending_Revoked.Active : "Shredded" in value ? Variant_Active_Shredded_RotationPending_Revoked.Shredded : "RotationPending" in value ? Variant_Active_Shredded_RotationPending_Revoked.RotationPending : "Revoked" in value ? Variant_Active_Shredded_RotationPending_Revoked.Revoked : value;
}
function from_candid_variant_n12(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n13(value: {
    Ok: _KeyRotationResult;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: KeyRotationResult;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n3(value: {
    Ok: _PiiDeleteResult;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PiiDeleteResult;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: Uint8Array;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Uint8Array;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n5(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _DecryptedPii;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: DecryptedPii;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: _EncryptedPii;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EncryptedPii;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n8(value: Array<_KeyMetadata>): Array<KeyMetadata> {
    return value.map((x)=>from_candid_KeyMetadata_n9(x));
}
function to_candid_AuditFilter_n1(value: AuditFilter): _AuditFilter {
    return to_candid_record_n2(value);
}
function to_candid_record_n2(value: {
    opt_from_ts?: bigint;
    opt_to_ts?: bigint;
    opt_pii_id?: string;
    opt_principal?: Principal;
    opt_field_id?: string;
}): {
    opt_from_ts: [] | [bigint];
    opt_to_ts: [] | [bigint];
    opt_pii_id: [] | [string];
    opt_principal: [] | [Principal];
    opt_field_id: [] | [string];
} {
    return {
        opt_from_ts: value.opt_from_ts ? candid_some(value.opt_from_ts) : candid_none(),
        opt_to_ts: value.opt_to_ts ? candid_some(value.opt_to_ts) : candid_none(),
        opt_pii_id: value.opt_pii_id ? candid_some(value.opt_pii_id) : candid_none(),
        opt_principal: value.opt_principal ? candid_some(value.opt_principal) : candid_none(),
        opt_field_id: value.opt_field_id ? candid_some(value.opt_field_id) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Pii_access_control {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Pii_access_control(actor);
}
