/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/messaging_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: Receipt;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_6 = {
    __kind__: "Ok";
    Ok: Message;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Init {
    governor: Principal;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: Unread;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_1 = {
    __kind__: "Ok";
    Ok: Message;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_4 = {
    __kind__: "Ok";
    Ok: MessagePage;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Receipt {
    conversation_id: string;
    read: boolean;
    user: Principal;
    message_id: string;
}
export interface Unread {
    conversation_id: string;
    count: bigint;
    user: Principal;
    last_read_sequence: bigint;
}
export type Result = {
    __kind__: "Ok";
    Ok: Conversation;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
};
export interface Message {
    id: string;
    conversation_id: string;
    body: string;
    sender: Principal;
    sequence: bigint;
    idempotency_key: string;
}
export interface MessagePage {
    messages: Array<Message>;
    latest_sequence: bigint;
    next_sequence?: bigint;
}
export interface State {
    messages: Array<Message>;
    schema: number;
    unread: Array<Unread>;
    governor: Principal;
    conversations: Array<Conversation>;
    receipts: Array<Receipt>;
}
export interface Conversation {
    id: string;
    participants: Array<Principal>;
    team_id?: string;
    next_sequence: bigint;
    club_id: string;
}
export interface messaging_domainInterface {
    create_conversation(arg0: string, arg1: string | null, arg2: Array<Principal>): Promise<Result>;
    delete_message(arg0: string): Promise<Result_6>;
    export_state(): Promise<Result_3>;
    list_messages(arg0: string, arg1: bigint | null): Promise<Array<Message>>;
    list_messages_page(arg0: string, arg1: bigint | null, arg2: number): Promise<Result_4>;
    mark_read(arg0: string, arg1: string): Promise<Result_2>;
    send_message(arg0: string, arg1: string, arg2: string): Promise<Result_1>;
    unread_count(arg0: string): Promise<Result_5>;
}
import type { Conversation as _Conversation, Message as _Message, MessagePage as _MessagePage, Receipt as _Receipt, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, State as _State, Unread as _Unread } from "./declarations/messaging_domain.did";
export class Messaging_domain implements messaging_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async create_conversation(arg0: string, arg1: string | null, arg2: Array<Principal>): Promise<Result> {
        const result = await this.actor.create_conversation(arg0, to_candid_opt_n1(arg1), arg2);
        return from_candid_Result_n2(result);
    }
    async delete_message(arg0: string): Promise<Result_6> {
        const result = await this.actor.delete_message(arg0);
        return from_candid_Result_6_n7(result);
    }
    async export_state(): Promise<Result_3> {
        const result = await this.actor.export_state();
        return from_candid_Result_3_n9(result);
    }
    async list_messages(arg0: string, arg1: bigint | null): Promise<Array<Message>> {
        const result = await this.actor.list_messages(arg0, to_candid_opt_n14(arg1));
        return result;
    }
    async list_messages_page(arg0: string, arg1: bigint | null, arg2: number): Promise<Result_4> {
        const result = await this.actor.list_messages_page(arg0, to_candid_opt_n14(arg1), arg2);
        return from_candid_Result_4_n15(result);
    }
    async mark_read(arg0: string, arg1: string): Promise<Result_2> {
        const result = await this.actor.mark_read(arg0, arg1);
        return from_candid_Result_2_n20(result);
    }
    async send_message(arg0: string, arg1: string, arg2: string): Promise<Result_1> {
        const result = await this.actor.send_message(arg0, arg1, arg2);
        return from_candid_Result_1_n22(result);
    }
    async unread_count(arg0: string): Promise<Result_5> {
        const result = await this.actor.unread_count(arg0);
        return from_candid_Result_5_n23(result);
    }
}
function from_candid_Conversation_n4(value: _Conversation): Conversation {
    return from_candid_record_n5(value);
}
function from_candid_MessagePage_n17(value: _MessagePage): MessagePage {
    return from_candid_record_n18(value);
}
function from_candid_Result_1_n22(value: _Result_1): Result_1 {
    return from_candid_variant_n8(value);
}
function from_candid_Result_2_n20(value: _Result_2): Result_2 {
    return from_candid_variant_n21(value);
}
function from_candid_Result_3_n9(value: _Result_3): Result_3 {
    return from_candid_variant_n10(value);
}
function from_candid_Result_4_n15(value: _Result_4): Result_4 {
    return from_candid_variant_n16(value);
}
function from_candid_Result_5_n23(value: _Result_5): Result_5 {
    return from_candid_variant_n24(value);
}
function from_candid_Result_6_n7(value: _Result_6): Result_6 {
    return from_candid_variant_n8(value);
}
function from_candid_Result_n2(value: _Result): Result {
    return from_candid_variant_n3(value);
}
function from_candid_State_n11(value: _State): State {
    return from_candid_record_n12(value);
}
function from_candid_opt_n19(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(value: {
    messages: Array<_Message>;
    schema: number;
    unread: Array<_Unread>;
    governor: Principal;
    conversations: Array<_Conversation>;
    receipts: Array<_Receipt>;
}): {
    messages: Array<Message>;
    schema: number;
    unread: Array<Unread>;
    governor: Principal;
    conversations: Array<Conversation>;
    receipts: Array<Receipt>;
} {
    return {
        messages: value.messages,
        schema: value.schema,
        unread: value.unread,
        governor: value.governor,
        conversations: from_candid_vec_n13(value.conversations),
        receipts: value.receipts
    };
}
function from_candid_record_n18(value: {
    messages: Array<_Message>;
    latest_sequence: bigint;
    next_sequence: [] | [bigint];
}): {
    messages: Array<Message>;
    latest_sequence: bigint;
    next_sequence?: bigint;
} {
    return {
        messages: value.messages,
        latest_sequence: value.latest_sequence,
        next_sequence: record_opt_to_undefined(from_candid_opt_n19(value.next_sequence))
    };
}
function from_candid_record_n5(value: {
    id: string;
    participants: Array<Principal>;
    team_id: [] | [string];
    next_sequence: bigint;
    club_id: string;
}): {
    id: string;
    participants: Array<Principal>;
    team_id?: string;
    next_sequence: bigint;
    club_id: string;
} {
    return {
        id: value.id,
        participants: value.participants,
        team_id: record_opt_to_undefined(from_candid_opt_n6(value.team_id)),
        next_sequence: value.next_sequence,
        club_id: value.club_id
    };
}
function from_candid_variant_n10(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_State_n11(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: _MessagePage;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: MessagePage;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_MessagePage_n17(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: _Receipt;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Receipt;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: _Unread;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Unread;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n3(value: {
    Ok: _Conversation;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Conversation;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Conversation_n4(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: _Message;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Message;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n13(value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n4(x));
}
function to_candid_opt_n1(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Messaging_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Messaging_domain(actor);
}
