/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Init = {};
export interface Migration {
  'id' : bigint,
  'destination' : Principal,
  'domain' : string,
  'source' : Principal,
  'checksum' : string,
  'schemaVersion' : bigint,
  'phase' : Phase,
  'recordCount' : bigint,
}
export type Phase = { 'exported' : null } |
  { 'verified' : null } |
  { 'aborted' : null } |
  { 'imported' : null } |
  { 'started' : null } |
  { 'committed' : null };
export interface _SERVICE {
  'abort' : ActorMethod<[bigint], Migration>,
  'begin' : ActorMethod<
    [string, Principal, Principal, bigint, string],
    Migration
  >,
  'commit' : ActorMethod<[bigint], Migration>,
  'initialize' : ActorMethod<[], undefined>,
  'markExported' : ActorMethod<[bigint, bigint, string], Migration>,
  'markImported' : ActorMethod<[bigint, bigint, string], Migration>,
  'status' : ActorMethod<[], [[] | [Migration], Array<Migration>]>,
  'verify' : ActorMethod<[bigint, bigint, string], Migration>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];