/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : string,
  'storage_path' : string,
  'retention_until_ms' : bigint,
  'deleted' : boolean,
  'owner' : Principal,
  'kind' : string,
  'mime' : string,
  'encrypted' : boolean,
  'content_length' : bigint,
  'checksum' : string,
  'child_sensitive' : boolean,
  'visibility' : string,
  'club_id' : string,
  'expires_at_ms' : bigint,
}
export interface Capability {
  'action' : string,
  'owner' : Principal,
  'allowed' : boolean,
  'asset_id' : string,
  'purpose' : string,
  'expires_at_ms' : bigint,
}
export interface Comment {
  'id' : string,
  'deleted' : boolean,
  'body' : string,
  'author' : Principal,
  'created_at_ms' : bigint,
  'asset_id' : string,
}
export interface Init { 'governor' : Principal }
export interface Reaction {
  'kind' : string,
  'user' : Principal,
  'created_at_ms' : bigint,
  'asset_id' : string,
}
export type Result = { 'Ok' : Asset } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Capability } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : State } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : Asset } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : Reaction } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Comment } |
  { 'Err' : string };
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : [] | [string],
}
export interface State {
  'capabilities' : Array<Capability>,
  'schema' : number,
  'assets' : Array<Asset>,
  'governor' : Principal,
  'comments' : Array<Comment>,
  'reactions' : Array<Reaction>,
  'roles' : Array<RoleGrant>,
}
export interface _SERVICE {
  'add_comment' : ActorMethod<[string, string, bigint], Result_6>,
  'add_reaction' : ActorMethod<[string, string, bigint], Result_5>,
  'delete_asset' : ActorMethod<[string], Result_3>,
  'delete_comment' : ActorMethod<[string], Result_6>,
  'export_state' : ActorMethod<[], Result_2>,
  'get_asset' : ActorMethod<[string], [] | [Asset]>,
  'grant_role' : ActorMethod<
    [Principal, string, [] | [string], [] | [string]],
    Result_4
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'issue_capability' : ActorMethod<[string, string, string, bigint], Result_1>,
  'list_assets' : ActorMethod<[string], Array<Asset>>,
  'list_comments' : ActorMethod<[string], Array<Comment>>,
  'list_reactions' : ActorMethod<[string], Array<Reaction>>,
  'register_asset' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    Result
  >,
  'remove_reaction' : ActorMethod<[string], Result_4>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];