/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'storage_path' : IDL.Text,
    'retention_until_ms' : IDL.Nat64,
    'deleted' : IDL.Bool,
    'owner' : IDL.Principal,
    'kind' : IDL.Text,
    'mime' : IDL.Text,
    'encrypted' : IDL.Bool,
    'content_length' : IDL.Nat64,
    'checksum' : IDL.Text,
    'child_sensitive' : IDL.Bool,
    'visibility' : IDL.Text,
    'club_id' : IDL.Text,
    'expires_at_ms' : IDL.Nat64,
  });
  const Result_3 = IDL.Variant({ 'Ok' : Asset, 'Err' : IDL.Text });
  const Capability = IDL.Record({
    'action' : IDL.Text,
    'owner' : IDL.Principal,
    'allowed' : IDL.Bool,
    'asset_id' : IDL.Text,
    'purpose' : IDL.Text,
    'expires_at_ms' : IDL.Nat64,
  });
  const State = IDL.Record({
    'capabilities' : IDL.Vec(Capability),
    'schema' : IDL.Nat32,
    'assets' : IDL.Vec(Asset),
    'governor' : IDL.Principal,
  });
  const Result_2 = IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'Ok' : Capability, 'Err' : IDL.Text });
  const Result = IDL.Variant({ 'Ok' : Asset, 'Err' : IDL.Text });
  
  return IDL.Service({
    'delete_asset' : IDL.Func([IDL.Text], [Result_3], []),
    'export_state' : IDL.Func([], [Result_2], ['query']),
    'get_asset' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
    'issue_capability' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64],
        [Result_1],
        [],
      ),
    'register_asset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat64],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [Init];
};