/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const AuditFilter = IDL.Record({
    'opt_from_ts' : IDL.Opt(IDL.Nat64),
    'opt_to_ts' : IDL.Opt(IDL.Nat64),
    'opt_pii_id' : IDL.Opt(IDL.Text),
    'opt_principal' : IDL.Opt(IDL.Principal),
    'opt_field_id' : IDL.Opt(IDL.Text),
  });
  const AuditRecord = IDL.Record({
    'allowed' : IDL.Bool,
    'requesting_principal' : IDL.Principal,
    'pii_id' : IDL.Text,
    'operation' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'field_id' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const PiiDeleteResult = IDL.Record({
    'shredded_at' : IDL.Nat64,
    'key_destroyed' : IDL.Bool,
  });
  const DecryptedPii = IDL.Record({
    'pii_id' : IDL.Text,
    'field_id' : IDL.Text,
    'plaintext' : IDL.Vec(IDL.Nat8),
  });
  const EncryptedPii = IDL.Record({
    'master_key_id' : IDL.Text,
    'ciphertext' : IDL.Vec(IDL.Nat8),
    'pii_id' : IDL.Text,
    'nonce' : IDL.Vec(IDL.Nat8),
    'field_id' : IDL.Text,
  });
  const KeyMetadata = IDL.Record({
    'status' : IDL.Variant({
      'Active' : IDL.Null,
      'Shredded' : IDL.Null,
      'RotationPending' : IDL.Null,
      'Revoked' : IDL.Null,
    }),
    'key_id' : IDL.Text,
    'created_at' : IDL.Nat64,
    'rotation_due_at' : IDL.Nat64,
  });
  const KeyRotationResult = IDL.Record({
    'new_key_id' : IDL.Text,
    'old_key_id' : IDL.Text,
    'rotated_at' : IDL.Nat64,
  });
  
  return IDL.Service({
    'audit_access' : IDL.Func([AuditFilter], [IDL.Vec(AuditRecord)], ['query']),
    'delete_pii' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : PiiDeleteResult, 'Err' : IDL.Text })],
        [],
      ),
    'derive_media_key' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, IDL.Nat64],
        [IDL.Variant({ 'Ok' : IDL.Vec(IDL.Nat8), 'Err' : IDL.Text })],
        [],
      ),
    'emergency_shutdown' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'get_decrypted_pii' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : DecryptedPii, 'Err' : IDL.Text })],
        [],
      ),
    'get_encrypted_pii' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : EncryptedPii, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_key_metadata' : IDL.Func([], [IDL.Vec(KeyMetadata)], ['query']),
    'initialize_master_key' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text })],
        [],
      ),
    'register_pii' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Principal],
        [IDL.Variant({ 'Ok' : EncryptedPii, 'Err' : IDL.Text })],
        [],
      ),
    'rotate_key' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : KeyRotationResult, 'Err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };