/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface job {
  'id' : string,
  'last_error' : [] | [string],
  'status' : status,
  'run_at_ms' : bigint,
  'attempts' : number,
  'scope' : string,
  'callback' : [] | [Principal],
  'lease_until_ms' : [] | [bigint],
  'idempotency_key' : string,
}
export interface page { 'jobs' : Array<job>, 'next' : [] | [string] }
export interface queue_state {
  'armed' : boolean,
  'next_run_at_ms' : [] | [bigint],
}
export interface reconciliation {
  'incoming_jobs' : number,
  'matching_jobs' : number,
  'local_jobs' : number,
}
export type result_job = { 'Ok' : job } |
  { 'Err' : string };
export type result_jobs = { 'Ok' : Array<job> } |
  { 'Err' : string };
export type result_nat16 = { 'Ok' : number } |
  { 'Err' : string };
export type result_page = { 'Ok' : page } |
  { 'Err' : string };
export type result_reconciliation = { 'Ok' : reconciliation } |
  { 'Err' : string };
export type result_snapshot = { 'Ok' : snapshot } |
  { 'Err' : string };
export type result_state = { 'Ok' : queue_state } |
  { 'Err' : string };
export type result_unit = { 'Ok' : null } |
  { 'Err' : string };
export interface snapshot { 'jobs' : Array<job>, 'state' : queue_state }
export type status = { 'Failed' : null } |
  { 'Processing' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'arm' : ActorMethod<[bigint], result_state>,
  'claim' : ActorMethod<[bigint, number], result_jobs>,
  'claim_with_lease' : ActorMethod<[bigint, number, bigint], result_jobs>,
  'complete' : ActorMethod<[string, string], result_job>,
  'export_state' : ActorMethod<[], result_snapshot>,
  'fail' : ActorMethod<[string, string, [] | [bigint]], result_job>,
  'get_job' : ActorMethod<[string], [] | [job]>,
  'get_state' : ActorMethod<[], queue_state>,
  'grant_callback_scope' : ActorMethod<[Principal, string], result_unit>,
  'grant_worker' : ActorMethod<[Principal], result_unit>,
  'grant_worker_scope' : ActorMethod<[Principal, string], result_unit>,
  'import_state' : ActorMethod<[snapshot], result_unit>,
  'initialize' : ActorMethod<[], result_unit>,
  'list_jobs' : ActorMethod<[[] | [string], number], result_page>,
  'reconcile' : ActorMethod<[snapshot], result_reconciliation>,
  'recover_expired' : ActorMethod<[bigint], result_nat16>,
  'recover_interrupted' : ActorMethod<[], result_nat16>,
  'schedule' : ActorMethod<[string, string, bigint, string], result_job>,
  'schedule_with_callback' : ActorMethod<
    [string, string, [] | [Principal], bigint, string],
    result_job
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];