/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'team_id' : IDL.Opt(IDL.Text),
    'next_sequence' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'conversation_id' : IDL.Text,
    'body' : IDL.Text,
    'sender' : IDL.Principal,
    'sequence' : IDL.Nat64,
    'idempotency_key' : IDL.Text,
  });
  const Unread = IDL.Record({
    'conversation_id' : IDL.Text,
    'count' : IDL.Nat64,
    'user' : IDL.Principal,
    'last_read_sequence' : IDL.Nat64,
  });
  const Receipt = IDL.Record({
    'conversation_id' : IDL.Text,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'message_id' : IDL.Text,
  });
  const RoleGrant = IDL.Record({
    'role' : IDL.Text,
    'user' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'club_id' : IDL.Opt(IDL.Text),
  });
  const State = IDL.Record({
    'messages' : IDL.Vec(Message),
    'schema' : IDL.Nat32,
    'unread' : IDL.Vec(Unread),
    'governor' : IDL.Principal,
    'conversations' : IDL.Vec(Conversation),
    'receipts' : IDL.Vec(Receipt),
    'roles' : IDL.Vec(RoleGrant),
  });
  const MessagePage = IDL.Record({
    'messages' : IDL.Vec(Message),
    'latest_sequence' : IDL.Nat64,
    'next_sequence' : IDL.Opt(IDL.Nat64),
  });
  
  return IDL.Service({
    'create_conversation' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Principal)],
        [IDL.Variant({ 'Ok' : Conversation, 'Err' : IDL.Text })],
        [],
      ),
    'delete_message' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : Message, 'Err' : IDL.Text })],
        [],
      ),
    'export_state' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text })],
        ['query'],
      ),
    'grant_role' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_messages' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'list_messages_page' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Nat16],
        [IDL.Variant({ 'Ok' : MessagePage, 'Err' : IDL.Text })],
        ['query'],
      ),
    'mark_read' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : Receipt, 'Err' : IDL.Text })],
        [],
      ),
    'send_message' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : Message, 'Err' : IDL.Text })],
        [],
      ),
    'unread_count' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : Unread, 'Err' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };