/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Competition {
  'id' : string,
  'status' : string,
  'name' : string,
  'season' : string,
  'revision' : bigint,
  'club_id' : string,
}
export interface Init { 'governor' : Principal }
export interface JoinToken {
  'id' : string,
  'issued_by' : Principal,
  'used' : boolean,
  'team_id' : string,
  'competition_id' : string,
  'expires_at_ms' : bigint,
}
export interface Match {
  'id' : string,
  'status' : string,
  'home_team' : string,
  'away_team' : string,
  'away_score' : number,
  'home_score' : number,
  'revision' : bigint,
  'competition_id' : string,
}
export type Result = { 'Ok' : Competition } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : JoinToken } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : State } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : TeamEntry } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : string } |
  { 'Err' : string };
export type Result_6 = { 'Ok' : Match } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : Season } |
  { 'Err' : string };
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'competition_id' : string,
}
export interface Season {
  'status' : string,
  'name' : string,
  'revision' : bigint,
  'competition_id' : string,
}
export interface State {
  'seasons' : Array<Season>,
  'schema' : number,
  'entries' : Array<TeamEntry>,
  'matches' : Array<Match>,
  'tokens' : Array<JoinToken>,
  'governor' : Principal,
  'competitions' : Array<Competition>,
  'roles' : Array<RoleGrant>,
}
export interface TeamEntry {
  'status' : string,
  'team_id' : string,
  'competition_id' : string,
  'club_id' : string,
}
export interface _SERVICE {
  'claim_join_token' : ActorMethod<[string], Result_5>,
  'create_competition' : ActorMethod<[string, string, string], Result>,
  'create_season' : ActorMethod<[string, string], Result_7>,
  'export_state' : ActorMethod<[], Result_2>,
  'grant_role' : ActorMethod<
    [Principal, string, string, [] | [string]],
    Result_4
  >,
  'issue_join_token' : ActorMethod<[string, string, bigint], Result_1>,
  'record_match' : ActorMethod<[string, string, string], Result_6>,
  'register_team' : ActorMethod<[string, string, string], Result_3>,
  'set_match_result' : ActorMethod<[string, number, number, bigint], Result_6>,
  'set_season_status' : ActorMethod<[string, string, bigint], Result_7>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];