/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  const Result_5 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const Competition = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'season' : IDL.Text,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const Result = IDL.Variant({ 'Ok' : Competition, 'Err' : IDL.Text });
  const Season = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'revision' : IDL.Nat64,
    'competition_id' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'Ok' : Season, 'Err' : IDL.Text });
  const TeamEntry = IDL.Record({
    'status' : IDL.Text,
    'team_id' : IDL.Text,
    'competition_id' : IDL.Text,
    'club_id' : IDL.Text,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'home_team' : IDL.Text,
    'away_team' : IDL.Text,
    'away_score' : IDL.Nat16,
    'home_score' : IDL.Nat16,
    'revision' : IDL.Nat64,
    'competition_id' : IDL.Text,
  });
  const JoinToken = IDL.Record({
    'id' : IDL.Text,
    'issued_by' : IDL.Principal,
    'used' : IDL.Bool,
    'team_id' : IDL.Text,
    'competition_id' : IDL.Text,
    'expires_at_ms' : IDL.Nat64,
  });
  const RoleGrant = IDL.Record({
    'role' : IDL.Text,
    'user' : IDL.Principal,
    'team_id' : IDL.Opt(IDL.Text),
    'competition_id' : IDL.Text,
  });
  const State = IDL.Record({
    'seasons' : IDL.Vec(Season),
    'schema' : IDL.Nat32,
    'entries' : IDL.Vec(TeamEntry),
    'matches' : IDL.Vec(Match),
    'tokens' : IDL.Vec(JoinToken),
    'governor' : IDL.Principal,
    'competitions' : IDL.Vec(Competition),
    'roles' : IDL.Vec(RoleGrant),
  });
  const Result_2 = IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'Ok' : JoinToken, 'Err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'Ok' : Match, 'Err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'Ok' : TeamEntry, 'Err' : IDL.Text });
  
  return IDL.Service({
    'claim_join_token' : IDL.Func([IDL.Text], [Result_5], []),
    'create_competition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'create_season' : IDL.Func([IDL.Text, IDL.Text], [Result_7], []),
    'export_state' : IDL.Func([], [Result_2], ['query']),
    'grant_role' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'issue_join_token' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [Result_1],
        [],
      ),
    'record_match' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_6], []),
    'register_team' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_3], []),
    'set_match_result' : IDL.Func(
        [IDL.Text, IDL.Nat16, IDL.Nat16, IDL.Nat64],
        [Result_6],
        [],
      ),
    'set_season_status' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64],
        [Result_7],
        [],
      ),
  });
};

export const init = ({ IDL }) => {
  const Init = IDL.Record({ 'governor' : IDL.Principal });
  
  return [Init];
};