/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : string,
  'participants' : Array<Principal>,
  'team_id' : [] | [string],
  'next_sequence' : bigint,
  'club_id' : string,
}
export interface Message {
  'id' : string,
  'conversation_id' : string,
  'body' : string,
  'sender' : Principal,
  'sequence' : bigint,
  'idempotency_key' : string,
}
export interface MessagePage {
  'messages' : Array<Message>,
  'latest_sequence' : bigint,
  'next_sequence' : [] | [bigint],
}
export interface Receipt {
  'conversation_id' : string,
  'read' : boolean,
  'user' : Principal,
  'message_id' : string,
}
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : [] | [string],
}
export interface State {
  'messages' : Array<Message>,
  'schema' : number,
  'unread' : Array<Unread>,
  'governor' : Principal,
  'conversations' : Array<Conversation>,
  'receipts' : Array<Receipt>,
  'roles' : Array<RoleGrant>,
}
export interface Unread {
  'conversation_id' : string,
  'count' : bigint,
  'user' : Principal,
  'last_read_sequence' : bigint,
}
export interface _SERVICE {
  'create_conversation' : ActorMethod<
    [string, [] | [string], Array<Principal>],
    { 'Ok' : Conversation } |
      { 'Err' : string }
  >,
  'delete_message' : ActorMethod<
    [string],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
  'export_state' : ActorMethod<[], { 'Ok' : State } | { 'Err' : string }>,
  'grant_role' : ActorMethod<
    [Principal, string, [] | [string], [] | [string]],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'list_messages' : ActorMethod<[string, [] | [bigint]], Array<Message>>,
  'list_messages_page' : ActorMethod<
    [string, [] | [bigint], number],
    { 'Ok' : MessagePage } |
      { 'Err' : string }
  >,
  'mark_read' : ActorMethod<
    [string, string],
    { 'Ok' : Receipt } |
      { 'Err' : string }
  >,
  'send_message' : ActorMethod<
    [string, string, string],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
  'unread_count' : ActorMethod<
    [string],
    { 'Ok' : Unread } |
      { 'Err' : string }
  >,
  'update_message' : ActorMethod<
    [string, string],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];